### ISSUE TITLE
Doesn't build because package dependency is not published

### ISSUE THREAD

**Issue by haacked** [neo-project/neo-gui#10]
In a8ee56a80834e65a6b07a5c73e5c2ae5d2e86150 the version of `AntShares` was changed from `2.0.0-preview2` to `2.0.0-preview2-04` but that version does not appear to be published on NuGet. (https://www.nuget.org/packages/AntShares).

This makes attempting to build the solution fail.

**Comment by erikzhang** [comment]
You can pack it by yourself.
```dotnet pack -c Release```
Then add a local source to nuget.

**Comment by haacked** [comment]
Is that the intended development model? Or just a workaround. It'd be nice to not have to do that. Or, if that's a necessary step, perhaps include it in the README.

**Comment by sombraSoft** [comment]
@erikzhang , I think it would be nice to have some nuspec files to deploy the nugets more easily.
