### ISSUE TITLE
Windows neo-gui 2.3.6516.23119 issue with GAS

### ISSUE THREAD

**Issue by donnyque** [neo-project/neo-gui#100]
After not managing my NEO for a long time, I was trying to claim my GAS. I sent my NEO to myself and clicked the claim GAS button in neo-gui. After doing so, some time went by and the GAS I claimed is displayed as being in my wallet. 

![neoguiwallet](https://user-images.githubusercontent.com/33639956/32794562-7d4a5878-c969-11e7-86e4-e614074e9938.png)

I then wanted to transfer the GAS. Then this showed:

![neoguitransfer](https://user-images.githubusercontent.com/33639956/32794610-96ef2c4a-c969-11e7-88be-66b73e34310b.png)

I checked [Neotracker.io](https://neotracker.io/), and there it says this:

![neotracker](https://user-images.githubusercontent.com/33639956/32794614-9aed59ca-c969-11e7-98bf-42cb19cecab5.png)

I don't understand this. Can anyone help me?

**Comment by jonatanblockchain** [comment]
is the wallet full sync? if so, try rebuild the index. Wallet->Rebuild index.

**Comment by donnyque** [comment]
@jonatanblockchain I did that, and it didn't work. But found another solution: Downloaded a mobile wallet, imported my private key there and claimed the GAS. Then it finally worked.

**Comment by jonatanblockchain** [comment]
@donnyque Perfect!
