### ISSUE TITLE
Neo gui not starting

### ISSUE THREAD

**Issue by chenrongg** [neo-project/neo-gui#101]
I opened neo gui while it was zipped because I was in a hurry to send some neo to it. Now it won't start even when I unzip it. It did receive neo tho, hope it's not lost.
[error.log](https://github.com/neo-project/neo-gui/files/1485068/error.log)

**Comment by jonatanblockchain** [comment]
Looks like neo-gui can't find Chain folder, on root folder.

**Comment by chenrongg** [comment]
hm okay, what can I do?

**Comment by crazyroses** [comment]
Not quite the same issue but the correct title. Neo GUI had been running fine for me on Win 10 since August. This week attempting to start it results in a busy symbol for a few seconds, then nothing. Just downloaded 2.3.5 and no change in behaviour. I'll be happy for any advice of how to troubleshoot the problem.

**Comment by crazyroses** [comment]
Commenting for anyone else who finds this. I spotted the log file in the same folder as the NEO.exe, which indicated a database issue with the local chain copy. Searched for other reports and the answer was simply to delete the chain folder and start over. A little tedious but effective, and I see Erik has listed a bug or two so hopefully this will not happen with a later revision. Probably corrupted when my PC had frozen and needed a hard reset.

**Comment by stum74** [comment]
Hi, I solved this problem. Remove the folder CHAIN. And my neo started.

**Comment by croban** [comment]
Hi I have same problem, NEO Gui does not starts on WIN 10
But it starts if "run as administrator"?

**Comment by croban** [comment]
Well I have unzip neo inside C:/ProgramFiles... if I start it from there i need to run it as admin, moving the whole neo folder inside %appdata% resolved my starting issue
