### ISSUE TITLE
Can not claim my GAS!

### ISSUE THREAD

**Issue by jack4458** [neo-project/neo-gui#102]
Hello Community!
 
   I have the newest neo-gui wallet and this is my first time attempting to claim gas after owning NEO since antshares.  I have followed all of the instructions listed on here and not been able to claim my gas.

I transferred all of my NEO tokens to myself, and clicked claim gas. It shows everything available and I hit claim, a transaction appears in my history but it NEVER GETS CONFIRMED!  When I check the neotracker or neoscan.io or whatever, it still shows all of my gas as "unavailable".

When I go back into my neo-gui and rebuild the index, the gas I had, disappears, and goes back to being "unavailable".  

I then tried to send all of my NEO tokens to myself again, then all of that unavailable gas goes back to being "available"  

I hit claim gas. And it shows in my wallet again, but the transaction remains UNCONFIRMED, and does not show in the neo tracker.

Please Help!!

**Comment by jonatanblockchain** [comment]
If I understand well, doesn't matter if you claim gas to send NEO to yourself, transactions are never confirmed? It's the wallet full synced?

**Comment by jack4458** [comment]
Hello Jonatan, 
 
  Yes the wallet is fully synced, all block height numbers are matching.  

Correct, when I send the neo to myself, that transaction will confirm quickly, which makes my GAS available to claim.  I click to CLAIM the gas, but the transaction for the GAS claim never gets confirmed.  

After I rebuild the index, the failed transaction is gone, and my gas goes back to unavailable.  I resend my neo to myself again, the gas becomes available for claim.  Claim with the button, and same thing, that transaction just suck, never confirmed.

**Comment by jack4458** [comment]
still no luck with this. I've tried rebuilding and sending all neo, sending just 1, waiting for complete sync afterwards, Unavailable gas keeps building up, and once I do the 1 or All neo transaction to myself, all of the neo becomes "available".  When I try to claim this available gas, the transaction never gets confirmed.

I am tempted to just abandon this wallet and give NEON a try; but will I lose all of my GAS by switching?

**Comment by jack4458** [comment]
Bump

**Comment by pepijnolivier** [comment]
@jack4458 Which version are you running ? (Help > About)

Do you still have this issue on the latest version (2.5.2) ?

**Comment by jack4458** [comment]
@pepijnolivier Hi! I am using version 2.3.6

I will try to update to the newest version of neo-gui

thank you

**Comment by mdejavue** [comment]
For me, same problem. Claiming Gas with a new address works, but claiming with my old one from Antshare times, which has the most available Gas, does never get confirmed and is not explorable in Blockexplorers.
Tried Neon, Antshare Wallet, and NEO GUI.. no luck.

@jack4458 anything new?

**Comment by danielcrenna** [comment]
I'll try to reproduce it.

**Comment by jack4458** [comment]
*Update* using the newest neo gui wallet, it finally confirmed a gas claim !

**Comment by danielcrenna** [comment]
Ah, there you go. Perfect.

**Comment by jack4458** [comment]
Thank You all for the help. I was unaware that a new version of the wallet was released since I started this thread.  It seems whatever was causing that bug for people who created their wallet back when it was antshares has been fixed in the newest wallet.

Cheers all!
