### ISSUE TITLE
neo-gui wallet has stopped working 

### ISSUE THREAD

**Issue by eshaks** [neo-project/neo-gui#104]
could anyone please tell me how to get my neo-gui wallet working, I participated in the RPX token sale and It worked perfectly for few days after the token sale, but now it won't open at all, anyone facing same problem?

**Comment by Yippyiyo** [comment]
I have not experienced this but you can:

Locate the latest .DB3 file - Wallet Database?
Save a copy to a different location.

Uninstall Neo-Gui.

Reinstall Neo-Gui and replace the .DB3 file with the one you saved.

This method has worked with other similar programs.

Good luck.

**Comment by Zmirko** [comment]
Newest version of neo gui doesn't accept .db3 file ?

**Comment by erikzhang** [comment]
You can choose the wallet type at the right-bottom of the dialogue.

**Comment by Zmirko** [comment]
Yes, I can choose wallet type, but there is a problem. New wallet doesn't support .db3 files anymore. The wallet offered to me to update/convert .db3 file into .json file, which I did. Now, new wallet versions (2.5.0 and 2.5.2), accept that updated .json file, but when I open that .json file, it shows correct address, but with zero balance. Also, .db3 file has more than 44 Kb, but .json file has less than 1 Kb (44b), which is indicative that updated (.json file) is not succesfully converted.

**Comment by erikzhang** [comment]
You need to wait for the wallet to sync complete.

**Comment by Zmirko** [comment]
Complete sync took around 24h, but in the end everything is fine. Thank you Mr. Zhang !
