### ISSUE TITLE
NEO区块数据同步问题

### ISSUE THREAD

**Issue by zk5580752** [neo-project/neo-gui#108]
开发者，您好：
我这边使用Windows版的Neo-GUI时发现neo区块同步经常卡住，目前卡在了140w左右的区块位上，连接数一直为0，无法继续同步。请问如何解决？
PS. 我尝试过重建区块链接，但是也卡在了140w左右的区块上。

**Comment by erikzhang** [comment]
请关闭NEO-GUI，然后删除peers.dat，然后重新启动程序，应该就可以有连接数了

**Comment by zk5580752** [comment]
多谢Eric！~ 问题已经解决！~

PS. 我的使用环境如下：

- Windows 7
- neo-gui 2.3.65版本

**Comment by bigthomsan** [comment]
你好, 我是新手, 請問左下的3個區塊是否都要更新到一致的高度, 才會顯示錢包的內容?
另外, neo token轉入錢包之後, 是否會自動顯示?
