### ISSUE TITLE
How to import *.db3 file?

### ISSUE THREAD

**Issue by mzq1213** [neo-project/neo-gui#112]

**Comment by mzq1213** [comment]
Hi, I downloaded the latest version client. However, I can't browse my db3 file on it. How should I set up to import db3 file??
Thanks!

**Comment by erikzhang** [comment]
You can choose the wallet type at the right-bottom of the dialogue.

**Comment by bradranks** [comment]
I updated my client two days ago and it converted my DB3 file to a json file. Then, no balance shows. I get zero.

Any way to fix this? I looked at the json and the address is correct.

**Comment by Zmirko** [comment]
Same problem here few days ago, erikzhnag answered on it. Just let it fully sync, to be fully precise, first X of X/X/X in bottom left of neo gui wallet window must be equal with last two X of X/X/X. It took around 20 hours for me to sync, but i have HDD. With SSD I suppose it can be faster, don't know really. After fully sinc, your balance will be correct, don't worry. And don't delete your .db3 file, just in case.

**Comment by bradranks** [comment]
Thank you. I did get it working today by letting it fully sync and then closing the wallet, then performing a  rebuild index. Then it showed correctly.

cheers
