### ISSUE TITLE
NEO-GUI extremely slow

### ISSUE THREAD

**Issue by simonfqy** [neo-project/neo-gui#113]
Hi, I use Windows 10 and the latest version of NEO-GUI. Previously I was using Antshares client and it worked fine. In October, I downloaded NEO-GUI, and I think it should be the current edition. I copied the .db3 file from the Antshares repository into the NEO-GUI repository and it worked. However, the problem is that the synchronization speed is extremely slow. I think it is perhaps less than 10% of that of Antshares Client, and it can never truly keep up with the whole network, no matter how long it stays connected.

I didn't remember downloading [https://github.com/neo-project/leveldb](url), and I don't know how to "build" it on Windows 10. Is it a possible source of the problem?

Any help is greatly appreciated. Thank you very much!

**Comment by fabwa** [comment]
Please consider using boostrap files to sync the Chain (see https://github.com/CityOfZion/awesome-neo).
The Releases for windows you find here on github have the leveldb builds embedded.
