### ISSUE TITLE
Suddenly not receiving new blocks

### ISSUE THREAD

**Issue by Weldopedia** [neo-project/neo-gui#117]
+ I am running win10.
+ I have 10 connected peers.
+ I have upgraded to most recent GUI client (about says 2.5.6557.29435).
+ I have tried rebuilding the index.
+ I have tried deleting the chain folder, and also rebuilding after that.
+ I have gone into file properties for all files and selected "unblock."
+ I have tried allowing the host machine to be unfiltered through my firewall by all hosts and ports on TCP/UDP protocols.

Still, my GUI client is stopped at block 1723992.  It does not matter if I have a wallet database open or not.  How can I resolve?  This happened initially without any changes on my host.

**Comment by Weldopedia** [comment]
are there any other ports I need open, other than TCP 10333? I currently have TCP 10332-10333 and TCP 20000-20444 open

**Comment by Weldopedia** [comment]
As a work around, I've imported my private key into the NEON wallet, still, not what I want.  I wanted to do transactions last week.  Very disappointing.

**Comment by Weldopedia** [comment]
ok so, even on the Neon wallet with current block, my transactions are failing... is there a malfunction in the Neo network??  Is my address frozen?

**Comment by erikzhang** [comment]
Delete the `Chain` folder, and then resynchronize.

**Comment by Weldopedia** [comment]
I had already deleted the chain folder under GUI 2.5.2... I solved the problem by downgrading to 2.3.5, deleting the chain folder (2nd time) and rebuilding the index (3rd time)... not good.
