### ISSUE TITLE
Could not load file or assembly 'Replicon.Cryptography.SCrypt.MMA.dll' or one of its dependencies

### ISSUE THREAD

**Issue by classictoan** [neo-project/neo-gui#118]
Everytime I try to create a new wallet I just get an exception.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Replicon.Cryptography.SCrypt.MMA.dll' or one of its dependencies. The specified module could not be found.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.<EnsureCrtInitialized>b__3()
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.<>c__DisplayClass8`1.<EscapeExecutionContext>b__5()
   --- End of inner exception stack trace ---
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.EscapeExecutionContext[T](Func`1 callback)
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.EnsureCrtInitialized()
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.DeriveKey(Byte[] password, Byte[] salt, UInt64 N, UInt32 r, UInt32 p, UInt32 derivedKeyLengthBytes)
   at Neo.Wallets.KeyPair.Export(String passphrase)
   at Neo.Implementations.Wallets.NEP6.NEP6Wallet.CreateAccount(Byte[] privateKey)
   at Neo.Wallets.Wallet.CreateAccount()
   at Neo.UI.MainForm.创建钱包数据库NToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
neo-gui
    Assembly Version: 2.5.6555.37642
    Win32 Version: 2.5.6555.37642
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/neo-gui.exe
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Neo
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0.0
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Neo.DLL
----------------------------------------
Neo.VM
    Assembly Version: 2.0.3.0
    Win32 Version: 2.0.3.0
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Neo.VM.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Configuration.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Configuration.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Configuration.Json.DLL
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.FileProviders.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Configuration.FileExtensions.DLL
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.FileProviders.Physical.DLL
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Primitives.DLL
----------------------------------------
Microsoft.Extensions.FileSystemGlobbing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.FileSystemGlobbing.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.1.20720
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.25908.02
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/System.IO.Compression.DLL
----------------------------------------
Microsoft.AspNetCore.Http.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.AspNetCore.Http.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.AspNetCore.Hosting.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.AspNetCore.Hosting.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.DependencyInjection.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.DLL
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Configuration.EnvironmentVariables.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.DLL
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.DependencyInjection.DLL
----------------------------------------
Microsoft.AspNetCore.Http.Features
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.AspNetCore.Http.Features.DLL
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 4.0.2.1
    Win32 Version: 4.6.25519.03
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
Microsoft.AspNetCore.Http
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.AspNetCore.Http.DLL
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Options.DLL
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Logging.DLL
----------------------------------------
Microsoft.Extensions.ObjectPool
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.ObjectPool.DLL
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Core
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.Core.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting.Server.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.AspNetCore.Hosting.Server.Abstractions.DLL
----------------------------------------
Microsoft.Net.Http.Headers
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Net.Http.Headers.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.3.0
    Win32 Version: 
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/System.Runtime.DLL
----------------------------------------
Microsoft.AspNetCore.WebSockets
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.AspNetCore.WebSockets.DLL
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Hosting.Abstractions.DLL
----------------------------------------
System.Net.Sockets
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.25908.02
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/System.Net.Sockets.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Microsoft.EntityFrameworkCore
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.EntityFrameworkCore.DLL
----------------------------------------
System.Interactive.Async
    Assembly Version: 3.0.3000.0
    Win32 Version: 3.1.1.0
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/System.Interactive.Async.DLL
----------------------------------------
Remotion.Linq
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.1.30000
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Remotion.Linq.DLL
----------------------------------------
Microsoft.Extensions.Caching.Memory
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Caching.Memory.DLL
----------------------------------------
Microsoft.Extensions.Caching.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Extensions.Caching.Abstractions.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.Data.Sqlite
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.Data.Sqlite.DLL
----------------------------------------
Microsoft.EntityFrameworkCore.Sqlite
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.EntityFrameworkCore.Sqlite.DLL
----------------------------------------
Microsoft.EntityFrameworkCore.Relational
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Microsoft.EntityFrameworkCore.Relational.DLL
----------------------------------------
System.ComponentModel.Annotations
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.25519.03
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/System.ComponentModel.Annotations.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.2.0
    Win32 Version: 4.6.25519.03
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/System.Collections.Immutable.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
SQLitePCLRaw.batteries_v2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/SQLitePCLRaw.batteries_v2.DLL
----------------------------------------
SQLitePCLRaw.provider.e_sqlite3
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/SQLitePCLRaw.provider.e_sqlite3.DLL
----------------------------------------
SQLitePCLRaw.core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/SQLitePCLRaw.core.DLL
----------------------------------------
Replicon.Cryptography.SCrypt
    Assembly Version: 1.1.6.13
    Win32 Version: 1.1.6.13
    CodeBase: file:///C:/Users/Toan/Desktop/Neo/2.5.0/NEO-GUI/Replicon.Cryptography.SCrypt.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by fabwa** [comment]
Can confirm the above with a clean master build on Win10_64bit

**Comment by fabwa** [comment]
To solve this, please install vs2010 redist x86 and x64:

https://www.microsoft.com/de-de/download/details.aspx?id=14632

https://www.microsoft.com/de-de/download/details.aspx?id=5555
