### ISSUE TITLE
What is the actual size of the NEO Blockchian?

### ISSUE THREAD

**Issue by crypwin** [neo-project/neo-gui#119]
Hi, I am making a wallet an need to download the blockchain, but I have a slow internet connection.
I was wondering what the actual size of the Blockchain is and, ev. the last blocknr.

I looked everywhere but didn't find this information
Thanks for looking at this!
Erwin

**Comment by fabwa** [comment]
Currently the MainNet Chain sits at around 2GB.

Please use bootstrap files to accelerate the syncing process. You find these here:
https://github.com/CityOfZion/awesome-neo

**Comment by crypwin** [comment]
Thank You!

2017-12-28 20:29 GMT+01:00 fabwa <notifications@github.com>:
