### ISSUE TITLE
請問開發者, 有關區塊高度更新很慢的問題? 我是新手

### ISSUE THREAD

**Issue by bigthomsan** [neo-project/neo-gui#125]
開發者, 你好
, 我是新手, 請問左下的3個區塊是否都要更新到一致的高度, 才會顯示錢包的內容?
我現在高度在54512/54512/1306150就停下了, 我有刪除peers.dat, 這是跟我的網速有關嗎?
另外, neo token轉入錢包之後, 是否會自動顯示?

**Comment by zk5580752** [comment]
您好，区块链的操作都是基于最新的区块进行，如果你的三个高度不一致，说明你的本地数据并没有同步到最新的位置，并不是说你这会儿不能发起交易，而是说你现在的数据不是最新的，需要同步到最新的高度各项数据才显示正常。
例如：我的钱包最新的交易在54000进行的，而你已经同步到了54512，那么这会儿显示的钱包数据就是新的了，但是别的交易数据你都不完整。
如果你是最近将neo token转到钱包的，那么必须要更新的最新的数据区块才会显示。

另外，同步高度停下来了很可能是网络问题，你更换一个网络再试试。

**Comment by bigthomsan** [comment]
zk5580752
謝謝你的回答, 你說的我都可理解, 謝謝你! 另外我在客戶端那裡有下載离线同步包, 請問你知道那多少會更新一次? 最後一次是12/25!

**Comment by zk5580752** [comment]
貌似是一个月一次，可以看看NEO官方的说明，或者去Reddit上面咨询，那里更加活跃。

**Comment by bigthomsan** [comment]
謝謝你抽空回答問題, 謝謝!
