### ISSUE TITLE
Display error in neo-gui2.6.0preview with the transaction record.

### ISSUE THREAD

**Issue by Ray-77** [neo-project/neo-gui#128]
The transactions of voting can not show up correctly in the neo-gui2.6.0preview.

**Comment by Ashuaidehao** [comment]
Hi @Ray-77 , is this problem resovled in the last release version?

**Comment by Ashuaidehao** [comment]
Hi @Ray-77，we're planning to close this issue due to inactivity.
If you still have problems, please reopen this issue or create a new one.
@lock9 can you help to close this ,thanks!
