### ISSUE TITLE
cant create a wallet

### ISSUE THREAD

**Issue by TomdeWinter** [neo-project/neo-gui#132]
when i try to create a wallet, i get a nice crash:

************** Exception Text **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Replicon.Cryptography.SCrypt.MMA.dll' or one of its dependencies. The specified module could not be found.

whats going on here?

**Comment by TomdeWinter** [comment]
had to install the c++ distro's

**Comment by jzairick** [comment]
Hello everyone, I need a little help. I just installed Virtualbox on my Mac and installed NEO-GUI and once I try to create a new wallet it give me a similar error “Unhandled exception has occurred in your application. If you click Continue , the application will ignore this error ...” “Exception has been thrown by the target of an invocation”.

Please help me.
