### ISSUE TITLE
Unhandled error NEO-GUI  VM on Mac. 

### ISSUE THREAD

**Issue by jzairick** [neo-project/neo-gui#134]
Hello everyone, I need a little help. I just installed Virtualbox on my Mac and installed NEO-GUI and once I try to create a new wallet it give me a similar error:

 “Unhandled exception has occurred in your application. If you click Continue , the application will ignore this error ...” 

“Exception has been thrown by the target of an invocation”.

Please help me.

**Comment by rkovalov** [comment]
+1

**Comment by rkovalov** [comment]
@jzairick https://github.com/neo-project/neo-gui/issues/131
To solve this, please install vs2010 redist x86 and x64:
https://www.microsoft.com/de-de/download/details.aspx?id=14632

https://www.microsoft.com/de-de/download/details.aspx?id=5555
