### ISSUE TITLE
NEO GUI private key missing after exporting it to neotracker

### ISSUE THREAD

**Issue by crypwin** [neo-project/neo-gui#135]
HI,
I exported my Private key to neotracker because of an unspend issue,  After doing so the unspend issue was solved and I had my neo's in Neotracker.
  
When looking at the same wallet address in Neo Gui, the balance was still zero, and I saw that my private key was missing.  I got an error message. 
 
How can I restore this wallet address?

**Comment by WhaleChen** [comment]
@crypwin when you open the gui, you can use your private key to open wallet simply right click the blank white place and chose "导入" --> "导入wif" , and you will find the place to input your private key like below. 
![image](https://user-images.githubusercontent.com/11818114/34639978-1b071d3c-f325-11e7-9e82-3417fc5b7d86.png)
After that, you may `rebuild your wallet index`, more info you can see the [docs gui](http://docs.neo.org/en-us/node/gui.html)
