### ISSUE TITLE
neo-project git hacked?

### ISSUE THREAD

**Issue by flenning** [neo-project/neo-gui#136]
/Downloads $ sha256sum neo-gui-2.5.2.tar.gz 
828b1cffe4e9c0735218d34466f1bff3367eda732f248106e525b62a6c024f49  neo-gui-2.5.2.tar.gz
this is compleatly different to the sha256 key on your website

**Comment by erikzhang** [comment]
Where did you download the file "neo-gui-2.5.2.tar.gz"? All releases of neo-gui are compressed into ZIP files.

**Comment by WhaleChen** [comment]
@flenning 
[the download link](https://github.com/neo-project/neo-gui/releases) shows the sha256 only for `neo-gui-windows.zip`, not for Source code (tar.gz) 

```
$ openssl sha -sha256 neo-gui-windows.zip
SHA256(neo-gui-windows.zip)= 142591b20dc811aa01272c2fa078f0c54a1a6dc51edef883a47db759f048839c
```
No problem~  And what you download for linux is also can be reproduced, also no problem~
```
$ openssl sha -sha256 neo-gui-2.5.2.tar.gz 
SHA256(neo-gui-2.5.2.tar.gz)= 828b1cffe4e9c0735218d34466f1bff3367eda732f248106e525b62a6c024f49
```
