### ISSUE TITLE
neo lost

### ISSUE THREAD

**Issue by nathaleejoline** [neo-project/neo-gui#137]
I downloaded a neo gui wallet and gave it a password (on my laptop) and i bought one neo on a website and send it to the right wallet adres but i still have not my neo in my wallet and it's like three weeks ago I'v send it.. 
does anyone know what the problem can be?!

**Comment by jrsikors** [comment]
Need more information ... you need to check the wallets and/or transactions on the blockchain:
https://neotracker.io/
go to the website you bought it from and tried to transfer... it should have a TX (transaction) number... you can copy/paste that into the website above.  You can also search by wallet address .. either yours on your laptop or the wallet address on the website you bought it from.

**Comment by jrsikors** [comment]
and just in case that looks shady and I'm trying to steal your stuff :) -- go check the NEO reddit (just google NEO Reddit)
https://www.reddit.com/r/NEO/

On the right side of the page .. scroll down .. you will see that link under the "Block Explorers"

No one can do anything with your public wallet address or transaction numbers... those are literally available for the entire world to see.  Never give anyone PRIVATE key or passwords !

**Comment by nathaleejoline** [comment]
thank you for your reply!! I tracked it and he found it but I'm not sure what to do now, the adress is corresponding with my adres in my wallet so I don't understand. But my neo wallet is contantly busy with what is standing next to hight, left under. may be that's a culprit? I'd like to transfer the neo to my exchange from the tracker site? and then i'll remove my neo wallet because my laptop can't handle it, it become so slow..

**Comment by jrsikors** [comment]
read my comments on a similar topic:
https://github.com/neo-project/neo-gui/issues/141

Basically you need to get your wallet sync'd... the quickest way to do it is to download the bootstrap, described in #141  , and unzip it to your chain folder.

At that point -- you should sync the rest pretty fast

**Comment by jrsikors** [comment]
and unfortunately , sent you sent your NEO to your wallet on NEO-GUI -- you *HAVE* to at least use NEO-GUI until you get sync'd and can transfer off of it.

So do this:
step 1)  Close down neo-gui.exe if you have it running
Step 2)  go to https://github.com/CityOfZion/awesome-neo#blockchain-bootstrap-files
Step 3)  Download MainNet (MEGA - Chain.zip) - Up to block 1775832.
Step 4)  Unzip the mega - chain.zip to your NEO Chain directory.  Assuming you didn't mess with teh config.json .. the CHAIN folder will exist wherever you have NEO-GUI.exe.  So if your NEO-GUI.exe is in C:\NEO ... the CHAIN will be C:\NEO\CHAIN.  The chain folder will already exist, so you should know exactly where to put all the ldb files.
step 5)  run neo-gui.exe ... and after 10 minutes, make sure the numbers are moving.
step 6)  once the numbers are moving, open your wallet database
step 7)  wait a bit for it to sync (might be an hour, might be 5 hours)

**Comment by jrsikors** [comment]
And what I would do if I were you -- once your wallet gets sync'd, I would suggest using a NEON wallet instead of NEO-GUI or Exchange.  NEON will be better.

But you HAVE to do the 7 steps above first.  That's the only way to retrieve your NEO.

go to:
https://www.reddit.com/r/NEO/
on the bottom right under "Wallets" you will see:
Neon Wallet (CoZ) - Win - Mac - Linux - Video Tutorial

**Comment by jrsikors** [comment]
/Actually .. the .json wallet file is very similar to the NEON wallet format... does anyone know if nathaleejoline can install NEON wallet and load up the NEO-GUI generated wallet in NEON?

**Comment by Yippyiyo** [comment]
See answer to this "LOST NEO" issue in 143
