### ISSUE TITLE
net framework issue

### ISSUE THREAD

**Issue by gencosphere** [neo-project/neo-gui#138]
Hello,
i try to install gui but it says that it needs net framework, afterward , can't install net framework because it says that the netframe work is not compatible with operating system...
my operating system is windows 10 x64 and i dont know what to do here...
can someone help me please?

**Comment by jrsikors** [comment]
What .net framework is it telling you that you need to install?  And when you say "install GUI" .. you know there isn't really anything to 'install' technically.  You just download the zip, unzip it, and run neo-gui.exe.

**Comment by gencosphere** [comment]
it says i need 4.7.2..but i can't install 4.7.2 on the win10 x64 and sorry it's my bad...error runs when you click on the exe, not when install

**Comment by jrsikors** [comment]
I don't even think there is a 4.7.2 .net framework.  Google'ing for it only shows 4.7.1 as the highest.

When you say "can't install .net framework on win10 x64" .. where are you getting the installer from?  Microsofts website?

I have a fresh Windows 10 Pro x64 build .. from like a month ago... and I didn't have to install any .net framework to get the NEO GUI to load
My info:
Windows 10 Pro
version 1709
build 16299.192

I would try google'ing ".net framework windows 10", download and install the latest from Microsoft's website.

Is there a way you can post a screenshot of the error you are receiving.. ideally on both when you run the NEO-GUI.exe and then the error you are getting trying to install the .net framework.  That might help.

Another thing to try is what was suggested in #118  , download and install these (change the language when you get there if you aren't german :))

https://www.microsoft.com/de-de/download/details.aspx?id=14632
https://www.microsoft.com/de-de/download/details.aspx?id=5555

**Comment by gencosphere** [comment]
First of all, thanks for the help mate,
and second, sorry it was my bad...its 4.7.1.
i'm turkish
and here you go:

![1](https://user-images.githubusercontent.com/35220029/34742428-378cb8e4-f597-11e7-9c43-6d66b6f75fdb.PNG)
![2](https://user-images.githubusercontent.com/35220029/34742432-39c74372-f597-11e7-95e9-0dec8577d7c0.PNG)

**Comment by gencosphere** [comment]
it says "net framework is not supported with this operating system"in the 2nd one

**Comment by erikzhang** [comment]
Try 4.7

**Comment by gencosphere** [comment]
erikzhang no chance

**Comment by jrsikors** [comment]
What exact version of Windows 10 are you on?  Home? Pro? Enterprise?  And what build?

This website stats that the "Windows 10 Fall Creators Update" (No idea what that means) comes "Preinstalled with the OS"
https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements

You can also try to go looking for it to see if it's installed... but Windows sometimes puts it as an "installed update" and not a real "program)"
.NET Framework 4.5.x/4.6.x/4.7 cannot be uninstalled using this package. To uninstall .NET Framework 4.5.x/4.6.x from your computer, go to Control Panel, choose Programs and Features, choose View installed updates, select Update for Microsoft Windows (KB2828152) and then choose Uninstall.

Other than that - I'm kind of running out of ideas.  Your problem almost is definitely Windows 10 related and not necessarily NEO-GUI related.  

If I were you, I would 
  1)  Try to see if it's listed in the 'installed updates' or 'components' of your control panel.. and do an uninstall/install from there
  2) try to go download the 4.6 framework... the 3.5 framework... see if any of those will install.

Good luck !

**Comment by gencosphere** [comment]
it's win10 pro build 1511...
and i tried to see if it's sort of update on my op sys but there is no kind of update(KB2828152)
well..it's been very tiresome to dive deep in this situation and guess i'm going to leave it here for all of us.
Let's leave this kind of an info for the others
Again thank you for your effort to help me
