### ISSUE TITLE
antshares UI exception - 

### ISSUE THREAD

**Issue by ghost** [neo-project/neo-gui#14]
If I use the "Close" command to close the UI (upper left under the icon) instead of the X (Upper right) the app exits, but when I open the app again I get an error and the app fails to start. (error listed below).

Looking into the code, it may be because in MainForm.Designer.cs line 712 it only listens for the "Main Form Close" event instead of the "Window Close" event so the DB is not closed properly.

https://msdn.microsoft.com/en-us/library/system.windows.window.closing(v=vs.110).aspx
vs
https://msdn.microsoft.com/en-us/library/system.windows.forms.form.formclosing(v=vs.110).aspx

AntShares.Implementations.Blockchains.LevelDB.LevelDBException
Corruption: 613 missing files; e.g.: .\Chain/039966.ldb
   at AntShares.Implementations.Blockchains.LevelDB.NativeHelper.CheckError(IntPtr error)
   at AntShares.Implementations.Blockchains.LevelDB.DB.Open(String name, Options options)
   at AntShares.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at AntShares.Program.Main()

**Comment by erikzhang** [comment]
I have tested and found that either of "close" of "X" will raise the "FormClosing" event and DB will be closed.
