### ISSUE TITLE
Sent NEO to a not-synched wallet

### ISSUE THREAD

**Issue by BjornA3** [neo-project/neo-gui#141]
Hi, 

It took ages to sync my wallet (it is still at 1369392/1798909). My first question is can I speed this up?

My second question is: I already sent NEO's to the wallet (I didn't know it should have been synced before). Is this a problem?

Hope someone can help.

**Comment by BjornA3** [comment]
Also, the 1798909 is getting higher too

**Comment by jrsikors** [comment]
I just started a fresh 2.5.2 Neo-gui chain the other day .. and yeah it's taking forever after 1.3 million.  

There are 3 numbers when sync'ing (if you open your wallet)

The 3rd number is the latest block in the chain, so it getting higher isn't an issue
the 1st and 2nd numbers are essentially where you are in downloading the chain

You can check out this post, and download one of the bootstraps to download the whole chain, or get very close
https://www.reddit.com/r/NEO/comments/6p7fk1/tutorial_how_to_speedup_neo_blockchain/
https://github.com/CityOfZion/awesome-neo#blockchain-bootstrap-files

It's not a problem that you sent your NEO to the wallet.  Go to https://neotracker.io/  (you can see the URL on the NEO reddit page if you dont trust me:)) , and paste in your wallet address.  If your NEOs show up in your wallet address on the blockchain, you are fine.  You just need to wait til sync'd

**Comment by jrsikors** [comment]
I'm actually going to download the "MainNet (MEGA - Chain.zip) - Up to block 1775832." on the link above, because the sync'ing is crazy slow.  Pretty sure it wasn't this slow on the other versions, not sure if that has anything to do with it.

**Comment by BjornA3** [comment]
Thanks! I am now at 1775832/1775832. NEO's not showing up yet, do I just have to wait?

**Comment by jrsikors** [comment]
Hopefully you left it running for a bit -- 1,775,832 wasn't the latest block in the chain .. it was just the latest block in the bootstrap.  So you still needed to sync like 25,000 more blocks.  Mine sync'd within an hour or so.  Looks like 1,802,387 is the latest block in the chain.

Regarding the 3 numbers when syncing (IE 0/1,750,000/1,770,000)

The first number is where your wallet is syncd at.. so if you don't have your wallet loaded up it will be 0
The second number is where your 'computer' is syncd at
The third number is the latest number in the blockchain

So when your wallet is loaded, you want the first 2 numbers to catch up to the 3rd number, and you are sync'd at that point.

The NEO-GUI has been 'glitchy' in my opinion.  Sometimes when you load NEO, the 3rd number never goes up.  If you have your NEO-GUI.exe running, and the 3rd number never goes up after 15-20 minutes, I'd go ahead and close down NEO-GUI and re-run it.

**Comment by jrsikors** [comment]
But give it about 10 minutes before you close down.  Make sure you have at least 1 connection (connected = 1).  If you have 0 connections, then obviously nothing will go up.  So give it a chance to find some connections and start syncing before you close down and start it again.  But no movement after  10 minutes -- I would just close down and re-open.

**Comment by BjornA3** [comment]
I reinstalled a newer version (because the installed one gave errors), downloaded the chain again, synched it and received the NEO's. Thanks for the help!
