### ISSUE TITLE
NEO + GAS + DBC have dissappeared.

### ISSUE THREAD

**Issue by Yippyiyo** [neo-project/neo-gui#143]
AT2SAwx9oX7J4MerC6qUVjTRW4adXJ7ycD

NEO X 100

GAS X 2.04145602

DBC X 2,398.9013

UNCLAIMED GAS 1.14926268

I am using Version: 2.3.6458.21374 on Windows 7.

When I started NEO-GUI this morning and tried to open WALLET that field was blank. SO browsed and located the .DB3 file. NEO and GAS were there but DBC  was gone.

I then pressed REPAIR MODE hoping to recover the DBC and it all went to zero. 

Then with all zero balance I pressed REBUILD INDEX but still at ZERO NEO etc.

Any thoughts or ideas please.

HELP

**Comment by jrsikors** [comment]
Do you have an older backup copy of your db3 file?  Even if you made a copy of the db3 file with a 0 balance it's fine.

Either way, I would delete the entire CHAIN folder and rebuild it.  Probably download the bootstrap so you don't have to download the whole thing:
https://www.reddit.com/r/NEO/comments/6p7fk1/tutorial_how_to_speedup_neo_blockchain/
https://github.com/CityOfZion/awesome-neo#blockchain-bootstrap-files

**Comment by Yippyiyo** [comment]
Thank very much jrsikors.

I think I have the solution.

As long as you have your NEO address and your private key there is not a problem.
Go to neotracker.io and select "open wallet".

The choose "Private Key". And enter your WIF oe HEX key.
That will open up and you will see your NEO, GAS etc.

Then uninstall existing desktop wallet. Install new neo-gui and create a new wallet database (different address).
Update the Blockchain. Then send the online NEO to your desktop wallet.

My numbers are:
0/1778240/1806903The first number 0 is new. That was not in previous Neo-Gui.
(What does that mean. Counts up then resets.)
Close your database and it may update more quickly.
I am doing this right now.

(Found it in error was sniffing around NEOTRACKER ).

Good luck.

Try the NEO online wallet and let us know if it works.
BUT IT DOES CONCERN ME BECAUSE ALL NEO-GUI DESKTOP WALLETS ARE ONLINE!!!!
IF YOU HAVE THE PRIVATE KEY!!!!

**Comment by Yippyiyo** [comment]
My problem may have been caused by NEO network issues?
Anyone have a zero balance now?

Also cannot send NEO, GAS, or claim GAS, DBC from neotracker.io wallet

https://twitter.com/neotrackerio?lang=en

**Comment by Yippyiyo** [comment]
AS others have posted here recently I too am having problems with seeing NEO stuff in the latest NEO-GUI (252). The NEO, GAS and DBC all appear on neotracker.io but do not appear  in the latest desktop wallet.
Solution for me was to go back to the wallet I was using when this issue occurred.

I do not understand why the NEO community is generally unaware that when you install NEO-GUI on your desktop you automatically receive a neotracker.io wallet from where you can send, receive claim gas etc.

Simply go to neotracker.io/wallet and open wallet; enter your private key. 

VOILA there you will clearly see the contents of your neo-gui wallet.

From there you recover your coins should they disappear from your wallet.

Simple solution to a reasonably common problem.
