### ISSUE TITLE
Send NEO 3rd wallet to NEO GUI wallet but NEO GUI doesn't show 

### ISSUE THREAD

**Issue by eakoh101** [neo-project/neo-gui#147]
Please resolve me

**Comment by Yippyiyo** [comment]
See #150

**Comment by jrsikors** [comment]
any update?

What is your public address of your wallet?
What is the TX number?
Is your NEO-GUI fully sync'd?  what 3 numbers are showing in the bottom left?  (IE:  1,827,124 / 1,827,124 / 1,827,124)

**Comment by jrsikors** [comment]
Would close this -- no response / update in 2 weeks.

**Comment by jrsikors** [comment]
@erikzhang can close this up .. no response
