### ISSUE TITLE
I send NEO to my NEO Gui Wallet and it doesnt arrive. 

### ISSUE THREAD

**Issue by SamuelBiallowons** [neo-project/neo-gui#150]
Hi like I sad, i sended them but hey don't arrive in my wallet. Can you please help me?

**Comment by Yippyiyo** [comment]
Hi

Best thing to do right now is to identify your environment.

Operating system etc.

Tell as much as you can

Most important!  
Read some the recent posts here #141 to 143,
You may find something there to assist.

Once you read some of recent posts you will then have a better idea on how  to progress your situation.

**Comment by jrsikors** [comment]
Any update on this ?

**Comment by jrsikors** [comment]
Would close this -- no response / update in 2 weeks.

**Comment by jrsikors** [comment]
@erikzhang can close this, no response from OP
