### ISSUE TITLE
Transfer neo from Account not working

### ISSUE THREAD

**Issue by Kiqui** [neo-project/neo-gui#151]
Hi , 
I am trying to withdraw Neo from my account . But it says that Transaction initiated but signiture is incomplete. Any help apreciated.

**Comment by Yippyiyo** [comment]
See #150

**Comment by jrsikors** [comment]
I see you have another issue open ... is this issue resolved?  Is this the same/related to your other issue?

**Comment by Kiqui** [comment]
Yes I thought the two might be connected. The issue is not resolved.

**Comment by jrsikors** [comment]
@erikzhang  you can close this one and make it a duplicate of #152

**Comment by erikzhang** [comment]
Duplicate of #152
