### ISSUE TITLE
Option to specify dir to store blockchain data

### ISSUE THREAD

**Issue by jphellemons** [neo-project/neo-gui#153]
I have other fullnode clients on my pc and use my E partition to store blockchain data. I cannot find the option in the GUI to move/change the dir.

**Comment by erikzhang** [comment]
The settings are in `config.json`.

**Comment by jphellemons** [comment]
Line 4:
````
{
  "ApplicationConfiguration": {
    "Paths": {
      "Chain": "Chain",
````
Ok so the GUI needs a FolderBrowserDialog to select another location. Will maybe try to setup a local dev environment.

**Comment by jrsikors** [comment]
It's slightly bothersome at this time -- when they update the NEO-GUI client...

you basically have to:
step 1)  Make a backup of your config.json
Step 2)  Unzip latest NEO release into folder (it comes with a default config.json so it will overwrite your custom)
Step 3)  Copy your config.json from step 1 back to the directory

And to throw another layer -- in the past they have changed the "format" of the config.json ... so using an old format config.json with a newer NEO-gui.exe will sometimes make it crash without explanation.

So really the process is:
step 1)  Make a backup of your config.json
Step 2)  Unzip latest NEO release into folder (it comes with a default config.json so it will overwrite your custom)
Step 3)  Evaluate/compare the default config.json that comes with the new release to your copy of config.json from step 1 ... adjust as necessary
Step 4)  Copy your config.json from step 1 back to the directory ... or if the config.json format is different, then update the 'new default' config.json with your CHAIN.  

Luckily it's a pretty simple config.json, even when they change it, for custom chain folders.

**Comment by jrsikors** [comment]
Also in case you haven't figured it out .. the format for the chain would be something like:

> "Chain":  "E:\\\\NEODATA\\\\CHAIN",

with the double \\

Are you good to go now ?

**Comment by jrsikors** [comment]
should be 2x \ ... \\\\ ... apparently github makes me put in 4x \ to be able to show 2 of them

**Comment by jrsikors** [comment]
You good to go with this?  Any issues?

**Comment by jphellemons** [comment]
Sure, it's no problem for me, but it's perhaps something to build in the GUI for other user who are less comfortable editing json files. (and post about it on github)

**Comment by jrsikors** [comment]
In the dozen or so other cryptos I've been involved with, and their GUIs, none of them have ever really offered a smooth way to change the default location of the chain data for us OCD folks.  I either have to make a bat file and use a --datadir="e:\blabla" , or edit some config file.  Maybe I've been unlucky.

If you think about it logically -- as soon as you open up the GUI -- it *immediately* locks in to the "data directory", and starts verifying , downloading new blocks, etc.  I think there must be a reason why most(?) crypto wallets don't offer the option through the GUI.  

The only thing they could do is offer an option to edit the config file .. and if you change it .. it will re-start the client.

But I would say with almost certainty that this would cause more problems, as people would have an easy way to mess up their config files, and then come to this forum to ask for help fixing it :).

If I had a vote, I'd vote to keep it the same, and make the 'advanced users' figure out how to edit their config files.  I also had to Google or ask on a forum to figure out how to edit the config.json , but I consider it pretty normal to have to do that in crypto world.

Up to Erik though !

**Comment by jphellemons** [comment]
Some have it in the installation wizard and lets you specify the dir. (bitcoin gold I thought) I believe the Monero client gives you the option to change it in the GUI. But not all parts of Monero (importwizard) use the same settings. Since it is in the config, I thought it would be nice to have it configurable.
If you have an SSD for the OS and applications and a huge several tb's hdd for block data, it'd be nice to separate them.
I do agree on the 'advanced users' part! Google Chrome also keeps some settings a bit more hidden for users. Perhaps do not make it configurable in the gui, but only in the installation wizard?

**Comment by jphellemons** [comment]
Tried today by the way and got an error file in the neo dir:
````
System.InvalidOperationException
Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at Neo.UI.MainForm.Blockchain_PersistCompleted(Object sender, Block block)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Neo.Core.Blockchain.OnPersistCompleted(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
````

**Comment by jphellemons** [comment]
Never mind, it worked.
