### ISSUE TITLE
Not able to create a new Wallet

### ISSUE THREAD

**Issue by arunikhanna81** [neo-project/neo-gui#154]
Hi, 
am trying to create a NEO wallet on my machine. However getting the attached error. Could you please advise?

Thanks
Aruni
<img width="336" alt="neoguierror" src="https://user-images.githubusercontent.com/35453020/34940122-7f673626-fa42-11e7-8c20-67e4816a0684.PNG">

**Comment by erikzhang** [comment]
Duplicate of #118
