### ISSUE TITLE
update new gui wallet - can not see my rpx and qlc amount

### ISSUE THREAD

**Issue by kukomah** [neo-project/neo-gui#155]
Hi,

I have my old neo gui wallet, installed just before the rpx ico.
now i download the latest version of neo gui wallet, i copy my chain folder, so I am fully synchronized (in the latest block), but now in my latest version only neo and gas amount is shown. I can not see rpx and qlx amounts (those two can be seen in neon 9 wallet). What is the issue? What should i do, to be able to see my other assests except neo and gas? Yesterday i participate in the trinity donation, will i be able to see them in my new version of neo gui?

thanks

**Comment by jonatanblockchain** [comment]
What do you have in Advanced-> Options -> NEP5 Contract List? 

Not sure if you have to add just the scripthash from the contracts.

RPX (RedPulse) - 0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9
QLC (Qlink) - 0x0d821bd7b6d53f5c2b40e217c6defc8bbe896cf5
TNC (Trinity) - 0x08e8c4400f1af2c20c28e0018f29535eb85d15b6

https://neotracker.io/browse/contract/1
