### ISSUE TITLE
issue transfer never comes NEO GUI

### ISSUE THREAD

**Issue by Knib** [neo-project/neo-gui#156]
HI guys
I ve send 1 neo to my wallet address: APV592sgMHYs3uBV9XrEhQbY8HuspTYZEa  and gas ,2 days ago

nothing never comes..i can track it with the txid but nothing in the wallet NEO GUI

ty for your concern

**Comment by jonatanblockchain** [comment]
Is you neo-gui in sync? Must be fully synchronized before use.

**Comment by Knib** [comment]
i think is that but i open it more than 48h . 70000sync and still get a Million to get sync

ty

**Comment by Knib** [comment]
a full week with neo gui opened 24h/24 i guess

**Comment by jonatanblockchain** [comment]
You can download a copy of the of the blockchain.
http://docs.neo.org/en-us/node/gui.html#synchronizing-blockchain-data

Use these:
https://github.com/CityOfZion/awesome-neo#blockchain-bootstrap-files

**Comment by jrsikors** [comment]
When you open NEO-GUI.exe, and you load your wallet, all 3 numbers in the bottom left corner need to be around the latest block (neotracker.io -> blocks).  Currentlatest block is 1,827,655

So the 3 numbers in the bottom left should say like:
1,827,655 / 1,827,655 / 1,827,655

If they don't -- you aren't synced.  If they aren't moving, try closing down NEO-GUI and re-open

![ss3](https://user-images.githubusercontent.com/31370541/35073011-a33f24a8-fbac-11e7-806d-ab2761849053.PNG)

**Comment by Knib** [comment]
great ty, i can t figure before that  i have to wait more than 3 days with
neo gui load on :)

**Comment by Knib** [comment]
i tried to sync neo gui ,so i let it download (2 times) to get the 3 numbers equals,but the both times ,the software doesn t respond anymore when i try to open it(when the download is over).It s 3 days wasted for each try and now i m getting desperate

**Comment by jrsikors** [comment]
Alright let's start over:
 1)  what operating system do you have?
 2)  what version of NEO-GUI are you using?

I'm not sure what you mean by "Software doesn't respond anymore when trying to open it".

You can't get all 3 numbers to show unless you can open the software, and then open your wallet.  So I'm confused as to where and when your app is getting locked

**Comment by Knib** [comment]
what i mean when i said : "Software doesn't respond anymore when trying to open it" is that i click on neogui.exe and no respond from the software anymore .Before it used to open normaly  until syncronsiation
I m on Windows 7 professional
i download the latest version of neo gui on this site and i repeat that the soft was working well during the syncronisation

**Comment by Knib** [comment]
now i m trying download the chain.zip ,ii  will let you know if it  works

**Comment by jrsikors** [comment]
Check anti-virus programs as well, I know mine caught NEO-GUI.exe as a "false-positive" and tried to quarantine it.

You might try disabling anti-virus just for a few minutes as a test to see if that helps.

**Comment by jrsikors** [comment]
But logically it makes sense --- once you are fully sync'd with the blockchain ... sometimes NEO-GUI.exe can take a while to open up... especially if you are on an older / slower machine.

I have a brand new desktop with plenty of CPU and RAM... and sometimes it takes about 5 minutes after i click NEO-GUI.exe for it to actually open.   

So try to be patient after you double click it (like give it an hour):
   ~Reboot your computer first
   ~Make sure no other programs are running and eating up lots of CPU/RAM
   ~Make sure Anti-Virus is disabled temporarily

**Comment by Knib** [comment]
hello,
1st : i reboot my PC then i click on neogui.exe and wait 2 hours but nothing happened

2nd : i disable my anti virus and try to open neo gui without success 

3rd: i download the file [chain.acc.zip](http://static.neo.org/client/chain.acc.zip) and put it on my share neogui ,start the soft,wait a bit and 
It works! 

ty everybody
