### ISSUE TITLE
Can't see your NEO in your wallet after you send it?

### ISSUE THREAD

**Issue by Yippyiyo** [neo-project/neo-gui#157]
AS others have posted here recently I too had problems with seeing NEO in the latest NEO-GUI (2.5.2). The NEO, GAS all appeared on neotracker.io but did not appear  in the latest desktop wallet.

DO NOT PANIC. 

This is how I fixed my problem. It may also work for you.

1.  Make a copy of your all your keys.
Open your neo-gui and go to:
WALLET
OPEN WALLET DATABASE
In the dialogue box that pops up BROWSE to your .db3/.json file.

So when you open that wallet file highlight the ADDRESS and right click.
In the box 4th on the list is VIEW PRIVATE KEY. Click on that and Copy 
every line in the new box. Save all the info to a text file and keep it safe.
NEVER EVER SHARE YOUR PRIVATE KEYS!

2. Now go to neotracker.io and click on OPEN WALLET.
Click on PRIVATE KEY
Paste your HEX or WIF key on the line mid page.
Click on UNLOCK and then GO TO WALLET.

You can now see all your missing NEO, GAS etc.
I do not understand why the NEO community is generally unaware that when you install NEO-GUI on your desktop you automatically receive a VERY PRIVATE neotracker.io wallet from where you can send, receive NEO, claim GAS etc.
=========================================

I fixed my problem by installing an earlier version of NEO-GUI. I re-installed V 2.3.5. 
When it was sync'd I then sent my NEO from neotracker.io/wallet to my newly installed wallet.

==============================================================
Because you are sending your NEO to a new addess your coins will disapper from your original neotracker.io/wallet.

But if you then input your new private key into neotracker.io OPEN WALLET you will again see the contents of your latest wallet.

Simple solution to a very common common problem.

:)

**Comment by jonatanblockchain** [comment]
Perfect. Remember that the neo-gui must be fully synchronized before use. Its documented.
http://docs.neo.org/en-us/node/gui.html

**Comment by Yippyiyo** [comment]
Instead of closing this you should have pinned this as addressing  a very
common neo-gui issue.

What is wrong with Eric.

You should have sent me 1000 NEO as a reward for posting that solution!
AKd8ooeutZfCB9jXAmxVxn2sA1duGD429o

What is wrong with you.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by erikzhang** [comment]
As @jrsikors has said in another post (https://github.com/neo-project/neo-gui/issues/142#issuecomment-357148193), your private key is generic and can be loaded into any wallet. So your statement is actually misleading, not that you will automatically get a neotracker.io account when you install the NEO-GUI.
And, here is the NEO-GUI code base to solve the NEO-GUI problem as a primary goal, rather than avoiding the problem and directing the user to other wallets. Although we do not exclude users from using other wallets, NEO-GUI problems should be tracked and resolved.
