### ISSUE TITLE
关于 AntShares.GUI “合约地址” 的bug

### ISSUE THREAD

**Issue by ericwen** [neo-project/neo-gui#16]
合约地址 A 如果有四个签名（private key）A1,A2,A3,A4
A上有100ans，

如果从A向标准地址B转账20ans，A地址上的ans数量就为0，剩下的80ans会转给A1。
这显然不符合逻辑，应该是一个bug。

如果从A想标准地址A1转账20ans，A地址上的ans数量也会为0，剩下的80ans会转给A2。
这也不符合逻辑。

正常的逻辑应该是，A向其他地址转账20ans后，还剩下80ans。

My NEO Address: AehTaz2GVU5BTqtbPVHbdGaAhSgYrhemTR

以下以两个privatekey为例：
![ans bug](https://user-images.githubusercontent.com/3114126/28073733-3d895b82-6689-11e7-9a0b-d64adff818f7.png)

**Comment by fabwa** [comment]
This in intended - see https://en.bitcoin.it/wiki/Change

**Comment by erikzhang** [comment]
找零默认会进入第一个标准地址。
因为系统无法判断合约账户的脚本逻辑，所以不能确保进入合约的钱能否再一次被使用，所以为了安全起见找零会默认进入标准地址。
如果需要找零到原地址，可以手动指定。
