### ISSUE TITLE
Unhandled exception has occurred error

### ISSUE THREAD

**Issue by defaultuser99** [neo-project/neo-gui#161]
Hi guys

Trying to access wallet and getting this error.

![capture](https://user-images.githubusercontent.com/35526389/35041484-add04356-fbd0-11e7-926c-6a7056f71f0e.PNG)

Thanks for your concern!

**Comment by jrsikors** [comment]
Had exact same problem... this resolved it for me:

#118 

To solve this, please install vs2010 redist x86 and x64:
https://www.microsoft.com/de-de/download/details.aspx?id=14632
https://www.microsoft.com/de-de/download/details.aspx?id=5555
(change from german to your language)

**Comment by jrsikors** [comment]
any update?

**Comment by defaultuser99** [comment]
Worked perfectly! 

Thank you.

**Comment by defaultuser99** [comment]
Worked Perfectly!

Thank you.

**Comment by iamn3rdz** [comment]
where did you install these to?

**Comment by iamn3rdz** [comment]
nvm you just run the .exe file lol
noob alert

**Comment by iamn3rdz** [comment]
this worked for me as well! finally wow
