### ISSUE TITLE
dealing with multiple keys with different passwords

### ISSUE THREAD

**Issue by snowypowers** [neo-project/neo-gui#163]
How will neo-gui deal with multiple keys with different passwords?

Lets say I have a wallet with 2 keys labeled `keyA` and `keyB` with passwords `a` and `b` respectively.

Currently, i can only supply 1 password. I give the password `a` and the wallet unlocks. However, I get an error when i attempt to view `keyB`'s private key.

If I supply `b` as the password, this results in a `incorrect password` message instead. It seems like the app only cares about the first account in the array?

**Comment by jrsikors** [comment]
When you say "key" , do you mean "Address"?

I don't know how  you would get 2 addresses in the same wallet with different passwords.. the password is for the "wallet", not necessarily for the "address".

Did you import "b" from a WIF or a Certificate?

**Comment by snowypowers** [comment]
It is very possible for 2 keys with different passwords to exist. Neon wallet allows you to craft each address individually before exporting everything in a wallet file.

**Comment by jrsikors** [comment]
Yeah I was just curious how you did it through the NEO-GUI ... which you answered .. you didn't do it through the NEO-GUI :)

I would have to defer to the NEO-GUI devs on this one .  Obviously they are 2 completely separate wallets, so it would make sense that unique features in NEON would be specific to NEON, and not necessarily transferable to NEO-GUI.

**Comment by Ashuaidehao** [comment]
Hi @snowypowers , can this issue be closed? Seems you have found an alternative wallet.
