### ISSUE TITLE
Neo GUI- funds transfered to watch only address

### ISSUE THREAD

**Issue by MashiRod** [neo-project/neo-gui#165]
I used the Neo-GUI to make a Neo transfer from my wallet to my Bittrex account. However, the amount I tranfered was credited on my Bittrex account without problems BUT the balance of my Neos on the wallet were sent to a new wallet address and appears now as "watch only address" in the Neo-GUI!

How can please help to get access to the Neos on the "watch only address" wallet.

**Comment by jrsikors** [comment]
Why do you need to "access" the NEO in your watch only address?  You only had X amount of NEO, and you successfully sent it.  Are you thinking you got free NEO ?

**Comment by jrsikors** [comment]
I couldn't find a NEO reference for Watch Only Addresses, but this one should work:
https://bitcoin.org/en/glossary/watch-only-address

If you have a public address and the private key, and that public address has funds in it, then access them.  

I can create a watch only address on any public address.. one with 100,000 NEO.. that doesn't mean I can claim them :)

**Comment by MashiRod** [comment]
Hello Jeff,

Thank you for your fast reply. I'm not thinking to get free NEO, it would be great but that would be like getting free Money :-)  I only want to recover the lost NEO.

I performed the following transfer:

[https://neotracker.io/tx/d832459fcbf9c1838d4ccc173cda4bc92a34efa992c5269cc30b31155b438b7b](url)

d832459fcbf9c1838d4ccc173cda4bc92a34efa992c5269cc30b31155b438b7b

My balance on my wallet was 20843 before the transfer. I transferred 11067 to Bittrex. These NEO we credit to my Bittrex account correctly BUT the remaining 9776 NEO were also transferred to a new address. **This address was created (not by me!) exactly the same moment when the transfer was executed.** The following picture will explain this.

![transfer_1](https://user-images.githubusercontent.com/35744076/35352651-e909fd6c-0144-11e8-8f39-2cbe955c8630.jpg)

![transfer_2](https://user-images.githubusercontent.com/35744076/35352832-7e7c0372-0145-11e8-8046-db691c4164f9.jpg)

The new wallet appears as a "watch only wallet" on the NEO GUI
What happened or went wrong? How can I recover the NEO?

Thank you in advance.

**Comment by jrsikors** [comment]
I figured that was the case, but just checking!

That's pretty odd -- that's usually the way transactions look when you are sending *FROM* an Exchange *TO* another wallet .. just the way Exchanges work.  

Also -- the date on there is over 1 year old.  December 27, 2016. ... did this happen over a year ago and you are just now noticing?

Looking at wallet address 

https://neotracker.io/address/AbEM51hVzJsf65Lop9WbLjLjEdenbZK5zQ

There are definitely 9,776 NEO on AbEM51hVzJsf65Lop9WbLjLjEdenbZK5zQ ... and GAS is increasing and unclaimed.

If you don't have the private key for AbEM51hVzJsf65Lop9WbLjLjEdenbZK5zQ ... you might be in trouble.

**Comment by jrsikors** [comment]
Can you include screenshot of your NEO-GUI wallet?

You might want to check to see if you have older copies of your NEO wallets... maybe one of them has AbEM51hVzJsf65Lop9WbLjLjEdenbZK5zQ as a real address.

I didn't start using NEO-GUI until around summer 2017, so I'm not sure if this was a known issue a year ago ?  Maybe someone else from around that time recalls this happening?

**Comment by MashiRod** [comment]
Sorry for my late reply. I was some days off. Here is the screenshot of my NEO-GUI wallet:

![img-20180129-wa0000](https://user-images.githubusercontent.com/35744076/35767113-047c38d2-08e6-11e8-878f-aa6474019740.jpg)
This happened a year ago and I tried to solve the problem by myself without success. I also get in Contact with the NEO support but I didn't get an answer. Now I found this place and hope someone can help. If there is a solution and I can recover the NEOs I will be of course very grateful.

**Comment by jrsikors** [comment]
Yeah I feel sick to say this because it's a lot of money now -- but here are the facts:

~There are 9,776 on the public address AbEM51hVzJsf65Lop9WbLjLjEdenbZK5zQ
https://neotracker.io/address/AbEM51hVzJsf65Lop9WbLjLjEdenbZK5zQ

~If you don't have a private key for AbEM51hVzJsf65Lop9WbLjLjEdenbZK5zQ ... or it's not included as 'your address' in any of your old wallet files... there just simply isn't a way to access that address / funds.

Even though I am 100% sure they were yours, if there was any 'backdoor' way to access funds simply by knowing a public address ... cryptocurrency would be 0% secure and there would be no point / faith in it.

Did you keep multiple copies of your .db3 wallet file or .json files?  Like every time you transferred you made a backup copy?

In my opinion (I'm not with the NEO team/support) , your only chance would be to try to find old wallet files and maybe you have a wallet where AbEM51hVzJsf65Lop9WbLjLjEdenbZK5zQ  is an actual address.

Good luck man, hopefully someone has some magic up their sleeve and can assist.. I cannot :(

**Comment by grishatataru** [comment]
I have the same thing,how can we fix this issue?

**Comment by grishatataru** [comment]
@MashiRos
Did you find a solution?
I have the same exact issue

**Comment by grishatataru** [comment]
@jrsikors 
Im in the same situation where my NEO moved from NEON wallet to a watch Address

How can we fix this problem?

**Comment by grishatataru** [comment]
Nobody?

**Comment by jrsikors** [comment]
It's pretty simple and straightforward:
If you don't have the private key for the address, you don't own the coins anymore

That being said --
you mentioned NEON wallet ... this is for NEO-GUI.  If it was the NEON wallet, you will definitely want to move the issue to the NEON wallet team's page/issues.

I've made tons of transactions in both NEO-GUI and NEON, and never had issues.  What was the TransactionID that caused the split?

**Comment by grishatataru** [comment]
<img width="1006" alt="screen shot 2018-09-18 at 12 58 54 pm" src="https://user-images.githubusercontent.com/39939426/45710033-b5f88980-bb42-11e8-968c-c04288777232.png">

How do i get in contact with NEON wallet team?

**Comment by grishatataru** [comment]
d611ee0824d14ee633b08b2995890728a69a5b2a975981096367f4cccd7fafb7

**Comment by jrsikors** [comment]
why did you send NEO to this address:
https://neotracker.io/address/AcWyPgfSVovTnE5rG6w3KNMCcoipjuDBxP

Did you not own AcWyPgfSVovTnE5rG6w3KNMCcoipjuDBxP ?

The NEON Wallet is developed by CityofZion:
https://github.com/CityOfZion/neon-wallet/issues/

**Comment by grishatataru** [comment]
Thats the problem
I never sent ANYTHING
I own the AVjDZ7VVz7foeqFmdW2R5okbjr1pTEmEBs address and i have the private KEY to this address only
I never AUTHORIZED any Transactions

Do you mind checking this forum please?
https://github.com/CityOfZion/neon-wallet/issues/524

Ive been posting everything there

**Comment by jrsikors** [comment]
Yeah I was looking at that actually thread in between my posts here..

It sounds like there's a bug between NEON and Ledger Nano. 

You posted a screenshot of this address:
https://neotracker.io/address/AKJQMHma9MA8KK5M8iQg8ASeg3KZLsjwvB

That definitely looks like a 'hackers wallet' based on the fact that there's tons of transactions constantly going in.  If it's not a hacker's wallet, it's definitely a "bugged wallet" that has something to do with Ledger and NEON.

But yeah -- unless Ledger Nano / NEON people can help you get the private key for this address:
https://neotracker.io/address/AcWyPgfSVovTnE5rG6w3KNMCcoipjuDBxP

I don't know of any way to assist you.  It looks like you got quite a few responses from smart people over on that 524 issue... and they basically said the same things I was thinking.  Sorry man :frowning_face: 

I'd keep posting on the CoZ thread 524 that you have been on.  Maybe they will eventually come up with a solution.  Or you can try their Reddit or Discord if they have one.  I've found that sometimes Github isn't monitored by all the people who know how to fix this type of stuff.  

So if i were you I'd go find CityofZion's Discord and/or Reddit and try there.

**Comment by dsc3425** [comment]
Resurfacing this old chain since I am having a similar problem. For some reason years ago I transferred my Neo to "watch" - now I can get in my watch but don't have the private encryption key to get into it in the regular way. Any advice?
