### ISSUE TITLE
私链将合约中1亿neo转出时提示没有找到可以签署该交易的私钥

### ISSUE THREAD

**Issue by zhangsj** [neo-project/neo-gui#166]
![image](https://user-images.githubusercontent.com/7639036/35318968-c16b774e-0118-11e8-9d1d-d6a8603a69cb.png)

**Comment by chenzhitong** [comment]
你应该打开私有链中的共识节点的钱包，然后添加合约地址，而不是新建钱包添加合约地址。
[参考文档](http://docs.neo.org/zh-cn/node/private-chain.html#5提取-neoneogas)

**Comment by zhangsj** [comment]
是用的共识节点钱包

**Comment by hsiaosiyuan0** [comment]
> NEO-GUI 版本： 2.7.6744.26727
> 共识节点 CLI 版本: 2.7.6.1

我也遇到同样的问题，四个共识节点的钱包分别是 wallet1~4，以其中任意一个钱包发起转账交易，在剩余的第三个钱包进行签名时，都会出现上面的截图 “没有找到可以签署该数据的私钥”。不知道出现这样的问题还有什么可能性吗？

**Comment by hsiaosiyuan0** [comment]
找到问题了，我一直都是由任意一个钱包开始，然后一直操作到第 4 个钱包，而实际上是由任意一个钱包开始，再操作两个钱包即可：

>然后系统会提示“交易构造完成，但没有足够的签名”，然后将代码复制下来，打开第二个钱包，点击 交易 签名 粘贴刚才复制的代码，点击 签名， 然后将代码复制下来，__打开第三个钱包__，点击 交易 签名 粘贴刚才复制的代码，点击 签名， 这时你会发现窗口中出现了一个 广播 按钮，代表交易已经签名完成（达到多方签名合约要求的最少签名数量）可以广播，点击 广播 后转账交易开始广播，约 15 秒后转账成功。

**Comment by Ashuaidehao** [comment]
Hi @lock9, this issue was resolved and can be closed.
