### ISSUE TITLE
new 2.6 client making me re-download whole chain from 0/0/0

### ISSUE THREAD

**Issue by jrsikors** [neo-project/neo-gui#167]
I'm not sure if it's because I'm using a custom CHAIN directory in the config.json ,, but the new NEO 2.6 client always starts from 0/0/0.

Have tried deleting all the data out of chain -- downloading the latest neochain.zip bootstrap .. but even though my chain folder is 2.0GB + , NEO-GUI 2.6 always seems to want to start me from 0/0/0.

I can/will just let the client re-download the chain.. this is just an FYI

**Comment by jrsikors** [comment]
And I did verify that that NEO-GUI is accepting my config.json ... the CHAIN did not re-create anywhere.  My custom chain folder is the place where all the LDB files are 'downloading' to.

**Comment by jrsikors** [comment]
I'm finally all re-sync'd and good to go on this by the way.  No one else had this issue?  Just lucky me? :)

**Comment by stormcleric** [comment]
I had this problem too.  Where did you download the latest neochain.zip bootstrap from?

**Comment by jrsikors** [comment]
2.6.0 doesn't seem to like any of the bootstraps when I did it... it wants to do the download through NEO-GUI... 

check out #178

**Comment by jrsikors** [comment]
It does have a disclaimer on the releases page under 2.6.0:

**_Important: When upgrading to this new version, the old blockchain database will no longer be available and the blocks will be automatically re-synchronized. It is recommended to back up the older chain data in advance and to export offline synchronization data chain.acc to speed synchronization._**

But it would be nice to know if there will ever be 'bootstraps' available again

**Comment by erikzhang** [comment]
http://static.neo.org/client/chain.acc.zip

**Comment by stormcleric** [comment]
> It does have a disclaimer on the releases page under 2.6.0:

Yep, I read that disclaimer but I don't have a chain.acc file in my data folder. I've been using an old wallet - can't say which ver right now. I had a chain folder full of data files anyway but the new version seemed to ignore that.

> http://static.neo.org/client/chain.acc.zip

Thanks! I'll try that.

**Comment by jrsikors** [comment]
@erikzhang   maybe please put that link in the notes under 2.6.0 ?

**Comment by panzengott** [comment]
I had the same problem. I´ve been forced to resync the hole Blockchain.
And after 4 fuc ... Days of downloading.
Its rewarding me with full refusal and wont open !!!

error.log shows:
Neo.IO.Data.LevelDB.LevelDBException
Corruption: 24 missing files; e.g.: Chain/1239620.ldb
   bei Neo.IO.Data.LevelDB.NativeHelper.CheckError(IntPtr error)
   bei Neo.IO.Data.LevelDB.DB.Open(String name, Options options)
   bei Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   bei Neo.Program.Main()

So do i have to download the hole BS again?
This would be very annoying !!!

**Comment by jrsikors** [comment]
check out:
#178 

There are some steps towards the bottom of the thread that will potentially help speed it up
