### ISSUE TITLE
Password incorrect message after switch from DB3 to Json

### ISSUE THREAD

**Issue by NEZ9** [neo-project/neo-gui#168]
Starting around New Year at some point my NEO-Gui backup wallet file would no longer accept my password. Not sure what might cause this issue but I saw someone post in a wallet issue thread on reddit with similar/same issue. Mistakenly didn't backup my private key, didn't anticipate an issue like this.
I've basically written this off as a loss but I might as well ask here, as you guys seem to have the best technical support.

Thanks for any suggestions

**Comment by jrsikors** [comment]
If you have your old DB3 file -- I would go download an older copy of NEO-GUI and get it sync'd.. then send it off to a new address.  

I was having trouble converting DB3 to JSON, and didn't trust it .. so I sent all my funds on my DB3 wallet to my NEON wallet ... then I created a new json wallet in NEO-GUI, and sent my funds back.

Hopefully you still have a backup copy of your DB3 file before you started trying to convert it ... and just go download an older NEO-GUI where it won't ask you to convert the DB3.

You might need to tinker around with it -- maybe even delete the whole chain folder.. maybe even do it on another computer that never had NEO-GUI installed.

**Comment by NEZ9** [comment]
Got it sorted out now! Thanks for the help.

**Comment by jrsikors** [comment]
@erikzhang   ok to close this
