### ISSUE TITLE
can´t make new Block 

### ISSUE THREAD

**Issue by Ragnar84** [neo-project/neo-gui#170]
So my Neo-gui wallet has been working without proplems for some time in fact I never had any proplems with it until today.

After I wake up today I went on my computer en klickt on the neo wallet icon.The wallet did not open immediately, but after about 30 sec i klickt 2 times more on the icon and it opened without a problem or so seemed to be. When I close the wallet another one pops up and then another so what happend was the 2 attempts I tried did open up to.

,,The waiting for next block,, bar was moving my balance was the same and so I copy to clipboard my address and transferred my neo to claim my neo-gas.

Normally to get 1 confirmation takes about 30 sek up to 2 min so I walk away from the computer and when I was back it was still not confirmed.

Then I noticed that the ,,Height,, had not changed is has been on 1860095/1860095 for about 5 hours now, and having over 9 connections.

I have tried to ,,rebuild index,, 2 times. Now it looks like my transfer I tried earlier got cancelled and my balens is still the same and the Height is still on 1860095/1860095. can anybody help me ?

![neo prplem](https://user-images.githubusercontent.com/31337009/35476115-abc19d60-03a2-11e8-8371-e5f5dbd8d1dc.PNG)

**Comment by jrsikors** [comment]
Sorry for the obvious suggestion, but have you tried rebooting?  It sounds like you accidentally opened multiple instances of NEO-GUI and that might have 'corrupted' your chain data.

Reboot
Open NEO-GUI
rebuild index

If you have done that already, i would do this if it was me...
I would download one of these bootstraps:
https://github.com/CityOfZion/awesome-neo#blockchain-bootstrap-files

Close NEO-GUI 
delete everything in the chain folder 
unzip the downloaded bootstrap into the chain folder
open NEO-GUI

It also looks like you are on an older version of NEO-GUI.  Although I don't advise upgrading right now until you get this figured out.. I would suggest upgrading at some point.

**Comment by Crypt0Bro** [comment]
I'm having the exact same problem - stuck on block 1860095. Did the above recommendation fix your problem?

**Comment by jrsikors** [comment]
Are you also on a version of NEO-GUI that is not the latest?  
https://github.com/neo-project/neo-gui/releases

_Neo GUI v2.6.0
@erikzhang erikzhang released this 7 days ago · 2 commits to master since this release_

If that's the case, it's possible older version of NEO-GUI aren't compatible past that block .. something happened in the chain?

**Comment by jrsikors** [comment]
Note on the 2.6 release:
**_Important: When upgrading to this new version, the old blockchain database will no longer be available and the blocks will be automatically re-synchronized. It is recommended to back up the older chain data in advance and to export offline synchronization data chain.acc to speed synchronization._**

I bet you need to upgrade to 2.6 and re-download the chain

**Comment by jrsikors** [comment]
before you upgrade ... MAKE SURE you have a copy of your .db3 or .json wallet file stored elsewhere.

If you have a db3 wallet file, I would even suggest getting your private key for your address(es) in case you have issues converting db3 to json.  

Quite a few people have had issues converting db3 to json.  The fix is to download the Microsoft 2010 c++ redists .. but I wouldn't take that risk if I were you.  Get the private keys.. so if you can't convert, you can just load your old addresses using the private key and WIF

**Comment by Crypt0Bro** [comment]
Hey thanks for the help! 
I made a backup copy of the whole NEO directory including the Chain directory and files. Then I downloaded the latest wallet version 2.6 and downloaded the latest Chain.acc and moved it into the new Chain folder. Started up the new NEO wallet and the synchronization got to Height: 0/1866102/1866102 and then I logged into my wallet database. It is showing 0 NEO and 0 GAS. But the first number (0) after Height started updating. At what point should I see my tokens? OR is there another step I should take?

**Comment by jrsikors** [comment]
the first number is where your "wallet" is in terms of block number.  So as soon as the first number gets up to where you are sync'd, your funds will show

**Comment by Crypt0Bro** [comment]
Ok. Thanks man! I thought that might be the case. But, not used to seeing 3 numbers at the bottom of the screen.

**Comment by malxes** [comment]
Help please, sent the neo tokens to the exchange, the purse left the purse, and there is no stock exchange, in the transaction antchain there is such a drawing

**Comment by malxes** [comment]
![default](https://user-images.githubusercontent.com/35693532/35527481-e21eae76-053b-11e8-961b-e78178cb4409.jpg)

**Comment by malxes** [comment]
Help please, sent the neo tokens to the exchange, the purse left the purse, and there is no stock exchange, in the transaction antchain there is such a drawing

**Comment by malxes** [comment]
Help please, sent neo tokens to the exchange, money from the purse went away, and there is no stock exchange, in the transaction antenchain here is such a drawing

**Comment by malxes** [comment]
Help please, sent neo tokens to the exchange, money from the purse went away, and there is no stock exchange, in the transaction antchain here is such a drawing

**Comment by malxes** [comment]
what is written in the picture?

**Comment by jrsikors** [comment]
Go look for the transaction and/or wallet in a different chain explorer like https://neotracker.io/

How many confirmations are you seeing in your NEO-GUI transaction list?

**Comment by malxes** [comment]
![default](https://user-images.githubusercontent.com/35693532/35528840-32e1a152-0540-11e8-9f40-d5a8f16797bb.jpg)

**Comment by malxes** [comment]
this is the deal. I understand she is hung?

**Comment by malxes** [comment]
how to increase the speed of confirmation? shows 1,160 confirmations

**Comment by jrsikors** [comment]
You should have enough confirmations.  As far as the blockchain is concerned ... your transaction went through fine.

Transaction looks like it went through fine:
https://neotracker.io/tx/3bed68e1c3cb995e9f0fa31518725f734e8c5805662e5df072ebcf5299e84623

This address now has 5 NEO:
AZieTK3evurdDTq9aS3DP7SWfT8scwLkXt
https://neotracker.io/address/AZieTK3evurdDTq9aS3DP7SWfT8scwLkXt

What's the problem?

**Comment by jrsikors** [comment]
if the address: _AZieTK3evurdDTq9aS3DP7SWfT8scwLkXt_ is your NEO address **_in an Exchange_** .. you will need to open a ticket with the Exchange.

**Comment by malxes** [comment]
thank you very much!you helped me a lot

**Comment by jrsikors** [comment]
@erikzhang  ok to close
