### ISSUE TITLE
File Hashes Don't Match the Downloadable File

### ISSUE THREAD

**Issue by levipage** [neo-project/neo-gui#173]
According to download page:

File: neo-gui-windows.zip
SHA1: A7FD62609F3133D62171E8190DE23C47C09BDA34
SHA256: C24D0AA92275A1061515DADE9F5A127330FEE5AA38B15D4EE31DCD6F85957ED

.... but hashes don't match

Actual SHA1 is 485097D3E38C96D4B1DBE98F9D436431F7829140
Actual SHA256 is 2C97B4788BF10A5B4122E3A3337268AEF03C8DD33C279D04469320254A2209EA

**Comment by jrsikors** [comment]
The hashes referenced:
**_File: neo-gui-windows.zip
SHA1: A7FD62609F3133D62171E8190DE23C47C09BDA34
SHA256: C24D0AA92275A1061515DADE9F5A127330FEE5AA38B15D4EE31DCD6F85957ED_**

are for:
Neo GUI v2.2.0
@erikzhang erikzhang released this on Aug 20, 2017 · 31 commits to master since this release

....

Are you talking about the older version of Neo GUI v2.2.0 ?

**Comment by levipage** [comment]
I am talking about this page:
https://github.com/neo-project/neo-gui/releases/tag/v2.2.0

For the file that is available for download here and hashes listed, they don't match.

**Comment by jrsikors** [comment]
Although I agree it should be looked into -- I wouldn't advise anyone to be using older versions of NEO-GUI.  People with versions prior to 2.6.2 seem to be having issues with syncing:
https://github.com/neo-project/neo-gui/issues/170

**Comment by levipage** [comment]
Okay np. The page I referenced was linked to by an article detailing a list of NEO wallets. I will check out the latest version. I didn't realize that wasn't the newest one. Thanks!

**Comment by jrsikors** [comment]
Sorry and just to clarify, i was calling it 2.6.2, but it's really 2.6.0 !

Let us know if you have issues with 2.6.0 , will be happy to help !

@erikzhang and team will need to look at the 2.2.0 hash problem.. not something I can do !

**Comment by erikzhang** [comment]
I reviewed the hashes of v2.2.0, they do match the file.

These are the outputs of 7zip:

```
---------------------------
Checksum information
---------------------------
Name: neo-gui-windows.zip
Size: 4103107 bytes (3 MB)

CRC32: F63A8CB7

CRC64: D9D2DCAD2F6CE658

SHA256: C24D0AA92275A1061515DADE9F5A127330FEE5AA38B15D4EE31DCD6F85957ED0

SHA1: A7FD62609F3133D62171E8190DE23C47C09BDA34

BLAKE2sp: 08DB3987EFDCD5F161A29A7A8E1755AF658AA9151398EFD5E66F75C95EE255B3

---------------------------
确定   
---------------------------
```
