### ISSUE TITLE
NEP5 TRANSFER PROBLEM

### ISSUE THREAD

**Issue by PeterLinX** [neo-project/neo-gui#174]
![_20180130131829](https://user-images.githubusercontent.com/18521923/35549367-260a7726-05c0-11e8-8c62-56fa62989b45.png)
Transfer NEP5 asset successfully, however, the tx in tx list cannot be confirmed.

**Comment by Ashuaidehao** [comment]
Hi @lock9 ,  is there any plan to fix the bug?

**Comment by lock9** [comment]
Since this is not critical, it will only be fixed in next neo-gui release.
Sorry for the inconvenience!
