### ISSUE TITLE
My NEO-GUI Wallet suddenly not opening

### ISSUE THREAD

**Issue by g4usat** [neo-project/neo-gui#176]
Hi, I have installed NEO-GUI wallet on my Windows7 in December and it was working pretty good until today morning. Am not sure what happened, but when I double click the exe file, it's not opening at all now. 
![neo_issue](https://user-images.githubusercontent.com/36013227/35646073-9d6a98c2-0693-11e8-8f71-239cf6f8c7f1.PNG)
Last night I transferred some coins from binance to my wallet and the wallet hasn't got updated as of today morning. But, in the blockchain, I saw and it showed up so i left it to check the wallet later. When I tried to open the wallet this afternoon and check if its got updated with the new transfer, the wallet doesn't open at all. 
Appreciate if anyone can help me.
Thank you!

**Comment by jrsikors** [comment]
Try right clicking and running as administrator.

I had something similar happen to me.  Nothing changed at all, but one day the NEO-GUI decided to stop opening unless I run it as administrator.

I would also recommend downloading the latest 2.6.0 wallet.  The older wallets don't seem to be syncing past a certain block.

**Comment by g4usat** [comment]
I did that and it didn't work. I checked the error.log and this is what it shows:
Neo.IO.Data.LevelDB.LevelDBException
Corruption: not an sstable (bad magic number)
   at Neo.IO.Data.LevelDB.NativeHelper.CheckError(IntPtr error)
   at Neo.IO.Data.LevelDB.DB.Get(ReadOptions options, Slice key)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main()
can you pls guide me how to fix this issue? thanks again

**Comment by jrsikors** [comment]
Just to clarify -- when you say "Wallet wont open", do you mean:
  A) NEO-GUI won't open
  B) Your wallet file (.db3 / .json) won't open while in NEO-GUI 

Here is what I would do:
 1)  Make a copy of your .db3 / .json wallet file and move it to a safe directory / jump drive
 2)  Delete all NEO-GUI 2.5 files and the chain directory ... everything except your wallet (db3 or json file which you already took care of in step 1 :smile: )
 3)  Download the **latest** 2.6.0 NEO-GUI
 4)  Unzip
 5)  Run NEO-GUI.exe ... if that doesn't work try running "as administrator"

**Comment by g4usat** [comment]
What I mean is the "NEO-GUI" won't open. I didn't see anywhere in the folder directory the .db3 file but I do see .json file. But, I haven't done anything yet with that file.
Unfortunately, I didn't save my private key yet and this has hung up. I hope am ok..please help me recovering this wallet...thanks again!

**Comment by g4usat** [comment]
NEO-GUI is not opening both ways 1)double clicking the .exe file or 2) right click and run as Admin. It's not running in the background too(checked in task manager). Am not sure what's happening with my wallet, I tried to open the wallet online at "neotracker.io" using the JSON file, but it says "Invalid Keystore File". Am really worried now...someone please help me fix my wallet without having to download another one.

**Comment by jrsikors** [comment]
They are 2 different things:
1). Your .json is your WALLET
2). NEO-GUI is an APPLICATION 

Go upgrade 2 as I suggested and dont touch 1

-Jeff

**Comment by g4usat** [comment]
So, I need to delete all the files except .JSON file and install the new upgraded 2.6 NEO GUI. With this, I won't lose my coins right? because I don't have the private key and also am not sure why did I get "Invalid Keystore File" error message at neotracker.io when I tried to open wallet using .JSON file. 

I don't have the private key and am really worried if I may lose my coins by deleting files and installing the new NEOGUi. I hope you understand my concern...can you pls confirm if am good and nothing to panic. Really appreciate ur help.Thanks a lot!!

**Comment by jrsikors** [comment]
I understand your concern.

As I said -- keep your .json file completely safe.  This is your **wallet**.  Lose this and you are 100% screwed.  At this point -- you are fine.

You don't even need to delete anything as i suggested if it makes you nervous... do this instead:

1)  Make a new directory on your c drive called C:\NEO260\
2)  go to https://github.com/neo-project/neo-gui/releases and download the 2.6.0 (neo-gui-windows.zip)
3)  unzip neo-gui-windows.zip to C:\NEO260
4)  browse to c:\NEO260 and run NEO-GUI.exe ... try regularly and then try as administrator

You are now running NEO-gui.exe 2.6.0 .  You will have re-download the whole NEO chain, but this is fine and normal, so it might take hours.

If you get NEO-GUI.exe 2.6.0 open, you can do the same thing you've been doing in 2.5, you simply open your json file that is your wallet.  Your balance/funds wont show up until you are fully sync'd.

**Comment by jrsikors** [comment]
also -- check your anti-virus.  I would suggest disabling anti-virus for 5 minutes, and try to open NEO-GUI.exe.  Sometimes Anti-Virus labels these crypto wallet apps as "False Positives".

**Comment by g4usat** [comment]
Great Thanks a lot...Will do as you mentioned. And after installation, when I open NEO-GUi.exe 2.6.0, I will need to select my existing JSON file path to open the wallet and it opens up as it used to until now, right?

**Comment by jrsikors** [comment]
Yep -- and if that  doesn't work out -- you still have your NEO-GUI 2.5 installed to another directory, and you can keep troubleshooting on that.

When you open NEO-GUI .. open your wallet .. type in your password ... do a right click on the address and get your private key.  You don't need to wait until full sync to do this step.

**Comment by g4usat** [comment]
THANKS A TON....It hit me reg the Antivirus and I've excluded NEO from Windows Defender..Lo and behold..the NEO-GUI App opened up. It's not synced and showing 0 balance. But, I think it takes time and it's ok. The next thing immediately I did is got my private key and saved it. Now, am relaxed..will wait for this current version to synch up and probably later I'll try installing the 2.6 version. yesterday there was a system update of windows 10 on my laptop and this started after this and the new update restricted NEO-GUI to run it. That's why I couldn't think of this option of excluding in antivirus 'coz I was thinking that it was running until this morning fine.. Lesson learnt is "Windows 10 sucks"

Again, can't thank enough for your help...Really appreciate it..

**Comment by jrsikors** [comment]
Good to hear man, you are welcome  !

**Comment by jrsikors** [comment]
@erikzhang  @g4usat erik or g4 you can close this issue please !

**Comment by briguy1** [comment]
Hi,

I am currently trying to upgrade my neon wallet since because I don't have the most recent update. Can someone explain how too do this. I already downloaded the new wallet off the Neon website, but now im trying to take my neo from my old wallet and transfer it too my new one but cant figure out how its done. Can someone please explain!

**Comment by jrsikors** [comment]
NEON wallet or NEO-GUI?

**Comment by g4usat** [comment]
Its NEON wallet. I have older version of it and can I upgrade it to newer
version without having to do any manual transferring of coins? I mean can I
just upgrade it and open the new wallet as like the older version?


Best Regards,
Srinivas Takuri

**Comment by jrsikors** [comment]
you might want to go to the CityofZion page and ask NEON questions there -- but basically you can upgrade NEON and you don't need to upgrade your wallet.

Your wallet is stored in C:\Users\YOU\AppData\Roaming\NEON\Storage

You should take a backup of the userWallet.json

But you should post over in their forum to confirm if you want:
https://github.com/CityOfZion/neon-wallet/issues

**Comment by g4usat** [comment]
Ok, Thanks Jeff...Will check over there...


Best Regards,
Srinivas Takuri
