### ISSUE TITLE
Slow UI startup during weak internet connection

### ISSUE THREAD

**Issue by jnlewis** [neo-project/neo-gui#177]
When the update manifest file at https://neo.org/client/update.xml couldn't be reach during app startup, the main UI does not show until connection timeout or when the file is finally downloaded. Showing a "checking for updates" form would be helpful.

![capture](https://user-images.githubusercontent.com/3898665/35731922-7d4a7880-0852-11e8-8ddf-8dea57bce636.JPG)

**Comment by Ashuaidehao** [comment]
Hi @lock9 ,the url is a dead link now, do we have plans to improve it?

**Comment by lock9** [comment]
@Ashuaidehao  this is very important, this causes a really bad use experience, and has a very low "cost to fix". 
Any chances you guys could make a PR to remove this load? If the url is dead, there is no sense  to keep this load.

**Comment by Ashuaidehao** [comment]
Hi @erikzhang , is there someone who maintain the “update.xml” file?
If no one maintains it, maybe we should remove these useless code.

**Comment by erikzhang** [comment]
No one is currently maintaining this file. But maybe we can put this file on Github so that any core developer can maintain it.
