### ISSUE TITLE
Incorrect balances after upgrade (NEO-Gui 2.0 -> 2.6)

### ISSUE THREAD

**Issue by soonliteh** [neo-project/neo-gui#178]
Hi,
I am a long-time user of NEO-Gui. All the while, I have been using version 2.0, until recently when I needed to see my NEP-5 token, which requires version 2.6. Here is the chronology of what happened:
1. Downloaded version 2.6 and offline sync data (chain.acc)
2. Extracted chain.acc in the NEO-Gui root directory
3. Opened NEO-Gui but it crashed within seconds
4. Deleted chain.acc file and re-opened NEO-Gui
5. Opened my wallet database; the only file I had was .db3
6. Saw prompt message that .db3 will be converted to .json; pressed "Ok"
7. NEO and NeoGas balances showed 0, but I thought I should wait till block sync completed
8. Block height sync completed, but balances are still 0

Note: Previous block height info on version 2.0: XXX/XXX
          Current block height info on version 2.6: XXX/XXX/XXX

What I am seeing now is: 73/73/1837941. The last number is the correct current block height.

Could someone help me with why I am seeing zero balances on both NEO and NeoGas?
Thanks!

**Comment by jrsikors** [comment]
the last/3rd number is the block height.
first 2 numbers 73/73 are where your wallet (balance) is actually sync'd at.

So once those first 2 numbers reach the correct block height, you will be fine.  If you left neo-gui running for the past 11 hours since you posted, i'm assuming you are probably fine now.

If those first 2 numbers aren't moving, you got issues and need to close down neo-gui and re-open... and if they are still stuck, i would advise deleting the entire chain directory and letting the client re-sync.

**Comment by soonliteh** [comment]
I had done what you suggested before posting it here, so obviously those steps didn't work (1. Left the GUI run for over 20 hours; 2. Closed it down and re-opened.)

How to properly delete the entire chain directory? Also, is there a clean way to uninstall the GUI?

**Comment by jrsikors** [comment]
Are your first 2 numbers increasing at all?  It can take a looong time.  If it's still increasing, i'd keep at it.

**How to properly delete the entire chain directory?**
Just delete all the files in it

**Also, is there a clean way to uninstall the GUI?**
Are you downloading the zip file?  Or are you downloading an exe to install?

Really I would do this if I were you -- it would take care of both of your issues.

step 1)  Go to https://github.com/neo-project/neo-gui/releases and download the 2.6.0 neo-gui-windows.zip
step 2)  Create a directory on your C: like C:\Crypto\NEO260\
step 3)  unzip from step 1 to the directory in step 2
step 4)  Run neo-gui.exe from the directory in step 2

**Comment by jrsikors** [comment]
and it should go without saying -- make sure you keep many backup copies of your .db3 wallet files and/or .json wallet files

**Comment by jrsikors** [comment]
Also -- check your CPU in Windows Task Manager.  Make sure NEO isn't eating up all the CPU:
#172 

When I installed 2.6.0 and had to do the re-sync, it probably took me a couple days.  I would keep an eye on my CPU/memory when I could and just closed out NEO-GUI.exe and re-opened it, if it was eating all my CPU/Memory

It's kind of brutal -- but you'll get through it I promise :smile:

**Comment by soonliteh** [comment]
1. Yes, it took a long time, and the first two numbers moved nowhere from 73/73/xxx.
2. Yes, it also consumed my CPU/memory. My computer was extremely laggy the whole time.
3. **Question: When you said "delete all the files", were you referring to the files in Chain folder or the entirety of NEO-Gui folder?**
4. I downloaded the .zip file, I don't think there was an option for .exe for version 2.6.
5. **Question: If your answer to Question 3 is "delete the entirety", should I also wipe out all the version 2.0 and version 2.6, before re-downloading version 2.6?**
6. Yes, I have my backup, thank you!

**Comment by jrsikors** [comment]
One other thing I would suggest -- when you open neo-gui .. don't 'load/open' your wallet file.  Let the first number stay at 0 ... just let the 2nd and 3rd numbers catch up.  

Once the 2nd and 3rd are caught up .. then open your wallet file.   It might help a little

**Comment by jrsikors** [comment]
**_Question: When you said "delete all the files", were you referring to the files in Chain folder or the entirety of NEO-Gui folder?_**

**_Question: If your answer to Question 3 is "delete the entirety", should I also wipe out all the version 2.0 and version 2.6, before re-downloading version 2.6?_**

Well I would answer both of these with 1 answer:
Since you don't really "install" anything, it's just 'unzipping'... you can have both versions on your computer.  I would recommend keeping your existing NEO2.0 and neo2.0 chain just in case.  I would just create a new directory for neo260 and that will create a new chain directory.

**Comment by jrsikors** [comment]
once your neo260 works fine .. then you can delete the old neo2.0 chain and zip (not your wallet :smile: ).

**Comment by soonliteh** [comment]
Just an FYI, I did everything you said and am currently waiting for the second and third numbers to sync before I open my wallet database. Currently, it's about 2/3 done, so it should be another few more hours before I open my wallet database.

I will keep the community posted again...

**Comment by jrsikors** [comment]
once you open your wallet database --- that (1st number out of the 3) will need to sync as well.. but it goes pretty quick.

**Comment by soonliteh** [comment]
Thanks for linking the issue #167. Actually, I read the post before opening this issue. 

As an update, the third number (xxx/xxx/xxx) has been stuck at 1,860,095 since yesterday night. The current block height is 1,891,081. Currently, only the second number has been increasing.

When the numbers appear to be "stuck", I had to close the GUI, and then re-opened it. Note that double-click doesn't work for me, so I had to right-click and run as an administrator. 

Any comment and help on **how to have the third number synced to the current block height?**

**Comment by jrsikors** [comment]
You sure you are on 2.6?

You might need to delete the whole chain folder and resync from 0/0/0. I believe that is the magic block # that people were getting stuck on with old versions.

-Jeff

**Comment by soonliteh** [comment]
Yup.
![image](https://user-images.githubusercontent.com/35473507/35788075-7ab0de32-09f8-11e8-8211-de12db2b916e.png)

Can you kindly verify the "magic block #" that people were getting stuck on? I would hate to delete the chain folder and re-sync. Who knows if it would get stuck at a different block height...

Also, I need access to my NEP-5 token by Feb 6, so I am running a little short on time.
If this is an endemic problem with NEO-Gui, I am disappointed with the NEO team, considering that they boast a myriad of dApps, and that this wallet is developed by their very own team.

**Comment by jrsikors** [comment]
1860095
see #170

**Comment by jrsikors** [comment]
also check out #167  ... @erikzhang posted a link to accelerate sync

**Comment by jrsikors** [comment]
Are you good to go now @soonliteh

**Comment by soonliteh** [comment]
Not really...

I no longer have problem with the third number (it seems to be synced to the current block height).
But, the second number is still in the 1.7 million and it has been two days since the re-installation.

So, I basically followed the steps you prescribed. I was able to do the offline block data sync (but the official guide is somewhat misleading). So, within the first 2 hours of re-installation with offline data sync, the second number was able to shoot up to 1.5 million. 

But you have read, it has been 2 days, and it's still at 1.7 million (second number).

**Comment by jrsikors** [comment]
Yeah I never had the chance to try the "accelerated" thing.   I remember it took me a couple days and a few re-starts (NEO-GUI.exe and another process started eating up 100% of CPU after a while).

Sorry -- I got no other fix for you :(

**Comment by soonliteh** [comment]
Everything is finally resolved! Here's a list of lessons learned, listed step-wise:

1. Backup wallet (.db3 and/or .json)
2. Delete all current NEO folders, only after wallet backup
3. Download the latest NEO-Gui
4. Download "Offline Synchronized Data"
5. Extract downloaded NEO-Gui into a folder in C:\ drive
6. Open the extracted NEO-Gui folder, and delete the "Chain" folder
7. Then, extract the downloaded "Offline Synchronized Data" into the NEO-Gui folder (root directory)
8. The "chain.acc" file is now in your NEO-Gui folder
9. Open "NEO-Gui.exe"
10. If it doesn't open, right-click and "Run as administrator"
11. At the bottom left corner, you can see three numbers: xxx/xxx/xxx
12. First allow the second and the third numbers to sync (the third number should sync quicker than the second)
13. Because of "Step 8", your GUI block height is quickly synced to the downloaded blockchain height
13. If the third number appears "stuck", close the Gui and re-open it
14. If the third number is still "stuck", repeat steps 2 through 13
15. Once the second and third numbers have reached the synced block height, open your wallet database
16. Browse to your backup wallet file (.json), and enter the same password as before
17. If your only backup wallet file is .db3, follow the prompt message to convert your wallet file into .json file, and then, follow step 16
18. Wait for the first number to sync (a blazing fast process)
19. Remember to thank jrsikors for his amazing help and patience! 👍 👍 👍 

Could you kindly guide me to how I could contribute to the current [NEO Client guide](http://docs.neo.org/en-us/node/gui.html)? I hope to be given an opportunity to write/edit an exhaustive guide, including frequently encountered problems and solutions. This, as a whole, would be a win-win for the NEO community.

**Comment by erikzhang** [comment]
To contribute to [docs.neo.org](http://docs.neo.org), you can make pull request to https://github.com/neo-project/docs.

**Comment by panzengott** [comment]
So after 4 long Days of downloading the new BS the Wallet rewards me.
error.log:

Neo.IO.Data.LevelDB.LevelDBException
Corruption: 24 missing files; e.g.: Chain/1239620.ldb
   bei Neo.IO.Data.LevelDB.NativeHelper.CheckError(IntPtr error)
   bei Neo.IO.Data.LevelDB.DB.Open(String name, Options options)
   bei Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   bei Neo.Program.Main()

So...do i have to do it again or is there a chance for salvation?
And when i have to do so...could this happen again?
And why this happened? Why are files missing?

**Comment by jrsikors** [comment]
If it lists the 24 files -- you could try unzipping specifically those files from the http://static.neo.org/client/chain.acc.zip

(if they exist in there)

**Comment by panzengott** [comment]
I dwnld this at the moment...but its freaking slow. About 23h...it says.

**Comment by jrsikors** [comment]
ah never mind -- the chain.acc.zip doesn't have individual files, just a chain.acc file.  to be honest I haven't even tested / played around with that method.  I finally got mine sync'd after a few days and haven't wanted to touch it and go through that again :blush:

**Comment by jrsikors** [comment]
But bottom line is -- you cannot 'trick' NEO-GUI and other crypto wallets.  If it doesn't like your Chain or datadirectory -- there's nothing you can do.

I personally haven't seen anyone post that error before about missing files -- that's pretty odd.  

I would think it might even an issue with your hard drive, and your hard drive is on the fritz and didn't download the blocks, or it downloaded them but they were corrupt.

**Comment by panzengott** [comment]
The Wallet was working and i was able to transfer my RPX and 1 NEO to my new NEON Wallet. And then when it was fully synced it stopped working. And did´nt wont open anymore and produced this log.

**Comment by WyattMufson** [comment]
Same issue with the missing files. Seems like the neo-gui is super buggy. It's happened to me numerous times and deleting the Chain folder (which isn't a solution in of itself, it's a bad work around at most) didn't help. It shouldn't take me more than a few hours to get the wallet to work, let alone 5 days.
