### ISSUE TITLE
Can't open wallet file

### ISSUE THREAD

**Issue by kostepanych** [neo-project/neo-gui#179]
I downloaded Neo GUI v2.6.0 and can't open wallet file created by Neo GUI v2.3.2.

Get this error: http://take.ms/elydc

Also strange thing: my wallet has *.dat extension but GUI expect *.json extension.

Still can open this file by v2.3.2.

**Comment by jrsikors** [comment]
Check out #118 

To solve this, please install vs2010 redist x86 and x64:
https://www.microsoft.com/de-de/download/details.aspx?id=14632
https://www.microsoft.com/de-de/download/details.aspx?id=5555

**Comment by kostepanych** [comment]
that doesn't helped...

**Comment by jrsikors** [comment]
Do you still have a backup of the old .db3 file .. before you tried to convert it to json ?  
Do you have the private key(s) for the addresses?

Please hit "details" on the error and post all the information in the error message here... when you get the "Unhandled exception has occurred"

Make sure you have .net framework 4.7.1 installed per their website

https://neo.org/download

NEO-GUI2.6.0
- NEO Project developed PC client 
- Clients with complete blockchain data
- Full-featured client
- Offline synchronized data(Main Net)/Test Net
- Instructions for use
**_- Need to install .NetFramework 4.7.1_**
- Support NEP-5, NEP-6

**Comment by kostepanych** [comment]
Yes, I have private keys and .net framework 4.7.1 installed.
Here is the detailed message:
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: One of the identified items was in an invalid format.
   at Neo.IO.Json.JObject.Parse(TextReader reader)
   at Neo.Implementations.Wallets.NEP6.NEP6Wallet..ctor(String path, String name)
   at Neo.UI.MainForm.打开钱包数据库OToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
neo-gui
    Assembly Version: 2.6.6596.21976
    Win32 Version: 2.6.6596.21976
    CodeBase: file:///D:/wal/NEO-GUI/neo-gui.exe
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Neo
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///D:/wal/NEO-GUI/Neo.DLL
----------------------------------------
Neo.VM
    Assembly Version: 2.0.4.0
    Win32 Version: 2.0.4.0
    CodeBase: file:///D:/wal/NEO-GUI/Neo.VM.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.Configuration.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.Configuration.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.Configuration.Json.DLL
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.FileProviders.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.Configuration.FileExtensions.DLL
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.FileProviders.Physical.DLL
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.Primitives.DLL
----------------------------------------
Microsoft.Extensions.FileSystemGlobbing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.FileSystemGlobbing.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.1.20720
    CodeBase: file:///D:/wal/NEO-GUI/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.25908.02
    CodeBase: file:///D:/wal/NEO-GUI/System.IO.Compression.DLL
----------------------------------------
Microsoft.AspNetCore.Http.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.AspNetCore.Http.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.AspNetCore.Hosting.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.AspNetCore.Hosting.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.DependencyInjection.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.DLL
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.Configuration.EnvironmentVariables.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.DLL
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.DependencyInjection.DLL
----------------------------------------
System.Net.Sockets
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.25908.02
    CodeBase: file:///D:/wal/NEO-GUI/System.Net.Sockets.DLL
----------------------------------------
Microsoft.AspNetCore.Http.Features
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.AspNetCore.Http.Features.DLL
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 4.0.2.1
    Win32 Version: 4.6.25519.03
    CodeBase: file:///D:/wal/NEO-GUI/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
Microsoft.AspNetCore.Http
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.AspNetCore.Http.DLL
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.Options.DLL
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.Logging.DLL
----------------------------------------
Microsoft.Extensions.ObjectPool
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.ObjectPool.DLL
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Core
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.Core.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting.Server.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.AspNetCore.Hosting.Server.Abstractions.DLL
----------------------------------------
Microsoft.Net.Http.Headers
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Net.Http.Headers.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.3.0
    Win32 Version: 
    CodeBase: file:///D:/wal/NEO-GUI/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///D:/wal/NEO-GUI/System.Runtime.DLL
----------------------------------------
Microsoft.AspNetCore.WebSockets
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.AspNetCore.WebSockets.DLL
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///D:/wal/NEO-GUI/Microsoft.Extensions.Hosting.Abstractions.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`

**Comment by kostepanych** [comment]
I renamed *.dat file to *.db3 and opened it as SQLite wallet. It converted to json format and opened without errors.

**Comment by jrsikors** [comment]
good to hear -- whatever works !  @erikzhang sounds like you can close this one out

**Comment by balintus03** [comment]
@jrsikors I have very similar problem that I have my .db3 file and I can't open it with the new NEON wallet and the NEO-Gui doesn't work either. What is the best way if you have the .db3 file and you want to convert into a .json file? Thanks for your help!
