### ISSUE TITLE
Update the Change Mechanism

### ISSUE THREAD

**Issue by PeterLinX** [neo-project/neo-gui#18]
### Abstract

The current change mechanism of Neo wallet (PC client) is rather simple. It sometimes might not lead to good user experience as some users with complex demands may feel dissatisfied. If users do not understand the change mechanism very well, wrong operations including deleting account might be performed. Therefore, an improvement plan with security, privacy and user experience can possibly be adopted. 

### Motivation

The current payment process is like this: Neo wallet(PC client) will calculate the optimal input addresses and the corresponding amounts to make up the total sum of the coins that user need to transfer. The transaction will be constructed from the full sum of coins from  each of the addresses being used for the transfer. After deducting the desired amount (which I input to transfer) to be sent from the full sum of coins, the remainder will be given back to me as change. By default Neo wallet will choose the FIRST standard account to be the default account to accept the change coins.

However, if people have no idea of this process, some incorrect operations might be performed. In order to solve this problem, we need to improve the user experience of Neo wallet(PC client). 

### Design Principles

Suggestions：

- Global change address can be set in the menu. 

- Please consider the situation when the global change address is deleted. For example, if global change account is deleted a new change account needs to be set.

- Users should be able to see the change address when transferring. 

- During the process of transferring, the change should be sent back to the global change address by default and users should be noticed. 

- Besides the global change account, user can also choose other accounts to accept the change. If the account is not standard, user should be warned.

### Appendix

The selection logic of the change address is shown as below: 

```c#
public virtual UInt160 GetChangeAddress()
{
	lock (contracts)
    {
    	return contracts.Values.FirstOrDefault(p => p.IsStandard)?.ScriptHash ?? contracts.Keys.FirstOrDefault();
    } 
}
```

The payment strategy is shown as below：

```c#
public T MakeTransaction<T>(T tx, UInt160 change_address = null, Fixed8 fee = default(Fixed8)) where T : Transaction
{
    if (tx.Outputs == null) tx.Outputs = new TransactionOutput[0];
    if (tx.Attributes == null) tx.Attributes = new TransactionAttribute[0];
    fee += tx.SystemFee;
    var pay_total = (typeof(T) == typeof(IssueTransaction) ? new TransactionOutput[0] : tx.Outputs).GroupBy(p => p.AssetId, (k, g) => new
    {
        AssetId = k,
        Value = g.Sum(p => p.Value)
    }).ToDictionary(p => p.AssetId);
    if (fee > Fixed8.Zero)
    {
        if (pay_total.ContainsKey(Blockchain.SystemCoin.Hash))
        {
            pay_total[Blockchain.SystemCoin.Hash] = new
            {
                AssetId = Blockchain.SystemCoin.Hash,
                Value = pay_total[Blockchain.SystemCoin.Hash].Value + fee
            };
        }
        else
        {
            pay_total.Add(Blockchain.SystemCoin.Hash, new
            {
                AssetId = Blockchain.SystemCoin.Hash,
                Value = fee
            });
        }
    }
    var pay_coins = pay_total.Select(p => new
    {
        AssetId = p.Key,
        Unspents = FindUnspentCoins(p.Key, p.Value.Value)
    }).ToDictionary(p => p.AssetId);
    if (pay_coins.Any(p => p.Value.Unspents == null)) return null;
    var input_sum = pay_coins.Values.ToDictionary(p => p.AssetId, p => new
    {
        AssetId = p.AssetId,
        Value = p.Unspents.Sum(q => q.Output.Value)
    });
    if (change_address == null) change_address = GetChangeAddress();
    List<TransactionOutput> outputs_new = new List<TransactionOutput>(tx.Outputs);
    foreach (UInt256 asset_id in input_sum.Keys)
    {
        if (input_sum[asset_id].Value > pay_total[asset_id].Value)
        {
            outputs_new.Add(new TransactionOutput
            {
                AssetId = asset_id,
                Value = input_sum[asset_id].Value - pay_total[asset_id].Value,
                ScriptHash = change_address
            });
        }
    }
    tx.Inputs = pay_coins.Values.SelectMany(p => p.Unspents).Select(p => p.Reference).ToArray();
    tx.Outputs = outputs_new.ToArray();
    return tx;
}
```

**Comment by lerider** [comment]
Is there a special use case where we need to accept from multiple addresses in one wallet?

Seems more intuitive and easier to implement to require the sum to be in same address? User then just need transfer between his own addresses before the transaction. The change is paid back to the address it was paid from.

I may be missing an important use case here?
