### ISSUE TITLE
Neu-Gui Password Incorrect, No private key :((

### ISSUE THREAD

**Issue by ursusarctus** [neo-project/neo-gui#180]
Hi!
I installed neo-gui wallet for rpx sale and I have logged in to my neo gui wallet 3 times in 3 separate days successfully and after a week or so it gave me wrong password error. I use variations of my passwords for local wallets and tried almost any combination and still cannot login to my wallet. I have db3 file and I have neo version 2.6474.32109. I know it sounds idiotic but I did not copied my private key.  I copied db3 file to 3 other computers and tried to login but same problem. I checked with my public address and my funds are still there. Is there a way to reach my wallet with db3 file or any other file located in my setup directory.

Please help, 

cheers

**Comment by jrsikors** [comment]
Try downloading an older version of NEO-GUI, like 2.2 from https://github.com/neo-project/neo-gui/releases

create a new folder on your c:\ like C:\neo220\ ... unzip it to that ... run neo-gui, and try to load your db3 into that.  You don't need to wait for sync... first mission is to get the wallet file loaded so you can get private key.

**Comment by jrsikors** [comment]
and it would also be worth a shot to try a different / backup version of the db3.  Hopefully you made backups of the .db3 !

**Comment by ursusarctus** [comment]
thank you for the quick reply, it still says password incorrect. should it work without chain sync?

**Comment by ursusarctus** [comment]
actually I am working on the backups of the db3, I am scared to mess with the original one

**Comment by jrsikors** [comment]
it should work without chain sync for sure.  

I would try to download all the versions of NEO from https://github.com/neo-project/neo-gui/releases

make like 8 different folders, one for each version ... try them all with different copies of the db3.

Sounds like your password is wrong .. maybe you changed it and forgot .. and/or the db3 got corrupted.  But if you did the right thing and saved original copies of the db3 onto different jump drives / hard drives, I would think one combo would work.  Sorry , maybe someone else has some other ideas :(

**Comment by ursusarctus** [comment]
thanks for the info, is there a way to brute force password from a txt file, I am pretty sure about 6 digits of my password out of 9.
