### ISSUE TITLE
Neo GUI v2.6.0   创建钱包数据库出错

### ISSUE THREAD

**Issue by AlleniCode** [neo-project/neo-gui#181]
************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

![d55771ef3775bb4e6586c20c3b1ac473](https://user-images.githubusercontent.com/8855341/35838673-6f0df0f8-0b27-11e8-9a6f-5afd0d1a1e8a.jpg)

**Comment by erikzhang** [comment]
Duplicate of #118
