### ISSUE TITLE
there is prune mode?

### ISSUE THREAD

**Issue by superbmilkyway** [neo-project/neo-gui#182]
I have laptop and it has only 128GB SSD.
Bitcoin core has prune mode and it is really helpful for small disk.

neo-gui has a kind of prune mode?
if not, it is possible to develop a kind of prune mode?

**Comment by Ashuaidehao** [comment]
Hi @lock9, do we have plans with this issue in NEO3?

**Comment by lock9** [comment]
Hello,
@superbmilkyway what exactly do you want to do with this prune mode?
If you have disk space restrictions, consider using a light wallet like Neon or O3.
