### ISSUE TITLE
win10运行错误

### ISSUE THREAD

**Issue by shaohao2014** [neo-project/neo-gui#185]
提示安装.net framework 4.7，win10上装不上，结果安装了4.6版本的，依然提示错误，求解决方法，谢谢！

**Comment by jrsikors** [comment]
https://neo.org/download

"Need to install .NetFramework 4.7.1"
->
https://www.microsoft.com/net/download/dotnet-framework-runtime

**Comment by jrsikors** [comment]
Still having issues?  Someone who speaks Chinese might need to take this please :smile:

**Comment by neotokens** [comment]
你必须要安装.NetFramework 4.7.1  有的操作系统需要先打补丁才能安装
