### ISSUE TITLE
My Neo was disappear..

### ISSUE THREAD

**Issue by yolael** [neo-project/neo-gui#188]
Hi, everyone..  help me anybody.

I login website "www.neotracker.io" to confirm my bounty of zpt coin.
When I login, I used privite key, and push "create keystore" button.
when I set my password of keystore, suddenly web site was changed to "www.neotracker.online" and then my neo was disapper....

![image](https://user-images.githubusercontent.com/36373839/36075091-e33b3b5c-0f8c-11e8-88fe-89cb08dd855f.png)

what can i do.... help me...

I naver login "neotracker.online"... Suddenly changed web site address...

**Comment by jrsikors** [comment]
I think your NEO is stolen unfortunately.  You must have clicked on the wrong/fake/phished link.

https://www.reddit.com/r/NEO_Coin/comments/7u1byi/15_neo_stolen_please_read/

https://bitcointalk.org/index.php?topic=2850494.0

I don't know if neotracker.io is compromised and hacked .. but neotracker.online is definitely the fake site used to steal people's funds. 

You really should have used a wallet like NEO-GUI or NEON for this reason :(

Sorry maybe someone else has some other ideas

**Comment by jrsikors** [comment]
You don't seem like you are the only one ... this address that you sent to looks like it's busy with lots of transactions (probably theft)

https://neotracker.io/address/AcQZuoHPUCRvdLogJLA3WtGoHBGaM1NzgP

**Comment by yolael** [comment]
thanks for reply!

I assuranced use website " www.neotracker.io"
But, suddenly changed "neotracker.online" when I pushed "open wallet -> privite key" ...

Do you know how to contact admin ~ ?

**Comment by jrsikors** [comment]
if you go to neotracker.io , in the bottom right of the page they list their twitter and facebook.

**Comment by jrsikors** [comment]
I did a search on twitter for "neotracker.io" and went to the "latest" ... lots of people reporting same issue as you :disappointed:  .  Sorry bud ... just remember that it's only money at the end of the day.  I know it hurts, I've lost plenty of it gambling / investing so I know the feeling way too well, but it's not the end of the world !  

There really are terrible people on this planet.

**Comment by jrsikors** [comment]
And I know you are desperate looking for help, so I don't mind trying to help, but it needs to be said for anyone else coming to this github as well looking for help ... **_that neotracker.io is not built/operated by the NEO team_**.  

I don't want people coming here thinking that the NEO team is even remotely at fault for this.  There is 0% 'blame' for the real NEO team on this.

I'm not affiliated with the NEO team or any website/app.  My opinions/thoughts are my own.

**Comment by yolael** [comment]
Oh.. I see... that's horrible on me... 
But, thanks you for help and answer me.

Thanks~ Have a nice day.

**Comment by cosmic-springs** [comment]
Hi.
I have now lost 9 NEO and around 2000 DBC. They disappeared from my wallet and the NEO are showing in my transaction history (-9). However, no transaction was made by me?? It’s everything i had :(

Hash: 49774c05a3c7a7d9e90912f168e834077988f58f806441469f04bca0ffa3021c
Time: 07/02/2018, 17:17:19
Wallet: AU6GkGRt4jeESJnM56mz9uJiwacNMTHjzH

Have I been hacked?
Is this just part of the mysterious disappearing and often reappearing of NEO from various wallets and ledgers (I lost one around a month ago but reappeared a week later)?
Is there any place ‘safe’ to store NEO?
Any assistance/advice/HELP! Would be greatly appreciated.

**Comment by jrsikors** [comment]
NEO-GUI and NEO-CLI from neo.org are the only 2 wallets that were built by the NEO team... and they are 'safe'.  NEON isn't developed by NEO team, but is also pretty safe.

3rd party wallets are always the ones that get hacked and people lose funds... especially web based ones like neotracker.io.

Even NEON is a 3rd party wallet, but I would put it in that 99.99% safe.

So -- unfortunately you did get hacked and your funds were stolen if you were using neotracker.io :( 

as mentioned earlier though -- neotracker.io is not 'supported' or owned by the NEO team, so contacting them about this won't be helpful.  You will need to try to contact neotracker.io to figure out what happened... lots of people got their funds stolen :(
