### ISSUE TITLE
Neo-gui, not visible NEP-5 balance

### ISSUE THREAD

**Issue by Ron8111** [neo-project/neo-gui#191]
Hello everyone, I had similar issue # 145 (I was unable to open my Neo-gui application with Nep-5 tokens, I follow steps # 145, however, my Nep-5 tokens balance and transaction related to the rooms are not visible, I see my full neo-gui neuro.book 2.3.5 is fully synchronized, What should I do?

Ps: I have windows 10 x64, there is visible NEO balance before Nep-5 tokens sale, according to neotracker.io I do not have any Neo there only Nep-5.

**Comment by jrsikors** [comment]
what is your wallet address?

**Comment by jrsikors** [comment]
And please clarify your issue -- I can't tell if you:
  A)  Can't open NEO-GUI
  B)  Your NEO from your address are gone

**Comment by jrsikors** [comment]
And NEO 2.3.5 won't work anymore .. you need to download the latest:
https://github.com/neo-project/neo-gui/releases

http://docs.neo.org/en-us/node/gui.html
http://static.neo.org/client/chain.acc.zip


Check out this for other tips on re-syncing:
https://github.com/neo-project/neo-gui/issues/178

**Comment by Ron8111** [comment]
Ok, anyway how to convert db3 file to json, it will change automatically when I attach to open database button?

**Comment by jrsikors** [comment]
make sure you backup your db3 file in multiple places before you do this, just in case.

Yes -- once you open NEO-GUI in 2.6 , and try to open the wallet file, it will auto-convert for you.

As long as you keep a backup of the db3 file, if something goes wrong (it shouldn't, very small chance), we can always figure out a way to recover your private keys from the db3 and then just import into NEO-GUI.

**Comment by Ron8111** [comment]
Thanks for the help @jrsikors , I will make an update here.

**Comment by jrsikors** [comment]
hows the progress?

**Comment by jrsikors** [comment]
@Ron8111 any updates?

@erikzhang you can probably close this.

**Comment by Ron8111** [comment]
Hi Guys, sorry for a really late response. Ok, I followed the steps - downloaded the newest wallet, transfer db3 file to json and fully synch the blockchain. However, nep-5 token balance is not still visible in the wallet interface. 
![nep-5](https://user-images.githubusercontent.com/36578170/38072356-2718b55e-3326-11e8-8b17-e4b539d31489.png)

**Comment by jrsikors** [comment]
this is for adding ONT ..  stolen from:
https://www.reddit.com/r/NEO/comments/82wcpt/ont_script_hash_for_neogui/


Advanced
Options
Add ONT Scripthash: ceab719b8baa2310f232ee0d277c061704541cfb
Apply/Ok
Wallet Sync
You should now see your ONT Tokens

**Comment by jrsikors** [comment]
you wont see the tokens on that screenshot screen though --  they won't show up on the same screen as your NEO and GAS .. it's whatever that middle tab is (Not at my computer with my wallet so I can't remember :smile: )

**Comment by jrsikors** [comment]
the "Asset" tab is where they will show

**Comment by Ron8111** [comment]
Hi Jeff, it is RPX tokens which scripthash should I add?
probably that one 0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9

https://www.reddit.com/r/RedPulseToken/comments/75l4i2/lost_script_hash/

**Comment by jrsikors** [comment]
yeah i was going to post same thing -- that's all i would do .. google it.  I dont have any master spreadsheet or anything, or know where to 'officially' find it other than RedPulses documentation

I would vote go with the reddit thread's suggestion

**Comment by Ron8111** [comment]
Thanks, it was pretty damm easy. Sorry for the inconvenience

**Comment by jrsikors** [comment]
no inconvenience man !  Happy to help !

**Comment by CrypJohn** [comment]
for some reason my wallet won't convert to json and im resyncing 2.5.2. Does this still work if I want to transfer my NEO?

**Comment by jrsikors** [comment]
Depends on what you really want to do:
  If you load up your wallet in 2.5.2 you should be able to export your private key(s) , you don't need to be sync'd for that.

From there you could:
  A)  Upgrade NEO-GUI to 2.6  and create a new wallet, import private keys
  B)  load private key to another wallet like NEON wallet

It's always advised not to "send" while you aren't fully sync'd.
