### ISSUE TITLE
Blocks are not updating

### ISSUE THREAD

**Issue by the-louse** [neo-project/neo-gui#192]
Hello,

My block Height has been stuck at 1860095/1860095 for quite sometime. Is there anything I can do to get the blocks to start updating again? I am unsure what I can do to claim my Gas as the blocks are not updating.

Thank you

**Comment by jrsikors** [comment]
you need to upgrade to the latest NEO version
https://github.com/neo-project/neo-gui/releases

Only 2.6.0 will sync past that block

Check also #178 for sync help

**Comment by jrsikors** [comment]
How's the progress on this going?

**Comment by the-louse** [comment]
Great. Thanks for the help! Trying to get all set for the ONT drop. Appreciate it!

**Comment by jrsikors** [comment]
No prob -- you can close this issue out if you are done and good please !
