### ISSUE TITLE
Neo-gui has stopped working, v2.6

### ISSUE THREAD

**Issue by bokacw** [neo-project/neo-gui#193]
Hi,

I have downloaded new neo-gui 2.6 three days ago, extracted it into a new folder, started it as admin, left it syncing since then and now it's crashing. I can't stress enough how frustrating this is. Could someone please help me? 
![neo-gui-26](https://user-images.githubusercontent.com/36687984/36464383-8ed08ece-169d-11e8-939b-0d4d4aa734b7.png)

**Comment by jrsikors** [comment]
does it crash immediately or when you click on something (like open your wallet file)?

Can you click on Debug?  Can you post info if it shows any?

**Comment by jrsikors** [comment]
Also -- what Operating System are you on?  Win7? Win10?

**if it crashes IMMEDIATELY after you open it:** 
Unfortunately the only decent fix is to rename your "Chain" folder ... it's probably corrupt.   Close down NEO-GUI and rename Chain folder to like Chain-Old.  Save it just in case it ends up not being a fix, you can rename it back to Chain later.

To help speed up the sync follow these steps (found on http://docs.neo.org/en-us/node/gui.html)
Step 1) download the http://static.neo.org/client/chain.acc.zip
Step 2) dont unzip the chain.acc.zip , just copy it to whatever folder your neo-gui.exe exists
Step 3) run neo-gui.exe

**if it crashes after you do click something (like try to open wallet, etc)**
Please click debug and try to post any screenshot/logs/info you get.  The screenshot you posted isn't enough to help troubleshoot

**Comment by bokacw** [comment]
Hi,

it was crashing immediately after I opened it. It's Win 10 and clicking on the Debug button didn't show anything. 
I did what you suggested. It's working for now, but the second number has not yet reached the number when it started crashing, it's still on 17xxxxx. 
I'll let you know when it, hopefully, syncs completely or starts crashing again.

Thanks!

**Comment by bokacw** [comment]
Hi,
it has finally synced. It's working ok now.
First time I downloaded the chain.acc.zip file and I extracted it to the Chain folder. I guess that was the mistake I made.

**Comment by jrsikors** [comment]
yeah it seems odd that you wouldn't unzip it, i made the mistake too ! 

If you are good to go now you can close the issue.

cheers !
