### ISSUE TITLE
Neo GUI does not open

### ISSUE THREAD

**Issue by maciogit** [neo-project/neo-gui#194]
Some time ago I have downloaded NEO GUI. It even succesfully synchronized once but after that particular moment I did not open it. Few days ago I opened it therefore I have to resynchronize it from 12xxxxxxxx to 19xxxxxxxx. It went up to something like 18xxxxxxxx. After that I have some problems and it started crashing as in #193. 

Currently I am not even able to open it. Nothing happens. I tried to open it as an admin. Do not work. Can I do anything in order to open it or reinstall and restore blocks that have been synchronized recently? It really took a loooooong time to synchronize this stuff. I do not have any funds on that wallet however I would love to use it on regular basis.  Hope you can help me. I am not very technical nonetheless I decided to ask fully fledged proffesionalls.

**Comment by jrsikors** [comment]
Are you sure your are on the latest NEO?

https://github.com/neo-project/neo-gui/releases/tag/v2.6.0

**Comment by jrsikors** [comment]
Also -- you might want to try to temporarily disable (like 5-10 minutes) anti virus to see if your Anti Virus is preventing it from running.

**Comment by maciogit** [comment]
Thank you for your answer jrsikors. Really appreciate it.

It was some time ago I downloaded this wallet. As I can see in the properties it is of 2.06411.26926 ver. It was running smoothly thus I clearly do not consider update. Is there a possibility to download latest version you have presented without synchronization from afresh? If so, could you provide me with details? Should I copy chain data in somewhere? Thank you and have a good day :)
Oh and I forgot to mention I had tried to disable antivirus beforehand.

**Comment by jrsikors** [comment]
you HAVE to use the latest version 2.6 NEO-GUI , older NEOs will not work and sync anymore past a certain block

http://docs.neo.org/en-us/node/gui.html

follow instructions, and also use #178 for other helpful tips on resyncing.

**Comment by maciogit** [comment]
Ok, thank you for info. I do not want to bother you but I would like to reassure I understood everything properly so as not to mess this up. 
To cut a long story short I should download 2.6 NEO-GUI, then chain.acc.zip posted in #167 by erikzhang and copy it to NEO-gui main folder? Am I right? There are too many information from #178 #167 and instructions bombing me same time ;)

**Comment by jrsikors** [comment]
No problem !

So yeah basically:
step 1) download 2.6 neo gui.zip
step 2)  Unzip neo-gui to wherever you want, like C:\NEO-GUI26  .. DONT RUN IT
Step 3) download the http://static.neo.org/client/chain.acc.zip  
step 4)  dont unzip the chain.acc.zip , just copy it to wherever you put NEO2.6 from step 2
Step 5)  run neo-gui.exe
step 6)  Go to sleep and check in the morning :smile:

**Comment by jrsikors** [comment]
Also -- make sure you have multiple backup copies of your db3 file... you will be asked to convert it to json

To help speed sync and avoid complications -- I would advise NOT opening your wallet until the Client is fully sync'd.

Keep an eye on your CPU / Memory usage ... if NEO-GUI starts eating up 100% of your CPU and/or RAM, I would just close NEO-GUI, wait 5 secs, and re-open it and let it continue to sync.

It does take a while to sync, and hopefully the Devs find a way to speed it up.. but for now it just takes time

**Comment by maciogit** [comment]
Yeah, I had observed this GPU-strange behaviour before.

It looks like chain.acc doesnt like me. I can not download this file - transfer failed. May be the file corrupted or do I simply have bad luck? Is there any other link to download?

edit Apparently I still cant download this file. Quite weird taking into account fact there is no problem with downloading other files. I am afraid I will be obliged to synchronize from start damn.

**Comment by jrsikors** [comment]
Yeah sorry man ..  I went through the 0/0/0 sync .. it's brutal but you'll get through.  Just check your task manager every few hours / whenever possible ... if it's at 100% CPU usage, I would suggest closing NEO down and re-opening.

**Comment by jrsikors** [comment]
hows the progress?

**Comment by jrsikors** [comment]
beep beep :smile:

**Comment by jrsikors** [comment]
@erikzhang  would close this
