### ISSUE TITLE
Didnt receive my 2 neo yet

### ISSUE THREAD

**Issue by pkruyt75** [neo-project/neo-gui#195]
![screenshot 2018-02-21 at 16 34 07](https://user-images.githubusercontent.com/36704343/36488960-11acd834-1725-11e8-8d1a-5d523c1eb0e8.png)
Dear Peter,

Few hours ago ive send 2 neo to a neo wallet but didnt received it yet...guess its taking too long.
Receive adress was AR8injsmu2RHpBqx6wwXpt93Ly4SNABjQN.
Since i am a complete newbie ...help!
made some screenshots to help.
![screenshot 2018-02-21 at 16 29 01](https://user-images.githubusercontent.com/36704343/36488825-b56f2374-1724-11e8-8285-ef3e187e1e4f.png)
![screenshot 2018-02-21 at 16 28 34](https://user-images.githubusercontent.com/36704343/36488828-b594a662-1724-11e8-89a2-c96d7baca96c.png)

Patrick Kruyt

**Comment by jrsikors** [comment]
Unfortunately this Github is for the NEO-GUI client ... you will need to take up your problems with the support people at neowallet.cn

However -- since you posted this -- I'm seeing NEO GAS claims on the address:
AR8injsmu2RHpBqx6wwXpt93Ly4SNABjQN

So I'm thinking you figured out your problem?

**Comment by jrsikors** [comment]
the github for the neowallet.cn looks like it's at:
https://github.com/PeterLinX/neowallet.cn

also on neowallet.cn ,, if you go to "about" , there is contact info for their team.

**Comment by pkruyt75** [comment]
Yes thanks i figured out the problem!

Greetings 

Patrick Kruyt 

Sent by Mailwise – Your emails, with style.:)
    

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [neo-project/neo-gui] Didnt receive my 2 neo yet (#195)
Van: Jeff S <notifications@github.com>
Aan: neo-project/neo-gui <neo-gui@noreply.github.com>
Cc: pkruyt75 <pkruyt75@gmail.com>,Author <author@noreply.github.com>
