### ISSUE TITLE
NEO GUI Synching issue 

### ISSUE THREAD

**Issue by g4usat** [neo-project/neo-gui#197]
Hello, 
My NEO GUI wallet is been synching for more than 3 weeks and it's still going on. As of now the height is still 1677837/1677837/1959658. This is really frustrating and annoying. It's eating up my laptop processing heavily and am unable to do other tasks efficiently. I can't take this anymore and would like to transfer my NEO to NEON wallet. Can you pls help me in transferring my NEO coins from NEOGUI to NEON wallet. 
Appreciate your help..

Thank you!

**Comment by jrsikors** [comment]
Get your private key from your NEO wallet (right click on the address) -> view private key.

Go download / install NEON, and import the private key.

Done !

**Comment by g4usat** [comment]
Thanks Jeff for your quick reply. So, when I install NEON, don't I need to create a new wallet by which it'll generate new address and new private key for it? if I use my private key of NEOGUI, then everytime I login to NEON, I can open the wallet only by using the NEOGUI private key? it's bit confusing..I thought I need to create a new wallet in NEON and it'll generate it's own private key and I don't need to use private key to login everytime.  Appreciate if you can clarify further...Thanks again

**Comment by jrsikors** [comment]
I haven't played around with it much but I just double checked ... so this is what I would do:

Step 1)  Generate a new wallet address with NEON
Step 2)  write down the public address , private key, etc... backup your new NEON wallet
step 3)  log out of your new NEON wallet
step 4)  do the "log in with private key" .. and log in with the private key of your NEO-GUI
step 5)  send all your funds this account to the public address of your new NEON wallet from steps 1 and 2

now all your funds are in your NEON wallet

**Comment by jrsikors** [comment]
There actually might be an easier way -- but I can't really help troubleshoot.  These are more "NEON" questions that NEO-GUI questions.  

I would suggest reaching out to the NEON community.  It would involve steps I'm personally not comfortable in trying to explain (copying your .json wallet file from NEO-GUI over to the place where NEON looks for wallet files... but then you might need to edit the .json file a bit.

I think my previous post a way better / safer method (send funds from 1 wallet to another).  Good news is no transfer fees.

**Comment by g4usat** [comment]
Yeah, I can understand what you are saying. I think your previous post with 5 steps looks good to me. I'll try that..Thanks a lot!!

**Comment by jrsikors** [comment]
You could to go now?  you can close the issue if you are... Erik probably will anyways :grinning:

**Comment by g4usat** [comment]
Yep, I'm done transferring...It can be closed. Thanks!


Best Regards,
Srinivas Takuri

**Comment by jrsikors** [comment]
You should have the ability to close the issue yourself :smile: 

And good luck to you !
