### ISSUE TITLE
Unable to load libleveldb running GUI

### ISSUE THREAD

**Issue by barbellfan** [neo-project/neo-gui#20]
I pulled the latest version (f1f81400490d722800599d9112e0b8e91a2b7d30), loaded it into Visual Studio, built it, and ran it. However, the GUI does not run, and this error ends up in the error.log file:

System.DllNotFoundException
Unable to load DLL 'libleveldb': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Neo.Implementations.Blockchains.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main() in F:\GitHub\neo-gui\neo-gui\Program.cs:line 109

**Comment by johanwahlqvist** [comment]
Had the same problem. As a workaround I downloaded the binary release and found the DLL there.

**Comment by erikzhang** [comment]
You need to build https://github.com/neo-project/leveldb and copy libleveldb.dll to the working directory.

**Comment by nengine** [comment]
libleveldb.dll included in neo-client zip file is in working directory where i run dotnet neo-cli.dll but still getting the same error.

**Comment by erikzhang** [comment]
Did you use the correct version? x64 or x86?

**Comment by barbellfan** [comment]
Yes, I got it working. Thanks for the help!

-- 
Chris Allen

**Comment by nengine** [comment]
I downgraded .Net core SDK to 1.1.0 form 2.0.0 on Windows 2012 Server machine and works now.  Quite strange thought why it was giving errors on version 2.0.0.  Thanks.

**Comment by guanhui07** [comment]
i get the same error

**Comment by agchil** [comment]
I found the solution by placing the libleveldb in the corresponding folder (x86 and x64), at the height of the application.
