### ISSUE TITLE
NEO gone after claiming GAS (NEOtracker)

### ISSUE THREAD

**Issue by MaxShpax1** [neo-project/neo-gui#200]
I have claimed GAS a month ago and back then I had 2 NEO, and GUI showed me completing everything correctly, but afterwards GAS was on 0 and so was NEO. 
I have waited for a couple of days, but nothing happened. Tried contacting NEOtracker support on facebook, they weren't of any help as of now.
Today my GAS shows correct values, but my NEO shows 0 still.
In the transactions window it appears as if I sent my NEO to some different account, which I never did, BUT it also shows, that I claimed GAS 3 minutes LATER and I used all my NEO just like I normally did. Which is strange, because if I actually did get phished, then I would not be able to claim GAS.

**Comment by jrsikors** [comment]
whats your wallet address and/or the transaction ID?

If your funds went to:
https://neotracker.io/address/AcQZuoHPUCRvdLogJLA3WtGoHBGaM1NzgP

Then you got phished unfortunately .. see #188

**Comment by jrsikors** [comment]
any updates to my questions?  what is your wallet address and/or the transaction ID?

**Comment by jrsikors** [comment]
beep beep, anything?

**Comment by jrsikors** [comment]
@erikzhang you can probably close this -- no response from original poster
