### ISSUE TITLE
NEO GUI crashing!

### ISSUE THREAD

**Issue by RayMiner** [neo-project/neo-gui#201]
Hi!
I updated the wallet to the latest and greatest version, and have severe issues where I have been trying to figure this out since last week and have followed almost everything mentioned here on github.
![image](https://user-images.githubusercontent.com/2855499/36683387-5e61f468-1b15-11e8-92d0-6b52291a06ff.png)
I have downloaded the offline chain and have been trying to sync but then randomly the program crashes and I can't get in even with elevated priveledges. I am getting nervous now as I haven't seen my NEO for a while. Is there a workaround available or if this version can be improved?
Below is the log extract:
System.Runtime.InteropServices.SEHException
External component has thrown an exception.
   at Neo.IO.Data.LevelDB.Native.leveldb_open(IntPtr options, String name, IntPtr& error)
   at Neo.IO.Data.LevelDB.DB.Open(String name, Options options)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main()

Any help or pointers will be greatly appreciated. Please note I have tried the below:
1. Disabled AV
2. Re-installed 
3. Re-downloaded offline chain
4. Renamed the chain.acc and tried as well

**Comment by jrsikors** [comment]
Couple things:
  1)  I would rename the Chain folder to Chain_Old
  2)  Make sure the chain.acc.zip  ... THE ZIP .. don't unzip it ... is in the folder where NEO-GUI is... zipped !
  3)  re-open NEO-GUI

**Comment by RayMiner** [comment]
Thanks, what happens to my old folder? I will be again resyncing this whole thing?

**Comment by jrsikors** [comment]
probably will re-sync -- but there's not much you can do about that.  NEO-GUI needs to sync on its' own terms.  any corruption of the blocks/db means that NEO-GUI doesn't like it.

Hopefully the devs improve the syncing process in the next release... it doesn't seem to be working for many people.  Or at least allow a bootstrap download.

**Comment by jrsikors** [comment]
any updates?

**Comment by RayMiner** [comment]
Hi!
So yes had to redo from scratch, re-install the NEO gui , downloaded the offline chain and had lot of patience :) can see all my NEO and it's all good. 
Thank you for your assistance.
