### ISSUE TITLE
Unable to Create Custom Contract 

### ISSUE THREAD

**Issue by ch0624** [neo-project/neo-gui#202]
I was following instruction on http://docs.neo.org/zh-cn/sc/tutorial/Lock2.html

When I try to import custom contract,  this Unhandled Exception appears. 

I am using windows 10 and have generated the contract file using visual studio 2017.

Could someone help?

**Comment by jrsikors** [comment]
what unhandled exception?  Can you post details?

**Comment by ch0624** [comment]
Hi jrsikors, thanks for the help. Please see the screenshot below. 

This window pops up when I tried to create new contract.

![error window](https://user-images.githubusercontent.com/34905285/36824499-af0cde48-1cd0-11e8-889f-f3e09f0bffb3.JPG)

**Comment by jrsikors** [comment]
unfortunately I don't have a lot of knowledge with smartcontracts.  The key part of the error message is in the first couple lines:

"Value doesn't fall within the expected range"
"Neo.Wallets.Keypair..ctor(Byte[] privateKey"

So -- if I had to guess .. it doesn't seem to like something that has to do with the steps...
byte[] b = HexToBytes("0285eab65f4a0126e4b85b4e5d8b7e303aff7efb360d595f2e3189bb90487ad5aa");
byte[] bytes = System.IO.File.ReadAllBytes("Test.avm");

**Comment by jrsikors** [comment]
In this step in the code .. are you putting in the Public Address like this?
byte[] b = HexToBytes("0285eab65f4a0126e4b85b4e5d8b7e303aff7efb360d595f2e3189bb90487ad5aa");

Are your values in test.avm good?

**Comment by jrsikors** [comment]
Were you able to ever figure this one out?  Or still same problems and looking for help ?

**Comment by Relfos** [comment]
I've found a similar problem, happens when your AVM fiile is quite large and when you paste it into this window, part of it gets cut off
