### ISSUE TITLE
Failed to deploy a smart contract to NEO testnet blockchain

### ISSUE THREAD

**Issue by blockchain1977** [neo-project/neo-gui#203]
Hello,

After I created a smart contract and compiled it into avm file, I failed to deploy it using NEO-GUI. I didn't find a documentation about how to deploy a smart contract to blockchain using NEO-GUI. Could anyone help with it please? Thanks!

Following are what I did:

I used NEO-GUI and got testnet blocks synced. I have applied enough test NEO and NEO GAS.
I created a smart contract with below content if I load it in NEO-GUI:

60c56b6c766b00527ac4616168164e656f2e53746f726167652e476574436f6e7465787410616d6f756e745f646576656c6f706572617c680f4e656f2e53746f726167652e4765746c766b51527ac46168164e656f2e53746f726167652e476574436f6e7465787412616d6f756e745f6469737472696275746f72617c680f4e656f2e53746f726167652e4765746c766b52527ac46168164e656f2e53746f726167652e476574436f6e746578740f616d6f756e745f706c6174666f726d617c680f4e656f2e53746f726167652e4765746c766b53527ac46168164e656f2e52756e74696d652e47657454726967676572009c6c766b54527ac46c766b54c3644f026161654e046c766b55527ac4611404d86df4cb9331db3975d7dc5728b4503c8ba9866168184e656f2e52756e74696d652e436865636b5769746e6573736c766b56527ac46c766b56c3648f00616c766b55c36c766b52c3a0009c6c766b57527ac46c766b57c3646700616c766b52c36c766b55c3946c766b52527ac46168164e656f2e53746f726167652e476574436f6e7465787412616d6f756e745f6469737472696275746f726c766b52c3615272680f4e656f2e53746f726167652e50757461516c766b58527ac4620302006c766b58527ac462f801616168184e656f2e52756e74696d652e436865636b5769746e6573736c766b59527ac46c766b59c3648c00616c766b55c36c766b53c3a0009c6c766b5a527ac46c766b5ac3646400616c766b53c36c766b55c3946c766b53527ac46168164e656f2e53746f726167652e476574436f6e746578740f616d6f756e745f706c6174666f726d6c766b53c3615272680f4e656f2e53746f726167652e50757461516c766b58527ac4624f01006c766b58527ac4624401616168184e656f2e52756e74696d652e436865636b5769746e6573736c766b5b527ac46c766b5bc3648d00616c766b55c36c766b51c3a0009c6c766b5c527ac46c766b5cc3646500616c766b52c36c766b55c3946c766b51527ac46168164e656f2e53746f726167652e476574436f6e7465787410616d6f756e745f646576656c6f7065726c766b51c3615272680f4e656f2e53746f726167652e50757461516c766b58527ac4629a00006c766b58527ac4628f00006c766b58527ac46284006168164e656f2e52756e74696d652e47657454726967676572609c6c766b5d527ac46c766b5dc3644f00616c766b00c300c36c766b5e527ac46c766b5ec306627579617070876c766b5f527ac46c766b5fc3642300616c766b51c36c766b52c36c766b53c3615272653a006c766b58527ac4620f0061006c766b58527ac46203006c766b58c3616c756651c56b61516c766b00527ac46203006c766b00c3616c756658c56b6c766b00527ac46c766b51527ac46c766b52527ac461616530016c766b53527ac46c766b53c361950164966c766b54527ac46c766b53c361950164966c766b55527ac46c766b53c361950164966c766b56527ac46168164e656f2e53746f726167652e476574436f6e7465787410616d6f756e745f646576656c6f7065726c766b00c36c766b56c393615272680f4e656f2e53746f726167652e507574616168164e656f2e53746f726167652e476574436f6e7465787412616d6f756e745f6469737472696275746f726c766b51c36c766b55c393615272680f4e656f2e53746f726167652e507574616168164e656f2e53746f726167652e476574436f6e746578740f616d6f756e745f706c6174666f726d6c766b52c36c766b54c393615272680f4e656f2e53746f726167652e50757461516c766b57527ac46203006c766b57c3616c756651c56b61006c766b00527ac46203006c766b00c3616c756651c56b61006c766b00527ac46203006c766b00c3616c756657c56b6161682953797374656d2e457865637574696f6e456e67696e652e476574536372697074436f6e7461696e65726c766b00527ac46c766b00c361681d4e656f2e5472616e73616374696f6e2e4765745265666572656e6365736c766b51527ac4616c766b51c36c766b52527ac4006c766b53527ac4629e006c766b52c36c766b53c3c36c766b54527ac4616c766b54c36168154e656f2e4f75747075742e4765744173736574496461209b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc59c6c766b55527ac46c766b55c3642d006c766b54c36168184e656f2e4f75747075742e476574536372697074486173686c766b56527ac4622c00616c766b53c351936c766b53527ac46c766b53c36c766b52c3c09f6359ff006c766b56527ac46203006c766b56c3616c756651c56b6161682d53797374656d2e457865637574696f6e456e67696e652e476574457865637574696e67536372697074486173686c766b00527ac46203006c766b00c3616c7566

I tried to deploy it to NEO Test blockchain. I input name, version, etc. I loaded the avm file which generated above code. I checked need created storage and need dynamic call. Then, I click deploy. 
It lead me to another dialog with some content of customized code ( It looks like it's invoking a contract rather than deploy it ). I click button to try running it. It gave me some messages like below ones:

VM State: HALT, BREAK
Gas Consumed: 490
Evaluation Stack: [{"type":"InteropInterface"}]

Whatever, I click button to invoke it, it gave me the transaction number as : 0xaeff5231c4dda16f4371a12ec7bf2b7ac3667eaa9a4cd277aa5b3512d830f936. While, I cannot find such transaction from neo testnet after around 20 mintues (more than 70 confirms of blocks).
https://testnet.neotracker.io/tx/aeff5231c4dda16f4371a12ec7bf2b7ac3667eaa9a4cd277aa5b3512d830f936. I got message that : Sorry, that page was not found.
And my test neo gas got deducted by 490. 

Did I do anything wrong? What should I do to deploy a smart contract please? Thanks!

BTW: I did above operation from testnet address: AGDVd3yUb6Nywo8pKb3gdh1y6jWHBkenjr.

**Comment by jrsikors** [comment]
steps here not helpful?

http://docs.neo.org/en-us/sc/tutorial/Lock2.html

**Comment by blockchain1977** [comment]
@jrsikors This is the way of deploying a local contract rather than deploying an application contract to blockchain.
I did found a link of doc of deploying contract to blockchain following your link:
http://docs.neo.org/en-us/sc/tutorial/deploy-invoke.html
While, I think I used the same steps as documented, but met the problem I mentioned in this issue.
Thanks!

**Comment by jrsikors** [comment]
Sorry I'm out of my element for deploying contracts.  Took a shot in the dark for ya.  Hopefully someone else who has knowledge of that topic swoops in.  Good luck & sorry !

**Comment by blockchain1977** [comment]
@jrsikors Thank you anyway! :-)
