### ISSUE TITLE
Corruption: 36 missing files

### ISSUE THREAD

**Issue by WyattMufson** [neo-project/neo-gui#204]
I am trying to sync with the blockchain but keep getting a corruption error. I've tried deleting the blockchain and resyncing and it keeps happening. I only had about 20k blocks left to go when it crashed. I can't even open neo-gui. The error.log keeps updating with the LevelDBException.

Why is there no easy way to set up the wallet? I downloaded the chain.acc.zip which doesn't seem to be updated regularly either so it takes like 2 days and then crashes with no way to fix.

**Comment by jrsikors** [comment]
Yeah it's pretty rough right now -- hopefully the NEO Devs have noticed all the problems/complaints here over the past month are working up something for the next release.

The 2.6 release really made the situation weird.  You used to be able to just download a bootstrap and unzip the files... now they went to this chain.acc.zip which is wonky.

And it doesn't help that 2.6 FORCED everyone to start from 0/0/0.

If @erikzhang and the NEO devs are listening .. I would strongly advise that for the next NEO-GUI release, have some thorough testing done on a new/different computer... and go it through the process like normal people would ! :smile:

**Comment by xstrm1** [comment]
I'm having the same problem. I had to wait 2 days for a full sync with Neo GUI 2.6.0. Once it completed, I sent one transaction and closed the app. I haven't been able to open any more

Error.log

### Neo.IO.Data.LevelDB.LevelDBException
Corruption: 21 missing files; e.g.: Chain/933358.ldb
   at Neo.IO.Data.LevelDB.NativeHelper.CheckError(IntPtr error)
   at Neo.IO.Data.LevelDB.DB.Open(String name, Options options)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main()

**Comment by jrsikors** [comment]
try this out:
https://www.reddit.com/r/NEO/comments/83j7dl/is_your_neo_node_stuck_at_2000190/

**Comment by WyattMufson** [comment]
Yeah it looks like CoZ updated the Chain they have on their Github (https://github.com/CityOfZion/awesome-neo). Looks like the solution is oddly to remove everything and try again.

**Comment by jrsikors** [comment]
well it looks like there is a link to where you can download an "almost complete" blockchain bootstrap, where you can actually unzip the files into the chain folder (delete everything first yeah).

I don't know what's going on with the chain.acc.zip , some people have success , some don't.

I personally would rather just see a bootstrap that i can download and unzip all the blocks into the Chain folder ... seems much cleaner to me.

**Comment by jrsikors** [comment]
So are you good to go now ?  Or still fighting it?

**Comment by xstrm1** [comment]
Thanks, I'll give it a try


Dne st 14. 3. 2018 20:32 uživatel Martin Strnad <xstrm1@gmail.com> napsal:

**Comment by xstrm1** [comment]
Thanks, I'll give it a try


Dne st 14. 3. 2018 20:20 uživatel Jeff S <notifications@github.com> napsal:

**Comment by jrsikors** [comment]
I finally got around to testing this out and here's what I did:
Step 1)  Deleted chain folder
Step 2)  Deleted peers.dat
Step 3)  Deleted chain.acc.zip and/or chain.acc (if you incorrectly unzipped it)
Step 4)  downloaded http://static.neo.org/client/chain.acc.zip
step 5)  copy ( **_DO NOT UNZIP_** ) chain.acc.zip to same folder as neo-gui.exe
step 6)  run neo-gui.exe 

after about an hour both my 2nd and 3rd numbers were at 1.8 million each ... if yours aren't syncing that fast... you didn't follow those instructions correctly.. please re-read.

If you ever get stuck on a block after that, try closing down neo-gui, delete peers.dat only, and re-open neo-gui
