### ISSUE TITLE
adding chain.acc.zip to neo-gui folder breaks app -- KeyNotFoundException

### ISSUE THREAD

**Issue by ceteris** [neo-project/neo-gui#205]
it works if I remove chain.acc.zip, breaks if I add it back -- tried deleting the chain folder and also the peers.dat file and also just starting with a clean download

I get this error:

System.Collections.Generic.KeyNotFoundException
The given key was not present in the dictionary.
   at Neo.IO.Caching.DataCache`2.GetAndChange(TKey key, Func`1 factory)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by jrsikors** [comment]
@ceteris  -- where did you download the chain.acc.zip from .. and when did you download it?  Can you unzip it (you shouldn't unzip it, but i'm curious if you CAN.. would eliminate a possible corrupt zip file).

What's the date/timestamp on the chain.acc file within the zip?

@erikzhang  -- few things:
  1) does the chain.acc.zip file get re-uploaded nightly or a few times a week?
  2) might be worth it to have a few different copies of it in case one gets corrupt
  3) might be worth it to try to have it hosted in a couple different places

**Comment by erikzhang** [comment]
Monthly.

**Comment by ceteris** [comment]
yes can unzip the blockchain archive, so file not corrupted

creation date shows as two days ago, but that’s just when I downloaded it

I’m also copying the whole release folder when I try different things to make sure it’s a clean restart

but — deleting the chain folder and peers.dat is also considered a clean restart?

thanks for your help







On Mar 7, 2018, at 6:02 PM, Erik Zhang <notifications@github.com> wrote:

Monthly.

**Comment by jrsikors** [comment]
Sorry -- yeah deleting the chain folder is considered a clean re-start.  I wouldn't worry about the peers.dat, but it couldn't do any damage to wipe that away as well.

**Comment by jrsikors** [comment]
check this out as well:
https://www.reddit.com/r/NEO/comments/83j7dl/is_your_neo_node_stuck_at_2000190/

**Comment by ceteris** [comment]
thanks


On Mar 12, 2018, at 3:54 PM, Jeff S <notifications@github.com> wrote:

check this out as well:
https://www.reddit.com/r/NEO/comments/83j7dl/is_your_neo_node_stuck_at_2000190/ <https://www.reddit.com/r/NEO/comments/83j7dl/is_your_neo_node_stuck_at_2000190/>

**Comment by jrsikors** [comment]
So are you good to go now?  Or still fighting it?

**Comment by ceteris** [comment]
no, I gave up —  just using the docker image

one thing I am unclear on is wether I have to build leveldb from source or download the dll — I’ve done both, don’t think it made a difference but I might have lost my way on that



On Mar 14, 2018, at 12:20 PM, Jeff S <notifications@github.com> wrote:

So are you good to go now? Or still fighting it?

**Comment by jrsikors** [comment]
So are we good to close this issue?  I'm sure it's been brought to the attention of the NEO devs.

That reddit link i posted ,,, it looks like CoZ took down the bootstrap download, and refers people back to the chain.acc.zip again... so it was probably not solving any problems.

**Comment by ceteris** [comment]
sure — I’m done — thanks



On Mar 16, 2018, at 10:03 AM, Jeff S <notifications@github.com> wrote:

So are we good to close this issue? I'm sure it's been brought to the attention of the NEO devs.

That reddit link i posted ,,, it looks like CoZ took down the bootstrap download, and refers people back to the chain.acc.zip again... so it was probably not solving any problems.

**Comment by jrsikors** [comment]
@erikzhang you can close this issue up please!

**Comment by drabadan** [comment]
you might not have changed the protocol.json settings... 
I had the same issue because I changed the config.json but not changed protocol.json to testnet
