### ISSUE TITLE
asking for basic help 

### ISSUE THREAD

**Issue by Johnydog** [neo-project/neo-gui#207]
Hi guys, hoping you can save a desperate soul here. i'm running a Neo Gui wallet which hasnt been updated since August. Never done an update! Now trying to figure out why i cant see my ONT tokens and the answer seems to be that i need to update to the latest version. This freaks me out! 

 " It is recommended to back up the older chain data in advance and to export offline synchronization data chain.acc to speed synchronization." How do i do this?

please help, i literally afraid to break my wallet and lose my neo

**Comment by jrsikors** [comment]
just load up your current version of NEO , right click your wallet, view private key.
Copy/paste/write down all the information ... then your NEO is 100% safe and worst case scenario you can load up your wallet/private key on a different wallet.

The instructions are pretty simple and clear here:
http://docs.neo.org/en-us/node/gui.html

**Comment by Johnydog** [comment]
Thank you so much for the response! Appreciate its a basic question, and even having you responding makes me feel like im not in this alone! 

I've downloaded the new client and pasted the chain.acc.zip in the directory. Its been syncing for a bit now. The first number is 0, second is still syncing and third stopped reaching 2000190. Can I try and load my wallet now or wait for the second number catch up to the third?

**Comment by jrsikors** [comment]
You should wait until the 2nd and 3rd numbers are matched.. but there's no real harm in opening it.  It's just that when you open it, you will be stuck with an open wallet for hours and hours while you remain syncing

If at any point you think it's stuck, just close out of NEO-GUI, and re-open it.

**Comment by jrsikors** [comment]
How's it going with this one?  You look at #212  ?

Are you jdog88 who posted #212? :smile:

**Comment by Johnydog** [comment]
Thanks for checking up on me, I'm still going, currently on my second attempt to sync the chain.  Up to 174XXXX on the second and the third is syncing to current high this time... My first attempt the third number was stuck on that number in issue #212 so just restarted... On the positive im more confident with it, but wallet conversion still tbc, hope it goes ok.

Not the same person as #212, yeah not sure about the name - maybe everyone likes dogs? ha ha ha

**Comment by jrsikors** [comment]
So are you good to go?  I saw in #212 you seemed like you were ok enough to close this issue?

You can close the issue yourself if you are good... there should be an option somewhere since you created it.

**Comment by Johnydog** [comment]
@jrsikors not yet... im still downloading the chain can you believe?! I'm now up to 1954XXX.

Would appreciate if we keep this one open in case something goes wrong?

**Comment by jrsikors** [comment]
yeah that's fine -- check your Windows Task Manager every chance you get -- if it's running at 100% ... try closing down NEO-GUI and re-opening it.  After running for a few hours and syncing it starts sucking up a lot of CPU.. making it sync even slower.

**Comment by Johnydog** [comment]
oh man @jrsikors just when i thought were on track, noticed third number is tuck on 2,022,689, current height is 2,030,900... What do you reckon? really don't want to restart sync agian

**Comment by jrsikors** [comment]
In 212 you posted this:

-----------------------------------
_Deleted Neo Gui folder
Downloaded NEO Gui again
Downloaded "Offline Synchronized Data"
Extracted downloaded NEO-Gui into a folder in C:\ drive
**Opened the extracted NEO-Gui folder, then, extracted the downloaded "Offline Synchronized Data" into the NEO-Gui folder (root directory)
The "chain.acc" file will be in the NEO-Gui folder**
Ran "NEO-Gui.exe"

It quickly synced to latest block hight_

--------------------------------------

In the parts i bolded -- you weren't supposed to unzip the chain.acc .. you are supposed to leave chain.acc.zip in zipped format and place it in the directory as neo-gui.exe

how long ago did you download the http://static.neo.org/client/chain.acc.zip ?  If it was more than a week ago, I would try downloading it again, it might be updated.

**Comment by Johnydog** [comment]
Hasn't been a week. maybe 5 days. but gutted. cant believe i have to restart.

**Comment by jrsikors** [comment]
I'm downloading the chain.acc.zip right now.

After that -- I'm going to:
Step 1) Rename my working chain folder to chain-old
Step 2) Copy the chain.acc.zip to my neo-gui folder  (AND DONT UNZIP IT)
Step 3) Run neo-gui.exe

So I can see if it's functioning as designed.  It really shouldn't be this painful for people.. there must be a step you are all missing .. like you are:
  A)  unzipping the chain.acc.zip 
  B)  you are trying to put the chain.acc.zip inside the Chain folder instead of the same folder as NEO-GUI.exe 

Both of those things are incorrect :D

**Comment by jrsikors** [comment]
So I just did this
step 1)  Downloaded the latest https://github.com/neo-project/neo-gui/releases/latest
step 2)  Downloaded the chain.acc.zip from http://static.neo.org/client/chain.acc.zip
Step 3)  Unzipped it to c:\NEO26  (or wherever)
Step 4)  *COPIED* *DIDNT UNZIP* the chain.acc.zip to C:\neo26
Step 5)  Launched neo-gui from c:\neo26

Within 10 minutes of opening ... my 2nd and 3rd numbers are already at 1.25 million each ... and i have 0 'connections' ... which means the chain.acc.zip is doing its job.

I have not opened my wallet file yet -- nor will I until I am sync'd

So -- I think you need to pay very close attention to my steps and do them exactly.  You aren't doing something right... either you are:
  A)  Not on the latest 2.6 NEO GUI, my step 1 will cover that
  B)  Have a bad chain.acc.zip, my step 2 should cover that
  C)  Have data in your chain folder already which is preventing the chain.acc.zip from working properly..  my step 3 will cover that (will create a brand new fresh directory for Chain folder)
  D)  Are unzipping the chain.acc.zip ... my step 3 will cover that

**Comment by jrsikors** [comment]
update:
after about an hour, it looks like it stopped 'speed syncing' at around 0 / 1.8 million / 1.8 million  ... and the remaining 1.2 million'ish blocks will need to sync normally .. which will probably be a while.

**Comment by Johnydog** [comment]
@jrsikors you are an absolute legend, thank you for taking the time to help me. I really do appreciate it.
I have followed the steps you've outlined above. The third number has correctly synced to the latest block (2,036,663 at the moment). The second number is still going, its pretty low at 234,680 (as i type) so will let it run overnight.

I know now i was making stupid errors, probably issues with steps 2 and 3 and 4 as well as i did unzip the chain initially (not sure why i decided that was the right thing to do!).
I'm not sure why its so hard, for me at least for me i think its just lack of confidence as anything you do here could have an actual financial impact... 
It would be great if there was a video/more visual guide for this stuff. As i mentioned, i just downloaded NEO GUI in August and never bothered upgrading as there was no reason to.

**Comment by jrsikors** [comment]
Between this trifecta of issues:
 issue 1) the CPU on your computer getting pegged at 100% after a couple hours
 issue 2) random nodes being wonky and making you get stuck on a particular block
 issue 3) the chain.acc.zip only getting you to the 2 million block

the syncing of NEO-GUI 2.6 is pretty rough right now for the average person.

the only workaround when you are stuck seems to be:
 Step 1)  Close down neo-gui
 Step 2)  Delete peers.dat
 Step 3)  Re-open neo-gui

This hopefully pushes you past the stuck block ... and repeat those steps every time you get stuck on a block for more than ~30 mins

**Comment by jrsikors** [comment]
@erikzhang can you please try to get the team to upload a newer chain.acc.zip that syncs to the latest block this week if time permits :smile:   ... something a lot closer to the 3 million block.

**Comment by jrsikors** [comment]
oops i'm dumb, NEO is at the ~2 million block, not ~3 million .. wrong crypto sorry :smile:

**Comment by jrsikors** [comment]
but @Johnydog  -- if your 2nd number isn't climbing FAST , then you didn't do the chain.acc.zip step properly... and i would suggest trying again.

If you do the chain.acc.zip step properly... your 2nd and 3rd numbers should ZOOM to the 1.8 million block.  Like you should be at:
**_0 / 1.8 mil / 1.8 mil_** 
within an hour

If you aren't -- and your 2nd number looks like it's going to take you months... you didn't do something correct and i would suggest starting over:

step 1) Downloaded the latest https://github.com/neo-project/neo-gui/releases/latest
step 2) Downloaded the chain.acc.zip from http://static.neo.org/client/chain.acc.zip
Step 3) Unzipped it to c:\NEO26 (or wherever.. make sure its a NEW FRESH DIRECTORY)
Step 4) COPIED DIDNT UNZIP the chain.acc.zip to C:\neo26 (or wherever you did step 3)
Step 5) Launched neo-gui from c:\neo26 (or wherever you did step 3)

Don't cheat and take shortcuts -- perform those steps exactly.

Essentially:
Get rid of any chain.acc's you unzipped ... get rid of chain.acc.zips ... get rid of your Chain folder ... get rid of your peers.dat file.

**Comment by Johnydog** [comment]
Well, after a full night my second number was still lagging.

I've just deleted peers.dat file and the Chain folder (which was in the unzipped NEO folder). That took my chain back to 0/0/0 so i guess were starting again...

I definitely definitely followed steps 1 to 5 above for sure! heading to work now, see what i come home to.

**Comment by jrsikors** [comment]
You should know immediately, within 2 minutes , whether you set everything up properly.  Your 2nd and 3rd numbers should start flying

**Comment by Johnydog** [comment]
so got back from work, third number synced fine, second number is sun 200,000. 

What do you reckon?

**Comment by Johnydog** [comment]
OK latest status is that i had a beer deleted everything and started again!
Current sync is 0/1,383,115/2,045,543  Connected:1

Surely i just wait for the second number to sync now?

**Comment by jrsikors** [comment]
That's the plan.

Latest block is now:
2,041,863

So it is kind of weird that your 3rd number was higher :smile: , but maybe you typo'd it .. but not a problem

**Comment by Johnydog** [comment]
yep that was a typo! I'm going to work from home today and babysit this thing.  

Current status is;
![picture1](https://user-images.githubusercontent.com/37173005/37629187-848726ea-2c31-11e8-9645-7dc463821b2d.png)

**Comment by Johnydog** [comment]
![picture1](https://user-images.githubusercontent.com/37173005/37629224-b55a36a4-2c31-11e8-8225-eeeb8435cb93.png)

**Comment by katzky** [comment]
The workaround of deleting the peers.dat file is not working for me. I continue to be stuck at block 2,022,689.

**Comment by Johnydog** [comment]
Just wanted to say i'm all set!  After the second and third numbers finally synced, wallet conversion and adding the NEP-5 ONT token was straight forward. 

Thank you again @jrsikors for the support, patience and just being here for a basic user like myself.

**Comment by jrsikors** [comment]
:bowing_man:
