### ISSUE TITLE
Windows 10 x64 CLI client error

### ISSUE THREAD

**Issue by KyferEz** [neo-project/neo-gui#209]
When trying to run the CLI version of NEO on Windows 10, we receive this error:

C:\Programs\neo-cli-win10-x64>neo-cli

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Neo.IO.Data.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)

**Comment by jrsikors** [comment]
probably steps in #208 should fix this as well.  Apply the fix for #208 and let us know if this is still a problem with the same error

**Comment by KyferEz** [comment]
Jrsikors,

No, the installation of the VC++ Redist did not help for this error and it has remained the same.

Thanks!

**Comment by jrsikors** [comment]
I saw this reference to a super old issue:
https://github.com/neo-project/neo-cli/issues/24

But perhaps you might be better off posting it under the:
https://github.com/neo-project/neo-cli/issues/
page (This is the neo-gui page)

**Comment by jrsikors** [comment]
and you mentioned it did NOT fix this #209, but did it at least fix your #208  ?

**Comment by KyferEz** [comment]
Yes, it did fix 208, and oops didn't realize I made that mistake.

**Comment by jrsikors** [comment]
No prob -- I'm such a noob at this i didn't even realize there was a separate CLI forum... I just loiter on this one.. I haven't played around with the CLI.

If you can -- please close #208 and #209 for @erikzhang  !

**Comment by jrsikors** [comment]
@erikzhang you can close this one too , he stated he will post issue on the CLI forum
