### ISSUE TITLE
Block stuck at 2,000,190 won't sync

### ISSUE THREAD

**Issue by Jdog88** [neo-project/neo-gui#212]
Anyone else have this problem? Block stuck at 2,000,190 and won't add any more blocks to it. Everything just stuck there for days.

**Comment by Johnydog** [comment]
same issue here

**Comment by Johnydog** [comment]
Jdog88, i've resolved my issue by starting again...

Deleted Neo Gui folder
Downloaded NEO Gui again 
Downloaded "Offline Synchronized Data"
Extracted downloaded NEO-Gui into a folder in C:\ drive
Opened the extracted NEO-Gui folder, then, extracted the downloaded "Offline Synchronized Data" into the NEO-Gui folder (root directory)
The "chain.acc" file will be in the NEO-Gui folder
Ran "NEO-Gui.exe" 

It quickly synced to latest block hight

**Comment by jrsikors** [comment]
solution here (I haven't tested it, but looks legit)
https://www.reddit.com/r/NEO/comments/83j7dl/is_your_neo_node_stuck_at_2000190/

**Comment by PeterLinX** [comment]
@Johnydog @Jdog88 @jrsikors Some of nodes have this problem recently, just resync your blockchain will be fine. You can use this offline blockchain data package(http://static.neo.org/client/chain.acc.zip) to make it faster.

**Comment by jrsikors** [comment]
@PeterLinX  ... it seems like some people are having the problem even with the chain.acc.zip ... unless there is a newer chain.acc.zip that gets you past the 2000190 block.

It actually looks like CoZ removed the non chain.acc.zip bootstrap ... judging on some of these  comments ... i wonder if it wasn't fixing it and causing more problems.

**Comment by Jdog88** [comment]
@PeterLinX @jrsikors I used Peter's Link above and resync the blocks and it reached over 2000190.

**Comment by vidov1** [comment]
WTF ? How can this happen ? What's the point of having a block chain, if you have to download its contents from one single centralized location in order to be able to work with it ?

**Comment by jrsikors** [comment]
I can't tell if your comment is meant to be funny @vidov1  :smile: 

You can always start from 0/0/0 and download the blockchain the way it was originally intended to be done... which is downloading blocks 1 at a time.

**Comment by jrsikors** [comment]
@Johnydog @PeterLinX .. so i noticed in Johnnydogs, instructions you actually UNZIP the chain.acc.zip .. that wouldn't be what the instructions at http://docs.neo.org/en-us/node/gui.html say to do.  

Are the instructions on the site wrong?  Do you actually need to unzip the chain.acc.zip ?

**Comment by jrsikors** [comment]
@erikzhang  as well .. see my previous post

**Comment by erikzhang** [comment]
No, we needn't unzip it.

**Comment by jrsikors** [comment]
Thanks @erikzhang  -- you can close this one -- @Jdog88  , who originally posted the issue, said he was good to go.

Anyone else still having similar or different problems should create a new issue.
