### ISSUE TITLE
Master branch is not compatible with current version of Neo.VM

### ISSUE THREAD

**Issue by joaocarlosleme** [neo-project/neo-gui#216]
Can't build neo-gui with current version of Neo.VM, other than 2.0.4.

Error on neo-gui\UI\TransferDialog.cs line 66 and on neo-gui\UI\MainForm.cs line 455. They both call GetArray(), but the method was throwing a new NotSupportedException() and was removed on Feb.2nd commit. See [commit changes](https://github.com/neo-project/neo-vm/commit/3fd0c9f09cbfdfffed86cbef845ad920f751a0fa#diff-d37b711635d0e87d78bf30389416e2ac).

Is there something broken or am I missing something?

**Comment by erikzhang** [comment]
The master branch of neo-gui is not compatible with current version of Neo.VM.

**Comment by joaocarlosleme** [comment]
Why there ain't no other branch available, other than master?
