### ISSUE TITLE
GAS Claim

### ISSUE THREAD

**Issue by NeoAntman85** [neo-project/neo-gui#217]
Hi everyone,
similar issue here re the gas claim. I do run the latest version of NEO gui (2.6.6596.21976).
All three parameters are in sync and I am up to date re the blocks.
I have recently made a gas claim and received a tx-number.
The aforementioned number is not being recognized on the https://neotracker.io/ but on antcha.in.
https://neotracker.io/ does show me an unclaimed GAS amount though when I enter my public address.

Neo gui also shows the 'missing' amount in brackets under "Asset", it does however not show under 'NeoGas' in the "Account" section.
Under "NeoGasClaim" it shows all the 'missing' gas as "unavailable".

What do I need to do to claim my gas?

Thanks in advance!

**Comment by jrsikors** [comment]
Should be a 3 step process:
Step 1)  Send NEO to yourself
Step 2)  Wait a few mins
Step 3)  Go to Advanced -> NEOGas Claim  ... and the button to 'claim gas' should be there

What steps are you doing when you say this:

> I have recently made a gas claim and received a tx-number.

**Comment by NeoAntman85** [comment]
@jrsikors Thanks for getting involved in my help request first of all!

Re your question "What steps are you doing when you say this: 'I have recently made a gas claim and received a tx-number.'?" 

Answer: I have actually done exactly what you described in step 3; the given amount had shown under "Available" and I was able to click on the "Claim All" button. That's when I received the tx number.
The current status is as described above: I have never received the gas but it all shows under "Unavailable" in the aforementioned window and "Claim All" is greyed out.

**Comment by jrsikors** [comment]
You are stuck at 2,022,689 , same block number as #215  .. which is odd.

That would explain why you can't send NEO and claim GAS, you aren't really sync'd.

My only tip is to close down NEO-GUI .. delete peers.dat .. and re-open NEO-GUI ... but #215 stated that didn't work.

So your only other option might be to follow my steps in #215 , nuke everything and start the sync over

**Comment by jrsikors** [comment]
i meant #219 as well for instructions

**Comment by NeoAntman85** [comment]
Hi there again,
followed your instructions as mentioned in #219; fresh GUI download, new directory, chain download as zip file, launch & waiting for sync... And guess what; stuck at 2,022,689 **again.**

Any further recos for me? :-(

**Comment by jrsikors** [comment]
yikes.  no clue

@PeterLinX @erikzhang :
Any nodes having problems on block   2,022,689 ?  multiple people reporting being stuck on that specific block

**Comment by erikzhang** [comment]
Yes, there is an issue at https://github.com/neo-project/neo/issues/193

**Comment by jrsikors** [comment]
thanks Erik -- are you all (can you please? :smile: ) going to be putting a new chain.acc.zip out there anytime soon to get people past that block?

**Comment by NeoAntman85** [comment]
Hi there, after another attempt it has now synced; I am up to 2084065 with all three parameters.
However the gas amount is still unchanged; the claim did not come through. 

As described: Under "Asset" I can see my current gas balance and the "missing amount"; it looks like this:
Balance: x.xx +(xx.xx); the "x" as a proxy for my actual gas amounts.
When I double-click that line it tries to take me to https://www.antchain.xyz without success due to an obsolete certificate. 
Under "Advances - NeoGasClaim" it shows the missing amount under "Unavailable".

Any ideas on how I can claim my gas? I obviously do not want to lose it.
Many thanks again!

**Comment by jrsikors** [comment]
Now that you are sync'd -- you need:
 Step 1) Send NEO to yourself , same address
 Step 2) Wait a few mins
 Step 2) Go to Advanced -> NeoGas Claim
 Step 3)  The button to claim Gas will be clickable

GAS isn't under the "Asset" I dont think

**Comment by jrsikors** [comment]
OK i just checked -- yeah NeoGAS is under Asset.  I rarely use the Asset tab sorry !

Either way -- my previous steps still apply for claiming NeoGas

**Comment by jrsikors** [comment]
What's the word on this?  You good to go now ?

**Comment by NeoAntman85** [comment]
Hi, sorry for the delayed response!
Was not able to look into it until now. 
Anyways - your proposed solution worked, many thanks again!
