### ISSUE TITLE
Configuration changes made after starting a sync don't take effect

### ISSUE THREAD

**Issue by juliavi** [neo-project/neo-gui#218]
Started to sync from the mainNet, then closed the neo-gui and changed the configuration to testNet.
After opening the gui again, it started to sync to the right folder but it was actually still syncing from the mainNet.

**Comment by erikzhang** [comment]
There are two .json files that need to be changed: "config.json" and "protocol.json". You need to change them both.

**Comment by juliavi** [comment]
Of course I changed them both.

**Comment by jrsikors** [comment]
can you copy/paste your config.json and protocol.json ?

**Comment by jrsikors** [comment]
In addition to that.. don't want to assume, but are you on the latest 2.6 client?

If you are -- double check the config_mainnet.json template against your config.json template.  

Depending on what version you are upgrading coming from -- NEO team has changed the format of the config.json .  So if you are trying to bring over an older version / different format of config.json .. that could be it as well.

**Comment by juliavi** [comment]
I'll look into the code and update
