### ISSUE TITLE
I compile and run the program, it seems that the client cannot connet to any node

### ISSUE THREAD

**Issue by ghost** [neo-project/neo-gui#22]
as descriped in title

**Comment by JOBTC** [comment]
Having the same issue, connected fine a few days ago, now says connected 1 , but not updating?

**Comment by lukeamac** [comment]
Thanks Erik, didn't see this open.

**Comment by erikzhang** [comment]
nop. I just reference this issue to another so that I can close them after resolving the problem.

**Comment by erikzhang** [comment]
The problem seems to have been solved.
