### ISSUE TITLE
Neo Gui doesn't recieve new blocks

### ISSUE THREAD

**Issue by uschwenkert** [neo-project/neo-gui#220]
After upgrading to Neo Gui v2.6.0 synchronzing the blocks up to block height 2000190. Since then Neo-gui is waiting for the next block but nothing happens. It shows "Connected: 10". 

Can anyone give me a hint whats wrong ?

![grafik](https://user-images.githubusercontent.com/32311643/37861976-0041d2b4-2f46-11e8-9844-8b5f989af5d4.png)

**Comment by jrsikors** [comment]
#215 , #219 , #211 

You and lots of others.

follow my steps in #219 exactly

**Comment by jrsikors** [comment]
But i will say, in #217  -- he got stuck on a different block, and a couple other people have gotten stuck on a different block (2,022,689) -- so you can give it a shot , but it might actually be wise to wait a few days and give the team a chance to try to fix the issue

**Comment by jrsikors** [comment]
Any update on this?  Were you able to get sync'd?

**Comment by uschwenkert** [comment]
I followed the steps in  <https://github.com/neo-project/neo-gui/issues/219> #219. Up to block 1200000 it got sync’d within 10 minutes. 

Neo is still synching, it is incredible slow. Block height is 1681330 in this moment.

 

 

Von: Jeff S <notifications@github.com> 
Gesendet: Montag, 2. April 2018 18:55
An: neo-project/neo-gui <neo-gui@noreply.github.com>
Cc: uschwenkert <schwenkert@online.de>; Author <author@noreply.github.com>
Betreff: Re: [neo-project/neo-gui] Neo Gui doesn't recieve new blocks (#220)

 

Any update on this? Were you able to get sync'd?

**Comment by uschwenkert** [comment]
I got sync’d. Thanks
