### ISSUE TITLE
Neo-gui client UI thread blocked during bootstrapping

### ISSUE THREAD

**Issue by katzky** [neo-project/neo-gui#221]
When using the bootstrap method of syncing the blocks, the GUI often becomes unresponsive.

**Comment by jrsikors** [comment]
might be similar to enhancement request #172 

NEO-GUI can be a resource hog... have you looked at windows task manager during the process to see if CPU is pegged at 100%?

**Comment by katzky** [comment]
No it is not consuming a ton of resources. The GUI become unresponsive and I am 99.9% sure this is due to the UI thread being blocked by another thread.

**Comment by jrsikors** [comment]
I can definitely also confirm the unresponsiveness during sync, I just assumed it was due to the heavy taxing on the system's resources.  I won't argue with you :smile:

**Comment by erikzhang** [comment]
resolved
