### ISSUE TITLE
Neo GUI 2.6 - Unhandled exception

### ISSUE THREAD

**Issue by SlyCognito** [neo-project/neo-gui#223]
Hi,

When I try to open wallet database it just says unhandled exeption has occurred in your application. The type initializer for 'Neo.WalletsIndexer' threw an exeption. Otherwise the wallet is fully synced. I have attached the log details below. Any help would be appreciated, Thanks.

[Neo Unhandled exception.txt](https://github.com/neo-project/neo-gui/files/1848113/Neo.Unhandled.exception.txt)

**Comment by jrsikors** [comment]
check out #118 

To solve this, please install vs2010 redist x86 and x64:

https://www.microsoft.com/de-de/download/details.aspx?id=14632

https://www.microsoft.com/de-de/download/details.aspx?id=5555

**Comment by SlyCognito** [comment]
Thanks a lot. Had nothing but problems since 2.6.  Just for reference and to anyone else encountering this problem had to delete the index_xxxxx folder as well as installing the above.

Thanks again.

**Comment by jrsikors** [comment]
no prob..

@erikzhang  you can close this one up !
