### ISSUE TITLE
Neo Wallet Problem a sudden: System.NullReferenceException

### ISSUE THREAD

**Issue by boxalex** [neo-project/neo-gui#224]
Hello, my 2.6 NEO wallet on Windows 10 worked perfectly until now. I had in for longer installed and had no issues since today.

Issue:
After i open the client it shuts down after some seconds.
Height: 0/2074349/2084562 while i wonder where the 0 comes a sudden from?!

Error.txt
System.NullReferenceException
Object reference not set to an instance of an object.
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Solutions tried so far, each without any success:
- reinstalled NEO application, copied over old Chain
- reinstalled NEO application, copied over old Chain and removed last 3 blocks
- reinstalled .NetFramework 4.7.1 (did not work as i got a win10 message that 4.7 or newer is installed allready)
- reinstalled vcredist_x64
- reinstalled vcredist_x86
- run as admin
- tried to launch with Nsight Hud

Additionally Information about high Resources when loading a Wallet .json file.

I run really a high performance PC, 64GB RAM, I7-8700 CPU, 2x 1080ti GPUs, but while loading the wallet takes a long time and freezes everything in the NEO client meanwhile. No idea what's left for low performance lap top users...

Any idea what to do as i need my NEOs transfered ASAP !!!!

**Comment by boxalex** [comment]
Update:
Here the exactly block when the NEO Gui crashes on my end each time:
2,074,349/2,088,179

maybe this info helps as well.

**Comment by jrsikors** [comment]
One thing I noticed you didn't try is with a fresh Chain directory.. which is a pain but it's a must.

You need to:
 1)  Delete your chain directory
 2)  download http://static.neo.org/client/chain.acc.zip
 3)  copy that zip... DO NOT UNZIP IT .. to the same directory as NEO-GUI.exe
 4)  run neo-gui.exe , and let it sync

You could always follow those steps, grab your private key  while it's syncing, and go use another wallet if you are in a rush and can't wait for full sync.

**Comment by jrsikors** [comment]
and the 3 numbers are:
first number = where your wallet is sync'd to ... so if you dont have the wallet loaded, it will be 0
second number = where your computer is sync'd to
third number = latest block in the block chain

So you to get fully sync'd, you need to wait until 2nd and 3rd numbers get syncd... then open wallet and let 1 sync.  So all 3 numbers should be equal and on the latest block eventually

**Comment by jrsikors** [comment]
any update here ?

**Comment by boxalex** [comment]
Hi, yes, i get a 404 Error on http://static.neo.org/client/chain.acc.zip .
I just switched to City of Zion Neo Wallet which works just fine.
I prefer real desktop wallets like the NEO Gui, but i have not the time to play around for days, so i best wait until a stable reliable version gets out.
Anyway, thx a lot for your help, i appreciate your continous afford. Hence i love NEO :-)
