### ISSUE TITLE
raises 'insufficient funds' error with NEP-5 Token (decimal != 8)

### ISSUE THREAD

**Issue by maisumakun** [neo-project/neo-gui#226]
Decimals of NEP-5 tokens are likely to not considered in transfer dialog [like this](https://github.com/neo-project/neo-gui/blob/0c2964dcc4b1fc91bb6ccac8c677547ced29803b/neo-gui/UI/PayToDialog.cs#L53), resulting in incorrect balance calculation for tokens whose `decimals` is not 8.

**Comment by 10Bit000** [comment]
Hey. Need help with neo-gui. How to find support?
