### ISSUE TITLE
The Private Key that Can Sign the data is not found

### ISSUE THREAD

**Issue by niastakevin** [neo-project/neo-gui#229]
![issues](https://user-images.githubusercontent.com/17697662/38536180-fd80db50-3cb1-11e8-8adf-e70a7e204e7c.png)

i dont understand what happened. transfer NEO from Contract Address to Standart Account, get the script signature (already created multi-sig before do the transfer). when tried to copy the trxid to signature wallet 2, this happened.

**Comment by solinter** [comment]
The same issue. +1

**Comment by niastakevin** [comment]
Hi Solinter, i just found the solution. You have to create multi-sig in 4 wallets (contract address).

**Comment by solinter** [comment]
Thank you!
