### ISSUE TITLE
Neo-Gui not working

### ISSUE THREAD

**Issue by Shaunrosenberg** [neo-project/neo-gui#23]
I downloaded the Neo-Gui folder, I copied the "Chain" file from my antshares wallet and pasted it into the NEO folder.  I went down and clicked on the Neo-Gui folder and it said "File not found"

I tried multiple times and it normally doesn't have the Neo-Gui logo on it. But all of the time it said "File not found"

**Comment by erikzhang** [comment]
Can you send me a screenshot?
