### ISSUE TITLE
Neo Gui Exception (System.ArgumentException)e

### ISSUE THREAD

**Issue by Seahorst** [neo-project/neo-gui#231]
Hi,

after opening the GUI (2.26442.408), the system starts syncing for a minute or so and then throws an exception. I am using this GUI since more than 6 month now an I wonder why it is not working anymore - perhaps someone can help? 
The error log contains the following:

System.ArgumentException
Der Wert liegt außerhalb des erwarteten Bereichs.
   bei Neo.IO.Caching.DataCache`2.Add(TKey key, TValue value)
   bei Neo.SmartContract.CloneCache`2.Commit()
   bei Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   bei Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

Thanks a lot!

**Comment by Ashuaidehao** [comment]
Hi @Seahorst , is this problem still happen? Did you try to run it using the last version?

**Comment by Ashuaidehao** [comment]
Hi  @Seahorst ，we're planning to close this issue due to inactivity.
If you still have problems, please reopen this issue or create a new one.
@lock9 can you help to close this ,thanks!
