### ISSUE TITLE
How can I modify the numbers of the node for Test

### ISSUE THREAD

**Issue by neotokens** [neo-project/neo-gui#233]
I want to use only one node to build the private chain for consensus and where I should modify for the code?
(我想用一台节点实现私链共识，请问我需要修改代码的什么地方?)

**Comment by neotokens** [comment]
Is there anybody here please?

**Comment by dinihou** [comment]
i am not neo developer but i found this :
"The deployment of an NEO private chain requires at least four servers to reach a consensus"
source : http://docs.neo.org/en-us/network/private-chain.html

**Comment by Ashuaidehao** [comment]
Hi @neotokens, does the link resolve your problems?

**Comment by shargon** [comment]
Closed because @neotokens has not answered since May 2018
