### ISSUE TITLE
Neo GUI not show assets

### ISSUE THREAD

**Issue by kostepanych** [neo-project/neo-gui#236]
I created a wallet in NEO GUI and withdraw Red Pulse (RPX) tokens from binance to this wallet.
I can see those tokens in neotracker but they no show in NEO GUI. Transactions also not show.
Why?
NEO GUI is synced.

**Comment by dinnur73** [comment]
![image](https://user-images.githubusercontent.com/36741206/39878221-dca5e058-5488-11e8-8ab1-e3ce5e15817e.png)

**Comment by jrsikors** [comment]
do you have the script hash 0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9 added for it?

**Comment by gitbrook** [comment]
I am also having a similar issue with the MCT token. I invoked a contract to pull in the MCT hash: a87cc2a513f5d8b4a42432343687c2127c60bc3f 

The transaction was confirmed, but I am not seeing MCT listed under assets or under options. I do see the airdropped MCT on the block explorer for my address.

**Comment by jrsikors** [comment]
are you:
  A)  On the latest NEO 2.6
  B)  Fully sync'd and on the latest block (2,272,764)

**Comment by gitbrook** [comment]
Yes, on 2.6 and was fully synced when I did this last Saturday, but haven't checked since then. I closed the wallet after 60+ confirmations of the transaction.
