### ISSUE TITLE
.db3 can't convert to json

### ISSUE THREAD

**Issue by CrypJohn** [neo-project/neo-gui#237]
Downloaded 2.6 version but wallet file can't be converted/openend. Can I still transfer funds if I go back to 2.5.2.?

**Comment by jrsikors** [comment]
check out https://github.com/neo-project/neo-gui/issues/118

if you are having issues converting.

But as I said in my other post -- definitely use 2.5.2 and get your private keys exported / safe place before you continue

**Comment by CrypJohn** [comment]
thanks for response, but sorry, can't find the solution in 118.

Can I still use 2.5.2. for transfers? Or is 2.6 update mandatory?

**Comment by CrypJohn** [comment]
it's almost fully synced again after a week, but can't see my NEP5 tokens yet (scripts added)

**Comment by jrsikors** [comment]
I personally wouldn't suggest it, and it's not recommended.  

I personally have transferred funds while not sync'd and had both successes and failures different times.  I think you are safer doing 1 of 2 things:
  A)  Export private keys from 2.5.2 , and create a new wallet in 2.6 , and import private keys.  This way you don't have to "upgrade" your wallet from 2.5.2 to 2.6.  You are creating a brand new 2.6 formatted wallet, and then importing your old private keys.  This is what I ended up doing to be on the safe side.
  B)  Export private keys from 2.5.2,  and set up a NEON wallet

**Comment by CrypJohn** [comment]
good advice, better be on the safe side. thanks!
