### ISSUE TITLE
neo-gui assest exception

### ISSUE THREAD

**Issue by dinihou** [neo-project/neo-gui#238]
hi
i create an assets at neo private chain but when i distribute it i have this error on reception wallet
![neo_1](https://user-images.githubusercontent.com/25209492/40625324-b5e1b756-62c2-11e8-964e-91f566ea7895.png)

any info what problem ??

**Comment by dinihou** [comment]
problem in neo-gui only ,neo-cli just work fine
best to handle exceptions guys ,this is a 4B$ project ,seriously !!

**Comment by erikzhang** [comment]
I need the exception message.

**Comment by dinihou** [comment]
exception is :
Settings.Defaut.Paths is "null"
as you see , There no "Paths" element var in settings structure , but "neo-gui" tray to create dir on this var

![neo_2](https://user-images.githubusercontent.com/25209492/40779990-041422e8-64e8-11e8-94d1-52453dc5d79e.png)

**Comment by erikzhang** [comment]
Please send me the exception message.

**Comment by dinihou** [comment]
note :
- i am running in private network
- error when neo-gui try parse my registered asset

exception message :
https://prnt.sc/jp728t

**Comment by erikzhang** [comment]
It seems that the problem is in the configuration file.
Can you provide me your config.json?

**Comment by dinihou** [comment]
of course :
http://prntscr.com/jpifbl

**Comment by erikzhang** [comment]
I know where the problem is. You provide a neo-cli configuration file that cannot be used in neo-gui.

**Comment by dinihou** [comment]
my mistack , i dont know how cli config come to gui folder
i fixed it , thanks bro , keep good work
