### ISSUE TITLE
请问什么调式官方给的demo Domain（域名系统)

### ISSUE THREAD

**Issue by ly745455** [neo-project/neo-gui#239]
请问什么调式官方给的demo Domain（域名系统)，在neo-gui中如何调式demo Domain（域名系统)，在哪里可以看到文档说明，如何部署智能合约，开发文档给的例子上很简单，比如方法要转多个参数、创建集合等，谢谢

**Comment by Ashuaidehao** [comment]
@ly745455 , 对文档的改进建议请到（https://github.com/neo-project/docs）仓库下提issue，我们这边评估后会加进后续的文档中，这里的issue先关掉了，谢谢！
@lock9 can you help to close this ,thanks!
