### ISSUE TITLE
What is the ScriptHash for NKN in the NEO GUI?

### ISSUE THREAD

**Issue by Crypt0Bro** [neo-project/neo-gui#240]

**Comment by miningbadger** [comment]
NKN hash: c36aee199dbba6c3f439983657558cfb67629599
NKN Token - https://www.nkn.org

**Comment by Ashuaidehao** [comment]
Hi  @Crypt0Bro，we're planning to close this issue due to inactivity.
If you still have problems, please reopen this issue or create a new one.
@lock9 can you help to close this ,thanks!
