### ISSUE TITLE
v 2.3.6458.21374 no longer sync

### ISSUE THREAD

**Issue by jaydeeatechs** [neo-project/neo-gui#241]
v. 2.3.6458.21374 does add new blocks but won't download blocks to catch up with the total?  what do i do?  if i need to install a new version, how to i ensure it will restore?  or do i have to start from scratch?

**Comment by fabwa** [comment]
Please consider using a boostrap file from here https://github.com/CityOfZion/awesome-neo#blockchain-bootstrap-files

**Comment by jaydeeatechs** [comment]
thanks. I am running net v. 2.3.6458.21374, however truly i have never known whether it's the neo-gui or the neo-cli (and what's the difference).  i see that both are 2.7.6 now.  how do i know which file to download (there are several files in the bootstrap section) and precisely what to to do with the file once downloaded.  it seems reading the tutorial that i would unzip and save to the neo/chain directory?  but then what?  will neo see it or do i need to open it ...it's not at all clear to me.  Sorry and thanks!

**Comment by Ashuaidehao** [comment]
Hello @jaydeeatechs , is this problem still happen? Did you try to run it using the last version?

**Comment by Ashuaidehao** [comment]
Hi  @jaydeeatechs ，we're planning to close this issue due to inactivity.
If you still have problems, please reopen this issue or create a new one.
@lock9 can you help to close this ,thanks!

**Comment by jaydeeatechs** [comment]
Hi Shine, i hope you and your family are safe and well.

Do you know how to bootstrap while assuring the keys are not lost in the process? I was too concerned i might mess up and so did nothing. If you have a published procedure, could you send it? Do you need my wallet version # to do so?

Thanks you. Take care.

Sent via mobile
