### ISSUE TITLE
contracts compiled with nep8 compiler cannot be evaluated

### ISSUE THREAD

**Issue by ghost** [neo-project/neo-gui#242]
Is there a timeline to have neo-gui updated to use the latest version of neo-vm? Contracts compiled with the nep8 compatible compiler can no longer be used

**Comment by erikzhang** [comment]
See https://github.com/neo-project/neo-compiler/pull/117

**Comment by ghost** [comment]
ah fantastic I hadn't seen that! I'll give it a try - thanks @erikzhang

**Comment by erikzhang** [comment]
Also, I will publish a preview release of gui for TESTNET.

**Comment by ghost** [comment]
closing issue as the branch by @lightszero addresses this concern
