### ISSUE TITLE
missing neo balance

### ISSUE THREAD

**Issue by yura-sutnuk** [neo-project/neo-gui#244]
I requested a test neo, created a contract address and waited for the full synchronization of the wallet, I saw on the balance of the contract address 1 neo and gas (but asked 100), for several days I did nothing with them and when I decided to transfer them to another address I found out that the balance is 0.
What happened?

**Comment by Ashuaidehao** [comment]
Hi @yura-sutnuk ,  is this problem resolved? 
If you just want to apply for test neo and gas , you can use https://neowish.ngd.network .

**Comment by Ashuaidehao** [comment]
Hi  @yura-sutnuk ，we're planning to close this issue due to inactivity.
If you still have problems, please reopen this issue or create a new one.
@lock9 can you help to close this ,thanks!
