### ISSUE TITLE
calculating gas for contract invocation

### ISSUE THREAD

**Issue by ghost** [neo-project/neo-gui#247]
I'm trying to determine if there is an efficient way to calculate the gas requirements of a contract invocation that runs CheckWitness. 

It is easy enough to calculate the actual gas requirement for this contract but becomes significantly more difficult as the contract complexity increases. For the sample contract below:

neo-gui test invocation: Gas Consumed: 1.244
If you comment out the CheckWitness if statement the invocation is correctly calculated at:
neo-gui test invocation: Gas Consumed: 11.054

```
        public static bool Main(string operation)
        {

            Storage.Put(Storage.CurrentContext, "key0", 1);
            if(!Runtime.CheckWitness(new byte[] { 187, 253, 4, 207, 138, 221, 236, 148, 199, 120, 122, 82, 106, 111, 132, 32, 83, 22, 121, 162 } ))
            {
                return false;
            }

            Storage.Put(Storage.CurrentContext, "key1", 1);
            Storage.Put(Storage.CurrentContext, "key2", 1);
            Storage.Put(Storage.CurrentContext, "key3", 1);
            Storage.Put(Storage.CurrentContext, "key4", 1);
            Storage.Put(Storage.CurrentContext, "key5", 1);
            Storage.Put(Storage.CurrentContext, "key6", 1);
            Storage.Put(Storage.CurrentContext, "key7", 1);
            Storage.Put(Storage.CurrentContext, "key8", 1);
            Storage.Put(Storage.CurrentContext, "key9", 1);
            Storage.Put(Storage.CurrentContext, "key10", 1);
            return true;
        }
    }
```

**Comment by Ashuaidehao** [comment]
Hi @birmas , is this problem still troubling you?
When the gui invokes contract for test, it would not add the witnesses.
So in your contract ,"Runtime.CheckWitness" fails then the contract terminates with the wrong gas consume .

**Comment by lock9** [comment]
There is a PR in neo-cli that would allow us to have CheckWitness in RPC endpoints. I think this is a critical issue, however, we don't plan to add new features to neo 2.
