### ISSUE TITLE
Remove Double Check

### ISSUE THREAD

**Issue by Sinepitiss** [neo-project/neo-gui#250]
Neo Gui get asset name in MainForm.Cs with function GetName() defined in Neo.dll ,but before that Checks if the token is GoverningToken or Utility Token ,if so gui names them Neo or NeoGas
                                string asset_name = asset.Asset.AssetType == AssetType.GoverningToken ? "NEO" :
                                                                 asset.Asset.AssetType == AssetType.UtilityToken ? "NeoGas" :
                                                                 asset.Asset.GetName();
but Neo.dll does the same thing 
 public string GetName(CultureInfo culture = null)
        {
            if (AssetType == AssetType.GoverningToken) return "NEO";
            if (AssetType == AssetType.UtilityToken) return "NeoGas";

**Suggestion : Remove the check from neo-gui.**

EDIT:Fixed typos

**Comment by Sinepitiss** [comment]
@erikzhang because you don't want to ,or there is another reason?Or you just don't want to share the reason?

**Comment by Sinepitiss** [comment]
If it's the first ,then I can do it :)

**Comment by erikzhang** [comment]
We are moving to NEO 3.0, so for 2.x we no longer fix non-critical issues.

**Comment by Sinepitiss** [comment]
I see ,so after 3.0 I can make a pull request and make the changes myself ,right?

**Comment by Ashuaidehao** [comment]
@lock9  can we close this issue?
