### ISSUE TITLE
Missing Neo

### ISSUE THREAD

**Issue by kbeanheads** [neo-project/neo-gui#251]
I had neo in a old neo-gui wallet and it stopped syncing at block 2022689. Shortly after my neo and gas disappeared.
Is there a way to find out where my neo went? I do have the keys.
I have downloaded the new version 2.7.6.

**Comment by Sinepitiss** [comment]
This is on mainnet I assume.In neo-gui Right click to the address where your neo and gas were and click "View Contract" there you can copy your address ,open https://neoscan.io in your browser and paste your address in top left corner ,where the search box is and press enter.This should open your address and all transactions

**Comment by kbeanheads** [comment]
Thanks , I can see the neo. Any idea how I can get them into my wallet?

**Comment by Sinepitiss** [comment]
well first thing is: **copy and paste you wallet file somewhere else to back it up** ,this is important!
Now try to open your wallet file with neo gui 2.7.6. and wait for blocks to sync ,if this works thats it.(neo-gui will ask if you wish to update the wallet to newer version)
If this doesn't work however you will need to get you WIFI key by using **older neo-gui** by right-clicking on the address and selecting "**view private key**".After that is done copy **WIFI** option ,then open **neo-gui 2.7.6.** and rightclick on any white space ,select **import** ->**import from WIFI** and paste your WIFI key

**Comment by kbeanheads** [comment]
Many thanks for this.
Will give it a go when the wallet has finished syncing and let you know how I get on.
Cheers

**Comment by Sinepitiss** [comment]
sure ,you can open your wallet without finishing syncing blocks ,if you get past the amount where you were stuck and Neo show up in your wallet ,its all safe.

**Comment by kbeanheads** [comment]
Got me neo back , many thanks pal.

**Comment by Sinepitiss** [comment]
@kbeanheads nice ,if you wish to send some GAS or NEO here is my address AQB51ogTWfrqp1CzJDVXimjVUcSJWzG6z1

**Comment by kbeanheads** [comment]
No worries mate will do later this week

**Comment by kbeanheads** [comment]
Dude, I only have 13 neo , and 1.something gas, don’t get your hopes up for much.

**Comment by Sinepitiss** [comment]
@kbeanheads never did ,as I said:"if you wish"

**Comment by Sinepitiss** [comment]
@erikzhang  I think you can close this

**Comment by Ashuaidehao** [comment]
@lock9 can you help close this issue?
