### ISSUE TITLE
Multi Signature UI does not work

### ISSUE THREAD

**Issue by aaroncatalano** [neo-project/neo-gui#253]
Installed NEO GUI successfully, Added wallet. Fully Synced Testnet blockchain. Modified two json files to point to test net. 

Launch NEO GUI as Admin. After wallet displayed - Right click, Add Multi Signature. Multi Signature UI window displayed.  BUG: ** NEO-GUI does not allow me to update dropdown to 1 or type 1. Cannot paste or type wallet signature into field.  **  What would cause the UI not to work in Multi Signature UI.?

**Comment by aaroncatalano** [comment]
Asking Neo-GUI creators/dev for assistance with issue. Concerns about NEO-GUI wallet stability in making decision to create Dapps on NEO network as opposed to Ethereum.

**Comment by chenzhitong** [comment]
@aaroncatalano  I recorded a video for you, please see this link https://github.com/chenzhitong/Attachment/blob/master/create%20multi%20signature%20address%20via%20neo-gui.mp4

**Comment by Li-Tian** [comment]
@aaroncatalano The video can not display on GitHub but you can download the video provided by chenzhitong and see the short video. What you need to do is as follows.
1. Create two separated public keys and save it somewhere.
2. In the window to create Multi-Signature, paste each public key in the window at the bottom, not the window in the middle.
3. After multiple keys are enlisted, specify the number of keys to required to unlock the address.

**Comment by Ashuaidehao** [comment]
Hello @aaroncatalano , does the video resolve the your problems?

**Comment by Ashuaidehao** [comment]
Hi  @aaroncatalano ，we're planning to close this issue due to inactivity.
If you still have problems, please reopen this issue or create a new one.
@lock9 can you help to close this ,thanks!
