### ISSUE TITLE
NEO-GUI 2.7.6 does not start synchronizing

### ISSUE THREAD

**Issue by Maxim3474** [neo-project/neo-gui#257]
i downloaded NEO-GUI 2.7.6 yesterday(27.08.2018), and yesterday it worked, but today there was all day and night NO synchronization, i am very intrested, what happend with synchronization?

Thanks a lot =)

**Comment by chenzhitong** [comment]
2 ways: 
1、Use offline Sync package [http://sync.ngd.network](http://sync.ngd.network/) To speed up the synchronization.
2、Modify protocal.json to add more seed nodes like this file
[protocol.txt](https://github.com/neo-project/neo-gui/files/2347317/protocol.txt) @Maxim3474
