### ISSUE TITLE
Is it possible to generate and sign an offline standard single-signature transaction using NEO-gui?

### ISSUE THREAD

**Issue by ghost** [neo-project/neo-gui#258]
I see conflicting views on this and have not been able to determine a definitive answer. 

Is it possible to sign a standard single-signature transaction using an offline version of NEO-gui and then relay this to the live blockchain using an online version of NEO-gui? 

I see that some kind of support for multi-signatures was added in #162 but cannot for the life of me figure out how to do it for a standard single-signature transaction.

**Comment by erikzhang** [comment]
I have reopened #4 for this feature.

**Comment by blahd** [comment]
Great, thanks
