### ISSUE TITLE
Error after updating to 2.9

### ISSUE THREAD

**Issue by sempiterna** [neo-project/neo-gui#259]
I just updated my Neo GUI (windows 10) to version 2.9, but i'm receiving the following error:

> System.NotSupportedException
> An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
>    at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
>    at System.Reflection.Assembly.LoadFile(String path)
>    at Neo.Plugins.Plugin.LoadPlugins(NeoSystem system)
>    at Neo.Program.Main()

The 2.7.6 version was working without problems.

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-gui/releases/tag/v2.9.0

I fixed this release and re-uploaded the file. Please try it again.

**Comment by sempiterna** [comment]
I have the same problem using the new release (same error). However, when I extract it using winrar (instead of copy/paste using windows' native zip program) it somehow works. So this probably is not a Neo GUI problem, but more to do with the way it was zipped or how windows own unzip handles this file.

**Comment by mistabowhunta** [comment]
> I have the same problem using the new release (same error). However, when I extract it using winrar (instead of copy/paste using windows' native zip program) it somehow works. So this probably is not a Neo GUI problem, but more to do with the way it was zipped or how windows own unzip handles this file.

@sempiterna I had the same issue unzipping with Windows native unzip program trying to unzip the latest v2.9.0. I then tried unzipping with 7-Zip and it worked. Thanks!
