### ISSUE TITLE
Transfered NEO not showing up in wallet

### ISSUE THREAD

**Issue by iandill** [neo-project/neo-gui#26]
Downloaded and set up NEO-GUI, sent NEO to the wallet from an exchange over three hours ago. Neo tracker says sent. Not showing up in the wallet. Should I wait longer or is there something wrong?
![capture2](https://user-images.githubusercontent.com/30855412/29106457-71252772-7c92-11e7-863a-0f7977532479.JPG)

**Comment by mgao6767** [comment]
Try rebuild index and wait for about 5mins? @iandill

**Comment by erikzhang** [comment]
Did you full sync the wallet?

**Comment by iandill** [comment]
Ok. Thanks. Something has happened since I left this ticket. I went from 1-3 connections to 8 and the height is updating.
I thought I did a full sync, but maybe not?

**Comment by iandill** [comment]
It has been 5 hours since the transaction was initiated and the NEO still isn't visible in my wallet. tried rebuilding the index multiple time. I have restarted multiple times. I'm starting to wonder what to do next.
Can you offer other suggestions? How can I full sync the wallet? Sorry, I'm not very experienced with this.

**Comment by iandill** [comment]
I downloaded NEON and opened my wallet from there. Thanks tho.
