### ISSUE TITLE
Missing Balance using Ledger Nano S with newest OS - HELP WANTED

### ISSUE THREAD

**Issue by GitGonzi** [neo-project/neo-gui#260]
Dear Developer & supporter,

...since update this version Neo GUI v2.9.0 no balance at all displayed, checked newest OS version, changed neo network, refreshing waiting long period but no change, tokens checked with web-neotracker are still there! - thanks for any help!

**Comment by pemila** [comment]
~~I also encountered the same problem~~

**Comment by Ashuaidehao** [comment]
Hello @GitGonzi , is this problem still happen? Did you try to run it using the last version?

**Comment by Ashuaidehao** [comment]
Hi  @GitGonzi ，we're planning to close this issue due to inactivity.
If you still have problems, please reopen this issue or create a new one.
@lock9 can you help to close this ,thanks!
