### ISSUE TITLE
Deploy contract does not work in 2.9.0

### ISSUE THREAD

**Issue by ediopia** [neo-project/neo-gui#261]
**Same avm file that I can deploy in Neo pyhon and previous Neo gui cannot deploy.**

<img width="493" alt="screen shot 2018-09-24 at 7 37 16 am" src="https://user-images.githubusercontent.com/6670368/45958694-f6398b00-bfcc-11e8-95cf-78b816906f0d.png">
<img width="493" alt="screen shot 2018-09-24 at 7 37 26 am" src="https://user-images.githubusercontent.com/6670368/45958695-f6d22180-bfcc-11e8-8bdf-fad42c4cab1a.png">

Invoke button does not active.

**Comment by erikzhang** [comment]
Fixed in https://github.com/neo-project/neo-gui/commit/4798a696f3f952af2ca69c605a33e28757e9a5f2
