### ISSUE TITLE
There exists a 'main' method when invoking contract

### ISSUE THREAD

**Issue by nicolegys** [neo-project/neo-gui#263]
Select Invoke contract, then open an ABI file,  there exists a 'main' in Method.
This may mislead the users.

**Comment by nicolegys** [comment]
<img width="302" alt="1" src="https://user-images.githubusercontent.com/43694095/47422277-d3a9b600-d7b4-11e8-87ae-6e2bb0091829.PNG">

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-gui/blob/a6810512fc46dc42e99ea4d794e0eb3023a3240b/neo-gui/UI/InvokeContractDialog.cs#L177

The latest version has solved this problem.
