### ISSUE TITLE
unable to open neo gui 2.9

### ISSUE THREAD

**Issue by tristri** [neo-project/neo-gui#266]
after update to neo gui 2.9 unable to run neo gui
windows 10 

error log 
System.NotSupportedException
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Neo.Plugins.Plugin.LoadPlugins(NeoSystem system)
   at Neo.Program.Main()

**Comment by Bowserbash** [comment]
This is happening to me as well, from what I know it is the flavour of Windows that you are on, I am on Win 10 Enterprise 10.0.17134. DotNet is baked into the major Windows updates now, (4.7.2). I think the only way to 'revert' back to 4.7.1 is to tamper with the registry. That or can someone explain how to enable that flag 👍  loadFromRemoteSources

My error code as well...
System.NotSupportedException
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Neo.Plugins.Plugin.LoadPlugins(NeoSystem system)
   at Neo.Program.Main()

**Comment by JiniMaster** [comment]
for me, the following helped: just add
`<loadFromRemoteSources enabled="true"/>`
to your neo-gui.exe.config
right after the `<runtime>` tag, like:
```
<configuration>
...
    <runtime>
        <loadFromRemoteSources enabled="true"/>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
```
...then restart neo-gui.exe!

**Comment by tristri** [comment]
> for me, the following helped: just add
> `<loadFromRemoteSources enabled="true"/>`
> to your neo-gui.exe.config
> right after the `<runtime>` tag, like:
> 
> ```
> <configuration>
> ...
>     <runtime>
>         <loadFromRemoteSources enabled="true"/>
>         <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
> ```
> ...then restart neo-gui.exe!

it works !! but is it safe to mess with config file ... ?

**Comment by Ashuaidehao** [comment]
@lock9 can you help to close this issue?
