### ISSUE TITLE
Neo GUI is not sync the new blocks 

### ISSUE THREAD

**Issue by BowscoinBSC** [neo-project/neo-gui#268]
Neo-GUI v2.9.0 is not sync new blocks nodes are also connected wallet open perfectly but block sync is not working

**Comment by topannuity** [comment]
NEO version 2.7.6744, Height 2919042, Connected 16, Not updating blocks. I've tried for 3 days now, no movement. please help.

**Comment by Ashuaidehao** [comment]
Hi @BowscoinBSC @topannuity , do you still trouble in this problem?

**Comment by topannuity** [comment]
Okay right now. I downloaded the archived patch and after unpacking for 3 days everything works now as long as I open neo-gui at least once a day. Problem happens when I don’t update for a week or more then it won’t update even though I’m connected with 10+ connections.

**Comment by lock9** [comment]
I'm very sorry to inform that this won't be fixed now, only in our next neo-gui version.
We are sorry for the problems caused @topannuity, but we are focused in NEO 3 and won't be able to fix this in the next weeks.
Thank you for understanding, I have to close this because it won't be fixed 😢
