### ISSUE TITLE
Root Cert with unrestricted purposes Explanation?

### ISSUE THREAD

**Issue by nshCore** [neo-project/neo-gui#27]
Can I get an explanation why this program needs to have a root CA installed with unrestricted purposes? There is zero reason Neo needs to be installing a root CA like this on my machine it is exposing a lot of people to a security risk

**Comment by erikzhang** [comment]
It is prepared for NeoID and, yes, it's unnecessary. You can click "NO" when it asks for the installation.

**Comment by erikzhang** [comment]
Fixed in 815cb8645469b70b5230984f4aee457e20ff1ac5
