### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by wizardofwhere1** [neo-project/neo-gui#270]
HI 
I tried to install the neo-gui and the error log shows this: System.NotSupportedException An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information. at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence) at System.Reflection.Assembly.LoadFile(String path) at Neo.Plugins.Plugin.LoadPlugins(NeoSystem system) at Neo.Program.Main() 
How do I fix this so the client will run? Thx

**Comment by wizardofwhere1** [comment]
I think I figured it out https://github.com/neo-project/neo-gui/issues/259

**Comment by Ashuaidehao** [comment]
@lock9 could you help close this issue? Seems it was resolved.

**Comment by shargon** [comment]
Solved
