### ISSUE TITLE
部署合约出现合约执行遇到错误，并退出“”

### ISSUE THREAD

**Issue by cayden** [neo-project/neo-gui#273]
Hi, 
  我在使用neo-gui 往我的私有链部署智能合约出现如图所示的异常
![avatar](https://github.com/cayden/tfdemo/blob/master/test.png?raw=true)

我的智能合约如下
`using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;
using System;
using System.Numerics;

namespace NeoContract1
{
    public class Contract1 : SmartContract
    {
        public static bool Main(int a, bool b)
        {

            return b;
        }
    }
}
`

**Comment by chenzhitong** [comment]
这是 neo-gui 的 Bug，目前发布智能合约会报错，跟私有链无关。

**Comment by cayden** [comment]
> 这是 neo-gui 的 Bug，目前发布智能合约会报错，跟私有链无关。

嗯 非常感谢回复，后来我使用了neo-gui-develop版本，没问题了

**Comment by alibugra** [comment]
Hi,

Any neo-gui without bug to download?

**Comment by Ashuaidehao** [comment]
@lock9 this issue can be closed.

**Comment by shargon** [comment]
Feel free to open if is not solved
