### ISSUE TITLE
wallet sync progress stuck at height 3506122

### ISSUE THREAD

**Issue by raymanyoung** [neo-project/neo-gui#277]
I am using NEO-GUI 2.9.0. Downloaded the bootstrap data file (1st May). After about 24 hours the block data sync-ed to the latest height, and I was trying to open my wallet. 
The sync of wallet data stuck at height 3506122. I have tried to rebuild the index, and delete the index folder but it repeated at same height, even I create a new address.

**Comment by raymanyoung** [comment]
I deleted the chain data and re-synced. Now the problem is gone. 
I recalled that in the middle of sync I tried to rename the offline-sync data filename (the file name downloaded is different from the documentation so I was not sure which one is the correct one). Maybe the chain data was corrupted at that time.

**Comment by shargon** [comment]
Did you compare both files?

**Comment by Ashuaidehao** [comment]
Hi @raymanyoung ,is this problem resolved?

**Comment by shargon** [comment]
Closed because we have no answer since May.
