### ISSUE TITLE
execution terminated in fault state - the invoke button does not work

### ISSUE THREAD

**Issue by federicamatteucci02** [neo-project/neo-gui#278]
Hi, can anyone tell me why I have this error?
![Cattura](https://user-images.githubusercontent.com/49142827/57864324-f86e8500-77fb-11e9-91f8-c53fabd609f5.PNG)

**Comment by shargon** [comment]
Could you copy the script value as text? is not possible to help you without this information

**Comment by federicamatteucci02** [comment]
what you mean with the script value as text? this?
![Cattura2](https://user-images.githubusercontent.com/49142827/57865010-20aab380-77fd-11e9-9fbe-684adcce3fe7.PNG)

**Comment by shargon** [comment]
Your script, in hexadecimal value.. `0b68...`

**Comment by federicamatteucci02** [comment]
this? 
016101610161016101615102ff00004c5a53c56b6c766b00527ac46c766b51527ac4610548656c6c6f05576f726c64617c68164e656f2e53746f726167652e476574436f6e74657874680f4e656f2e53746f726167652e50757461516a52527ac46203006a52c3616c756668134e656f2e436f6e74726163742e437265617465

![Cattura6](https://user-images.githubusercontent.com/49142827/57908464-504ecf80-7880-11e9-82b8-0ad9fc7d3d03.PNG)

**Comment by shargon** [comment]
Is a contract create?

**Comment by shargon** [comment]
What did you put in your contract parameter list and contract return type? looks weird 
![image](https://user-images.githubusercontent.com/3167973/57913967-0b319a00-788e-11e9-8119-e76ae71ee15d.png)

All information that you can provide, is useful for speed up the resolution of the issue.

**Comment by federicamatteucci02** [comment]
Hi, I'm not understanding what you're talking about!
I followed this guide (https://medium.com/coinmonks/neo-smart-contract-development-part-9-5c36b765014d) to create my first contract. When I get to the "Import the existing Developer account from the NEO privatenet Docker container" section I can't click "invoke". I HAVE CARRIED OUT THAT GUIDE STEP BY STEP.

**Comment by shargon** [comment]
![image](https://user-images.githubusercontent.com/3167973/57914783-a5dea880-788f-11e9-8805-36e365442d7c.png)

this is wrong, you need to provide the same type as your smart contract, in your comment https://github.com/neo-project/neo-gui/issues/278#issuecomment-493107531 you show that your return is bool (`01`) and your parameter list string and array(`0510`)

acording to https://docs.neo.org/en-us/sc/Parameter.html

Try with these values please

**Comment by federicamatteucci02** [comment]
I tried to set the parameters but it always gives me the same error. I tried to modify the code

````
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;
using System;
using System.Numerics;

namespace NeoContract1
{
    public class Contract1 : SmartContract
    {
        public static void Main()
        {
            Storage.Put("Hello", "World");
            
        }
    }
}
`




 by removing the parameters but the error persists. I can't understand what's wrong!

**Comment by federicamatteucci02** [comment]
I tried to set the parameters but it always gives me the same error. I tried to modify the code 
 by removing the parameters but the error persists. I can't understand what's wrong!

using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;
using System;
using System.Numerics;

namespace NeoContract1
{
    public class Contract1 : SmartContract
    {
        public static void Main()
        {
            Storage.Put("Hello", "World");
            
        }
    }
}
`

**Comment by federicamatteucci02** [comment]
I tried to set the parameters but it always gives me the same error. I tried to modify the code by removing the parameters but the error persists. I can't understand what's wrong!

```
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;
using System;
using System.Numerics;

namespace NeoContract1
{
    public class Contract1 : SmartContract
    {
        public static void Main()
        {
            Storage.Put("Hello", "World");
            
        }
    }
}
```

**Comment by hal0x2328** [comment]
The bug causing the contract deployment to fail was fixed some time ago here: https://github.com/neo-project/neo-gui/commit/4798a696f3f952af2ca69c605a33e28757e9a5f2

The problem is there hasn't been a new release build since then.

**Comment by Ashuaidehao** [comment]
Hi  @federicamatteucci02 ,is this problem still happen using the last gui version?

**Comment by Ashuaidehao** [comment]
Hi  @federicamatteucci02 ，we're planning to close this issue due to inactivity.
If you still have problems, please reopen this issue or create a new one.
@lock9 can you help to close this ,thanks!
