### ISSUE TITLE
Block Height stuck, want to move funds to new wallet and claim GAS and ONT

### ISSUE THREAD

**Issue by JamesB1985** [neo-project/neo-gui#279]
Can i please get help.... When using the neo-gui its stuck at block Height 2394985, I want to move funds to new wallet and claim the GAS and ONT..etc .....Can someone please help me or list steps required to take to resolve this issue. Thank you

**Comment by Ashuaidehao** [comment]
@JamesB1985 ,is this problem still happen? 
Did you try to full resync blocks using quick sync method(https://docs.neo.org/en-us/network/syncblocks.html)?

**Comment by JamesB1985** [comment]
Yes still a problem so I just used the neon wallet  to gain access to my wallet instead

Sent from my iPhone

On 16 Jul 2019, at 5:01 pm, Shine Li <notifications@github.com<mailto:notifications@github.com>> wrote:


@JamesB1985<https://github.com/JamesB1985> ,is this problem still happen?
Did you try to full resync blocks using quick sync method(https://docs.neo.org/en-us/network/syncblocks.html)?

**Comment by longfeiWan9** [comment]
@lock9 I think we might be able to close this issue, right ?
