### ISSUE TITLE
Unconfirmed transfer from antshares core wallet

### ISSUE THREAD

**Issue by silverhousehd** [neo-project/neo-gui#28]
hi guys,

i did a transfer on aug 8 from the core wallet to bittrex during the update phase. transaction does show in antchain.xyz so I want to know if the ans I sent is lost?

TXID: 17a4d2b0db8098bf10801a372dce676b4f8a2a3a12b68595b555ebb5445fabf8

thanks in advance

**Comment by erikzhang** [comment]
The problem seems to have been solved.
