### ISSUE TITLE
Old wallet file not working

### ISSUE THREAD

**Issue by MarianPole** [neo-project/neo-gui#280]
Last time i logged into my wallet was august 2017. I have a file for my neo wallet with the master key and encrypted key inside. I used to just login with this file. 
Does someone know how I can get into my wallet with this?

**Comment by shargon** [comment]
If you have any compatibility problem, you can use the client for this date, and extract the private key. you have all the releases in the release tab

**Comment by MaximePanta** [comment]
Hi guys @shargon @MarianPole ,
Hope you are doing great !
May I ask you how did you solve the issue with the neo wallet, as I have the exact same issue at the moment. When you could help me with this would be awesome !!!!

**Comment by lock9** [comment]
@MaximePanta  use this release: https://github.com/neo-project/neo-gui/releases/download/v2.0.2/neo-gui-windows.zip
But careful: this is an old version. Try to retrieve your keys and use a more updated version to perform transfers.
