### ISSUE TITLE
I find a bug in neo clint wallat 

### ISSUE THREAD

**Issue by noreen621** [neo-project/neo-gui#281]
Hi sir i find a bug in neo clint wallat i find it on web that is very bad for your coin i think if i tell u this then u should give me a rewad of neo coins please answer me for information of neo coin bug

**Comment by shargon** [comment]
You can find the details of security bounties here https://neo.org/dev/bounty

**Comment by vncoelho** [comment]
What the **** is this issue? kkkkkk heuaahhsheua jajaja
Man, people are insany...I did not understand nothing.

**Comment by noreen621** [comment]
The issue is this we know that neo has a separate  blockchain and ether has
a separate  blockchain but when we enter ether private key into neo wallat
the wallat  will be created .And the other blockchain like ether wallat
cannot open like this but neo wallat open in the ether private key but the
neo has a different  blockchain than ether but it open and create the ether
private key wallat but in the case of ether you cannot open the wallat or
creat the wallat by using neo privite key.
Please check this first take myetherwallat or any ether private key and
then go to neowallat and enter private key and open wallat the wallat will
be open but the key is ether not neo private key .
And give me my reward for this thanks
*AHumBLrnSVx6gVXDMGcktkDvWxzVokwdBm this is my neo adress *

*AHumBLrnSVx6gVXDMGcktkDvWxzVokwdBm*

**Comment by noreen621** [comment]
Asset - What software asset the vulnerability is related to  Neo Clint wallat

Severity - Your opinion on the severity of the issue   high
Summary - Every blockchain is secure due to their own adressess and private keys but if some other private key in use your blockchain then the blockchain is not secure and this is dangerous for the neo smart economy 
Description - The issue is this we know that neo has a separate blockchain and ether has a separate blockchain but when we enter ether private key into neo wallat the wallat will be created .And the other blockchain like ether wallat cannot open like this but neo wallat open in the ether private key but the neo has a different blockchain than ether but it open and create the ether private key wallat but in the case of ether you cannot open the wallat or creat the wallat by using neo privite key. Please check this first take myetherwallat or any ether private key and then go to neowallat and enter private key and open wallat the wallat will be open but the key is ether not neo private key .
Steps - You should just finish all the otje otjer private keys access like ether to improve the protection of neo coin and the security of the neo coin infuture this impact very badly in neo coin so please make it secure that no one can access  it by using other private  keys except  neo private key 
Supporting Material/References - Source code to replicate, list any additional material (e.g. screenshots, logs, etc.)
Impact - What security impact could an attacker achieve?
Slow down the neo blockchain by using other private keys 
Your name and country. Umair Farooq Pakistan
Rewards send reward to this neo adress AHumBLrnSVx6gVXDMGcktkDvWxzVokwdBm

**Comment by shargon** [comment]
try harder

**Comment by noreen621** [comment]
Why the ether key working in neo open wallat i dont know what is the reason behind this please check it and also try mew by using neo private key it will not work you should change the settings that just neo keys working  other key not open in your wallats

**Comment by noreen621** [comment]
I try harder for this if some one  tell u a thing about your coin then you should give them some reward then he find more things like this give me some reward for this  
 AHumBLrnSVx6gVXDMGcktkDvWxzVokwdBm

**Comment by vncoelho** [comment]
@noreen621, with all my respect, you should learn the basics of crypto and digital signatures.
Take some time to read on wikepedia or a specific book, you gonna thank us in the future.

Issues like this consumes our time. Please, avoid to open issues before getting familiarized with the concepts.
However, fell free to ask any question.

Closed.
