### ISSUE TITLE
Better if I can choose a change address when claiming gas

### ISSUE THREAD

**Issue by nicolegys** [neo-project/neo-gui#282]
I claimed gas from a multisigaddress, then the gas appeared in my first standard address.

some neo in the multisigaddress:
<img width="679" alt="beforesend" src="https://user-images.githubusercontent.com/43694095/58947294-3424bb00-87ba-11e9-8c8e-78715bab0cdb.png">

make the gas available:
<img width="679" alt="beforeclaim" src="https://user-images.githubusercontent.com/43694095/58947302-38e96f00-87ba-11e9-9617-e725edc88825.png">

claim gas, but cannot choose a change address:
<img width="677" alt="nowclaim" src="https://user-images.githubusercontent.com/43694095/58947326-430b6d80-87ba-11e9-9fa3-5c61eaf5d1cb.png">

sign:
<img width="676" alt="beforesign" src="https://user-images.githubusercontent.com/43694095/58947328-469ef480-87ba-11e9-99b6-3f21e0ff9880.png">

all gas appear in my first standard address:
<img width="679" alt="afterclaim" src="https://user-images.githubusercontent.com/43694095/58947336-49014e80-87ba-11e9-8b67-53433c1e7616.png">

I hope I can choose a change address, so that the gas could appear in the multisigaddress.

**Comment by superboyiii** [comment]
Need improvement for product design. We'll do this soon.

**Comment by Lichen9618** [comment]
[https://github.com/Lichen9618/neo-gui/tree/Update](url)
I will try to enhance this feature
