### ISSUE TITLE
Leveldb Assertion failed

### ISSUE THREAD

**Issue by IprelProgetti** [neo-project/neo-gui#287]
![Capture](https://user-images.githubusercontent.com/47773901/60872024-3b653b80-a234-11e9-9cd6-6b70f7944125.PNG)

While syncing neo-gui v.2.10.7123.28849 on the testnet, leveldb crashes with the attached error.

It seems to happen randomly, not on a specific block. In my case, it happened at block 404026.

Do you know how to solve that? Thanks.

**Comment by lock9** [comment]
Hi @IprelProgetti, 
Could you say the OS you are using?
Are you compiling from source or using a release (I didn't find a release with version 2.10)?
Do you know if this problem happens with the latest release? (2.9)

**Comment by IprelProgetti** [comment]
Hi @lock9 ,
I am using Win10 on a MacBook Pro via bootcamp.
I compiled the gui from the source code on the master branch.
The latest release (2.9) had the same problem on my laptop.

I think I have the same problem of #264

**Comment by lock9** [comment]
Hi @IprelProgetti, we will take a look. I will close this one and update #264 instead. Thank you for reporting.
