### ISSUE TITLE
NEO-GUI keeps crashing on Windows 8.1 

### ISSUE THREAD

**Issue by jaykp** [neo-project/neo-gui#29]
Crashes every few mins - was a new install of Windows 8.1

  Problem Event Name:	APPCRASH
  Application Name:	neo-gui.exe
  Application Version:	2.0.6411.26926
  Application Timestamp:	5971a5de
  Fault Module Name:	StackHash_e20c
  Fault Module Version:	6.3.9600.17415
  Fault Module Timestamp:	5450559e
  Exception Code:	c0000374
  Exception Offset:	PCH_0F_FROM_ntdll+0x00000000000911FA
  OS Version:	6.3.9600.2.0.0.256.4
  Locale ID:	1033
  Additional Information 1:	e20c
  Additional Information 2:	e20ce74b268616e84416d73bec7af208
  Additional Information 3:	dcd9
  Additional Information 4:	dcd98d741558b10c330f458b4d8a94c3

Any ideas how I can address this?

**Comment by erikzhang** [comment]
please upload the error.log
