### ISSUE TITLE
gui连接远程私链会异常

### ISSUE THREAD

**Issue by boy-good** [neo-project/neo-gui#290]

**Comment by boy-good** [comment]
![捕获](https://user-images.githubusercontent.com/39320533/61100241-fe00e800-a497-11e9-9804-69e385cd642d.PNG)

**Comment by boy-good** [comment]
@erikzhang 是我的配置有问题还是呢，我现在在linux上运行私链，但不通过GUI的话不知道怎么获取到NEO代币

**Comment by boy-good** [comment]
************** 异常文本 **************
System.ArgumentOutOfRangeException: “16”的值对于“Value”无效。“Value”应介于 'minimum' 和 'maximum' 之间。
参数名: Value
   在 System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   在 Neo.UI.MainForm.timer1_Tick(Object sender, EventArgs e)
   在 System.Windows.Forms.Timer.OnTick(EventArgs e)
   在 System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by boy-good** [comment]
@shargon hello, when i can use the Fixed version? or how to do Avoid appearing？

**Comment by shargon** [comment]
If you are dev, you can compile this branch, but if not you need to wait for a release

**Comment by Ashuaidehao** [comment]
@boy-good 可以发下你搭建私链时配置的出块时间间隔吗？在protocol.json里的SecondsPerBlock的值。这个值目前不建议超过15，否则容易触发一个winform的UI控件的异常。
gui短时间内不会release新版，你可以用上面提到的分支签出代码本地编译一个不报错的版本出来。

**Comment by boy-good** [comment]
> @boy-good 可以发下你搭建私链时配置的出块时间间隔吗？在protocol.json里的SecondsPerBlock的值。这个值目前不建议超过15，否则容易触发一个winform的UI控件的异常。
> gui短时间内不会release新版，你可以用上面提到的分支签出代码本地编译一个不报错的版本出来。

确实是因为我的出块时间设置超过了15秒导致的。
