### ISSUE TITLE
Neo-GUI Unhandled Exception on Windows 10

### ISSUE THREAD

**Issue by ghost** [neo-project/neo-gui#30]
Hi,

I am using Windows 10 w/ latest updates. When opening Neo-GUI, the Height syncs as normal. As soon as I open an Antshare/NEO wallet and authenticate, this Unhandled Exception appears. Clicking Continue immediately repeats the same dialog box. The only "fix" is to close the application.

Here's the error:
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Value does not fall within the expected range.
   at Neo.Core.Blockchain.CalculateBonus(IEnumerable`1 inputs, UInt32 height_end)
   at Neo.UI.MainForm.timer1_Tick(Object sender, EventArgs e) in C:\Users\erik\Documents\Visual Studio 2017\Projects\neo-gui\neo-gui\UI\MainForm.cs:line 305
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![image](https://user-images.githubusercontent.com/30881422/29148262-dcf03d12-7d31-11e7-9565-d11b37729352.png)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
neo-gui
    Assembly Version: 2.0.6411.26926
    Win32 Version: 2.0.6411.26926
    CodeBase: file:///C:/neo-gui-windows/Neo/neo-gui.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2104.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2103.2 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST`

**Comment by erikzhang** [comment]
see #21

**Comment by ghost** [comment]
Unhandled Exception goes away once the blockchain is fully synced. This may still be a bug as adding the wallet prior to complete sync shouldn't throw an error.

**Comment by erikzhang** [comment]
Fixed in 815cb8645469b70b5230984f4aee457e20ff1ac5

**Comment by jzairick** [comment]
Hello everyone, I need a little help. I just installed Virtualbox on my Mac and installed NEO-GUI and once I try to create a new wallet it give me a similar error “Unhandled exception has occurred in your application. If you click Continue , the application will ignore this error ...” “Exception has been thrown by the target of an invocation”.

Please help me.

**Comment by davidstroukbn** [comment]
@donkeykonghunter even with the blockchain fully synced I'm getting the "Unhandled exception has occured in your application" error.

<img width="453" alt="screen shot 2018-06-21 at 10 13 00" src="https://user-images.githubusercontent.com/40020736/41703370-b5c79746-753b-11e8-8619-9d7578800148.png">

Can someone pls help me?

*edit* : this has been solved by installing Microsoft Visual Studio C++ (issue #118)
