### ISSUE TITLE
Synchronizing problem NEO-GUI still persistent. No matter what I tried.

### ISSUE THREAD

**Issue by nachtmens** [neo-project/neo-gui#300]
After a long time I decided to pay attention to my stacked Neo's.
So I downloaded the NEO-GUI 2.7. Indeed I did run into the problems as described in jrsikors comments #219 refering to A),B), C) and D). After a (indeed) frustrating proces I got the NEO-Gui syncing.
At the first attempt got stuck around about block height 3203303 or something close. At the second 
attempt got stuck at Block height 3773043.

Then did a new fresh start with NEO-GUI 2.10.7167.31939, and now I seem be stuck at 
Block height 3773043 again. "seem" because the synchronized wallet blockchain height is 
still catching up. But the wallet does not receive new blocks anymore since more than 8 hours.

Considerations:
A) I used the latest NEO-GUI.exe
B) Before installing, deleted the former NEO-GUI map, so completely fresh.
C) I made sure that I used the latest ImportBlocks Plugin.
D) I made sure that I used the latest Full Offline Package.
E) Did not unzip chain.acc.zip .
F) Did not put chain.acc.zip in Chain_xxxx folder
G) peers.dat nowhere to find when looking for it to delete.
H) Restarting NEO-GUI does not help.
I) At time of writing connected to 40 nodes.

For me its hard to believe that this issue has no more follow ups since march 2018.
This problem is a harsh reality for me and very real. I am talking about 18 August 2019 and NEO-GUI 2.10.7167.31939 here . What is going on? Or is everybody after making those failed attempts using a light wallet? That's not good for the long term for Neo.

Please help

**Comment by nachtmens** [comment]
Update;
I made another attempt, and this time it seems with succes. I did not start all over again by reinstalling Neo-GUI or replacing the rootfolder . The Neo-Gui keeps up now pretty good with displaying the pace of new blocks, and the wallet blockchain sync is catching up, now at about 60 percent at time of writing. I removed the Chain_xxxx folder, started the sync proces again. Did not replace the chain.acc.zip file this time, because that made no sense to me, because there was no a more recent one at the https://sync.ngd.network/ site at that time.

As I look back now, I think the whole issue is not just the misunderstanding #219 of the installation proces, but also problems with the quality of the Blockchain network. I think this problem could put off a whole lot of users who want to install a full node. Think about it, you have to go through dissapointment repeatedly, that gets deeper with each failure, in my case also with rage and dispair, because it took a long time to get it right, and  there is nobody helping you within an acceptable timeframe. The subject is hard to find on the internet, no helpdesk, all time consuming, you are alone. So its quite a feat if you made it landing here. Like trying to make a save landing with a burning plane. The flying plane is your hope and rage, and the fire is your dispair.

So if you are still really determined to go on, I hope this will help you.

**Comment by shargon** [comment]
Maybe we should ban the hashes of the previous forks that could stuck a new node?

**Comment by nachtmens** [comment]
> 
> 
> Maybe we should ban the hashes of the previous forks that could stuck a new node?

Ah, I see.
 No, what I mean is de _quality_ of the Neo Blockcain in _particular_ as it is now.
I did not expirience this problem with some other crypto's that I favor as much too.

**Comment by shargon** [comment]
It could be related to https://github.com/neo-project/neo/issues/924 ?

**Comment by nachtmens** [comment]
> 
> 
> It could be related to [neo-project/neo#924](https://github.com/neo-project/neo/issues/924) ?

Just took a look at  [neo-project/neo#924](https://github.com/neo-project/neo/issues/924) .
I think yes. Maybe funny, it took me also three times.

**Comment by longfeiWan9** [comment]
Thanks, @shargon .

Hi, @lock9 I think we can close this issue since it is related to a temp fork.
