### ISSUE TITLE
打开钱包失败，提示缺少依赖项

### ISSUE THREAD

**Issue by liuyuduen** [neo-project/neo-gui#301]
未能加载文件或程序集“Replicon.Cryptography.SCrypt.MMA.dll”或它的某一个依赖项。找不到指定的模块。
neo-gui根目录 只有Replicon.Cryptography.SCrypt.dll
没有Replicon.Cryptography.SCrypt.MMA.dll
下载源码重新编译也没有 怎么解决

**Comment by VVanaheim** [comment]
换个稳定好用的钱包吧，优盾钱包就挺好用的，有个人版本和交易所版本
