### ISSUE TITLE
Import WIF private key

### ISSUE THREAD

**Issue by ravetroll** [neo-project/neo-gui#304]
I can't seem to find a way to convert my private key into a WIF format private key that is compatible to be imported into NEO GUI 'Import from WIF'.  At least that is what I think I need to do, perhaps I misunderstand?

**Comment by erikzhang** [comment]
Right click an address, then click `Show private key`.

**Comment by ravetroll** [comment]
You can see that for an address already imported.  I could import a 'Watch-Only Address' using just the address.  How can I import other 'Standard Account' using 'Import from WIF' if I don't know the WIF of that other account, only the private key?

**Comment by longfeiWan9** [comment]
Do you still have your wallet json file ?

**Comment by ravetroll** [comment]
I have a wallet.json file set up for an address.  I created another address via neotracker.io and I want to see that in the client

**Comment by longfeiWan9** [comment]
The private key you can get from neotracker.io is already WIF format. You can directly use to import from neo-gui with an opened wallet. 

Then you address will be imported into the opened wallet

**Comment by ravetroll** [comment]
Thankyou I now get it.  The private key you use in Neotracker.io to open your wallet is different to the private key you see displayed in neotracker.io once you have opened the wallet in neotracker.io.  What is the difference between those as they both seem to be called the private key but they are different.  The one I was using before was the one that required a password to open the wallet, so perhaps it is a private key encrypted with the password?

**Comment by longfeiWan9** [comment]
@ravetroll Normally, private key is not encrypted, and it could be used to open a wallet directly. I think the one you used along with password to open a wallet is encrypted key (PrivateKey +password). And wif is the encoded private key. For example:
+ Private Key (hexstring): `c7134d6fd8e73d819e82755c64c93788d8db0961929e025a53363c4cc02a6962`
+ WIF: `L3tgppXLgdaeqSGSFw1Go3skBiy8vQAM7YMXvTHsKQtE16PBncSU`
