### ISSUE TITLE
Creating transactions with same hash and no signature

### ISSUE THREAD

**Issue by joeqian10** [neo-project/neo-gui#305]
Some exchanges and some developers have reported this issue: when they invoke the same method in the same smart contract multiple times and neo-gui create invocation transactions under 10 gas free limit, these transactions will have the same hash and have no signatures, which causes these txs are never confirmed. 

A temporary solution I provided to them is adding the timestamp and the first address in neo-gui in the transaction attributes. 

We need a permanent fix for this issue. Any suggestion is welcome.

**Comment by shargon** [comment]
No different Inputs? SmartContract transactions?

**Comment by longfeiWan9** [comment]
There are two issues:
+ **Add an nonce attribute when creating tx**
there is no nonce for transaction for NEO 2.x. So when projects uses neo-gui to invoke smart contract transactions for the same params without inputs. Only the first transaction will be accepted. So we need to add a timestamp as nonce to distinguish them. 

+ **Add signature when there is no input for certain tx**
Currently, gui does not sign a tx without input and output. But in some cases,  smart contract will have verification trigger logic to check witness. So neo-gui should be able to support that.

**Comment by shargon** [comment]
> there is no nonce for transaction for NEO 2.x

There was, but only for transfers https://github.com/neo-project/neo/pull/1184/files#diff-3f891451d2176ac40781e3bde8ad50c2L350-L352

**Comment by shargon** [comment]
@joeqian10 Please test https://github.com/neo-project/neo/pull/1184 for the first issue

**Comment by shargon** [comment]
@joeqian10 any news?

**Comment by joeqian10** [comment]
@shargon The first issue has been fixed.

**Comment by longfeiWan9** [comment]
hi, @shargon . Thank you for fixing the first issue. 

Recently, I have got some projects who is asking why invoking smart contract in neo-gui will not work. It is related to the second issue that Joe mentioned. I think it is necessary to fix this issue so that developers can use neo-gui properly. 

Probably @Lichen9618 can help to fix it and submit a PR.
