### ISSUE TITLE
neo-gui unconfirmed ContractTransaction

### ISSUE THREAD

**Issue by uberlance** [neo-project/neo-gui#31]
While the behavior may be a duplicate of Issue #28 , I am including additional information regarding the environment and behavior.

Having waited a few days before switching wallets from the AntSharesCore wallet to the NEO wallet, here are the steps that led to the current issue:
1. Downloaded and extracted neo-gui version 2.0.6411.26926.
2. Copied the Chain directory from my AntSharesCore directory to the neo directory.
3. Launched the neo-gui executable and waited until the chain had synced completely.
4. Opened and unlocked my existing wallet database.
5. Successfully transferred all my NEO back to myself (same address via ContractTransaction) in order to allow AntCoin/NeoCoin to be claimed.
6. Successfully completed a ClaimTransaction.
7. Successfully completed a ContractTransaction sending 1 NEO to an exchange (Bittrex).
8. Created a ContractTransaction sending additional NEO to the same exchange address used in the prior transaction and the transaction shows Unconfirmed in the Transaction History.  Checking the blockchain with several explorer websites, this transaction does not appear to have been fully submitted (TXID b1b194e9eba2c72a6c41120b368531d0c7d53f00ec4684fca2e6b10e16961e82).
9. After waiting an hour and confirming the chain was fully synched locally, I ran a Wallet-Rebuild Index.
10. After the Rebuild Index completed, I successfully completed an additional ClaimTransaction.  The ContractTransaction in step 8 still shows Unconfirmed.

Platform is Windows 7 Enterprise SP1 with all current patches.

My concern is whether this ContractTransaction is what the future behavior of this ContractTransaction will be.  Will it eventually appear on the blockchain?  Is there a way to revoke it as it appears to have not actually been submitted?  I want to avoid a duplicate transaction and the Gas/Exchange fees associated with it.

**Comment by erikzhang** [comment]
You need to wait for at least one confirmation before sending new transaction.

**Comment by uberlance** [comment]
thank you for the clarification.  As the transaction in question has been followed by multiple successful transactions, I can treat it as "abandoned".   If so, then this issue can be closed.

**Comment by erikzhang** [comment]
Yes, you can click the "rebuild index" button and wait for 10~30 minutes to remove to unconfirmed transactions.

**Comment by mehmetdogu** [comment]
URGENT!
Someone just moved all my NEO coins from my wallet and the transaction hasn`t been completed yet.

HOW CAN I CANCEL THE TRANSACTION AND SEND THE COINS TO SOMEWHERE ELSE? 

PLEASE HELP AS SOON AS POSSIBLE!
