### ISSUE TITLE
Provide cryptographic signatures for all builds 

### ISSUE THREAD

**Issue by ghost** [neo-project/neo-gui#35]
This is so that users can validate the integrity of their downloads, and protect themselves against their tokens and wallet being stolen. Ideally, provide gpg signatures for all builds.

**Comment by erikzhang** [comment]
Added file hashes in release page.
https://github.com/neo-project/neo-gui/releases/tag/v2.0.2

**Comment by ghost** [comment]
Would you also be open to the possibility of adding PGP signatures?

**Comment by erikzhang** [comment]
@chenzhitong Can you look into it?
