### ISSUE TITLE
Doesn't import into neo-gui wallet.

### ISSUE THREAD

**Issue by il4real** [neo-project/neo-gui#37]
Hey guys, when i bought my first NEO i created wallet in Neon. Then I downloaded neo-gui (with all blockchain as well) and wanted to import my wallet there through WIF. Address appeared on Account page, but it shows no NEO or NeoGas on it, but actually there is (as I can see through Neon wallet)

**Comment by erikzhang** [comment]
Click the "rebuild index" button and wait for 15~30 minutes. Then your NEO and GAS will appear.
