### ISSUE TITLE
Compatibility Issue with Windows 10

### ISSUE THREAD

**Issue by izzys36** [neo-project/neo-gui#44]
Hi. i downloaded the NEO GUI v2.2 . it starts to sync then keeps crashing. this is the error message. Please Help??

Neo.Implementations.Blockchains.LevelDB.LevelDBException
Corruption: 84 missing files; e.g.: Chain/011458.ldb
   at Neo.Implementations.Blockchains.LevelDB.NativeHelper.CheckError(IntPtr error)
   at Neo.Implementations.Blockchains.LevelDB.DB.Open(String name, Options options)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main() in C:\Users\erik\Documents\Visual Studio 2017\Projects\neo-gui\neo-gui\Program.cs:line 121

**Comment by erikzhang** [comment]
Try to delete the "Chain" directory and restart the program.

**Comment by izzys36** [comment]
Erik,

Thanks for your response. I am not tech savvy, would toy be able to kindly
direct how I do that. In what file is the directory??

I truly appreciate your help.

Regards

Izzy s

**Comment by erikzhang** [comment]
![image](https://user-images.githubusercontent.com/10204923/29621157-8b2fd236-8852-11e7-9b5c-e0ea70731dff.png)

**Comment by izzys36** [comment]
Erik,

Thanks so much for your help. Will try it out after work.

Wishing you all the best and lots of success. Go Neo

Regards

Izzy s

**Comment by izzys36** [comment]
Erik,

I tried following your instructions, however there is no file called
"CHAIN" OR "Certs" only the other ones on your template. Kindly advise.

Thanks again

Izzy s

**Comment by izzys36** [comment]
![20170823_181646](https://user-images.githubusercontent.com/31259442/29629192-d3c0a1d8-882f-11e7-9c91-8acbbc4838cf.jpg)

For ease of reference this a picture of the wallet file.

Thanks

**Comment by izzys36** [comment]
Short update: i downloaded the wallet again, started syncing, then crashed, so i deleted the Chain File, (which i realised that it only appears after a sync or partial sync has taken place) and restarted the wallet, unfortunately, it crashed froze again. been doing that 2 or 3 times now. no luck so far.

**Comment by izzys36** [comment]
final Update: i downloaded the DOWNLOAD SYNCHRONIZE DATA OFFLINE file and copied it into the NEO Wallet file and kaboom. it worked. synced entire chain in less then 15 min. Seems to be working fine now.

All the best

**Comment by PoLabs** [comment]
Hi, I'm having the same issue. Could you please elaborate on your fix? 

Where did you find the 'DOWNLOAD SYNCHRONIZE DATA OFFLINE' file?
Where is the NEO wallet folder you copied it into?
