### ISSUE TITLE
Release does not contain neo-gui.exe.<version>.config 

### ISSUE THREAD

**Issue by kwaazaar** [neo-project/neo-gui#48]
It does not contain the files neo-gui.exe.testnet.config  and neo-gui.exe.mainnet.config. I also cannot find them in the source repository (only app.config exists).
According to this document, they should be there: http://docs.neo.org/en-us/node/testnet.html.

Result is that the gui will not connect to the testnet (default setup works fine on the mainnet).

**Comment by erikzhang** [comment]
"neo-gui.exe.<version>.config" files have been removed from latest version. You can use config.xxx.json and protocol.xxx.json

**Comment by kwaazaar** [comment]
You're closing this issue, but [the documentation](http://docs.neo.org/en-us/node/testnet.html) has not been fixed.

~~Also, mainnet immediately starts syncing, but testnet does nothing (height: 0/0, connected: 0).~~
Never mind, connecting eventually works. Just takes about an hour or so for it to start.

**Comment by acrigney** [comment]
Yes this doco issue should be fixed, I got the latest github code and it works
Except there was a missing reference to libleveldb.dll. I could not add a reference to this dll as I expect its unmanaged so I just included it in the bin folder and it was found.
