### ISSUE TITLE
Application crashing due to unhandled exception

### ISSUE THREAD

**Issue by cooke-m** [neo-project/neo-gui#5]
The AntSharesUI.exe application crashes periodically.  I used event viewer to search for the cause, and found a .Net runtime error and Application error for AntSharesUI.exe corresponding to each crash.  I have tried bringing this up about 10 times, and it always crashes with these errors, typically after less than an hour.

Application: AntSharesUI.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: exception code e06d7363, exception address 000007FEFCE6A06D 

Please advise on the best method to acquire more details for debugging.

**Comment by erikzhang** [comment]
It will create a file named "error.log" in application folder when it crashes. Can you find it and show me the content of the file?

**Comment by cooke-m** [comment]
Strangely, it has not been creating this file.  After trying several more attempts, it produced two back-to-back pairs of errors in the Event Log within a few seconds of each other at the time of the crash.  The second one produced an error.log:
 `
System.Runtime.InteropServices.SEHException
External component has thrown an exception.
   at AntShares.Implementations.Blockchains.LevelDB.Native.leveldb_open(IntPtr options, String name, IntPtr& error)
   at AntShares.Implementations.Blockchains.LevelDB.DB.Open(String name, Options options)
   at AntShares.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at AntShares.Program.Main()
`

And similar additional information in the event log:
`
Exception Info: System.Runtime.InteropServices.SEHException at 
AntShares.Implementations.Blockchains.LevelDB.Native.leveldb_open(IntPtr, System.String, IntPtr ByRef) at 
AntShares.Implementations.Blockchains.LevelDB.DB.Open(System.String, AntShares.Implementations.Blockchains.LevelDB.Options) at 
AntShares.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(System.String) at AntShares.Program.Main() 
`

The application error gives this information:
`
AntSharesUI.exe 
   1.6.6354.35073 
   5926c003 
   KERNELBASE.dll 
   6.1.7601.23807 
   5915fe14 
   e06d7363 
   000000000001a06d 
   1b3c 
   01d2eec301b3c00d 
   C:\<extract directory>\AntSharesCore\AntSharesUI.exe 
   C:\Windows\system32\KERNELBASE.dll 
   9c800485-5ab8-11e7-b9a8-002564f718ed 
`

I should note that at no time I see any Windows errors about the application crashing, it is just closed.

**Comment by erikzhang** [comment]
Is it x86 version of windows 7 you are using?

**Comment by cooke-m** [comment]
It is x86-64 (AMD64).  

I ended up installing a few optional .NET windows updates, and then it immediately crashed before the GUI even came up.  After trying this several times, I re-extracted and started with a new chain download, and it has been running for hours.  So it may be related to something with my blockchain download (it was not finished downloading in the other install) or related to these .NET updates, or some combination of the two.

**Comment by erikzhang** [comment]
It is related to leveldb I think.
