### ISSUE TITLE
Option to perform initial sync over HTTPS

### ISSUE THREAD

**Issue by skhameneh** [neo-project/neo-gui#55]
Simple feature request, if not seen as an issue, to request a sync over HTTPS.

e.g. Client will offer to download from "https://neo.org/client/chain.acc.zip" on first run.

**Comment by ghost** [comment]
I would be happy to work on this feature if approved by neo core team

**Comment by erikzhang** [comment]
@birmas You can talk about your idea of implementing first.

**Comment by ghost** [comment]
I would propose an implementation such as:

Upon program start, if Settings.Default.DataDirectoryPath (Chain|ChainTestNet) does not exist then prompt the user "do you wish to download a bootstrap file (chain.acc or chain.acc.test) to initalise NEO". Answering NO would continue execution to MainForm()

In the event the user chose YES we would redirect them to a simple dialog where they could choose to 
download mainnet or testnet (combobox with mainnet selected by default). 

Download would be performed with a progress bar showing progress and download speed. Download would be written to Application.StartupPath\chain.acc.(test.)zip

At 100% execution continues as normal and existing functionality in MainForm.cs would be responsible for extracting the zip file.

I would suggest that we could setup an s3 instance to host the files but would leave this to the discretion of neo team. For development purposes I would refer to neo.org/client/chain but put the URL list in a json file that could be added to.

**Comment by erikzhang** [comment]
Sounds good. Do it!
