### ISSUE TITLE
Supporting ICOs?

### ISSUE THREAD

**Issue by ghost** [neo-project/neo-gui#57]
When will the NEO gui wallet support ICOs like the NEON wallet does?

**Comment by erikzhang** [comment]
What do you mean by "supporting ICOs"?

**Comment by ghost** [comment]
being able to view the amount of tokens that you have(eg. viewing the
amount of RPX(Red Pulse) tokens that you have recieved on your NEO GUI
wallet)?

**Comment by ghost** [comment]
I don't think this really classifies as an "issue" when you have a viable alternative in neon to view your tokens

**Comment by ghost** [comment]
Even when people who bought in to the red pulse ICO(during the presale and
during the upcoming ICO september 11th) will wonder where the their tokens
are on the official NEO CLI wallet?

**Comment by ghost** [comment]
The Devs are working on nep5 support, there is a branch for it on GitHub. I just don't think this question belongs in issues.

**Comment by erikzhang** [comment]
We will release a new version next week. Just need more tests.
https://github.com/neo-project/neo-gui/tree/feature/NEP-5
