### ISSUE TITLE
neo-gui.exe opens as background pocess when neo-cli process is running on the same node

### ISSUE THREAD

**Issue by arthurgreef** [neo-project/neo-gui#62]
The neo-gui UI does not open when the exe is started after the neo-cli process has also been started.

**Comment by arthurgreef** [comment]
I did a little more investigation and here is how to reproduce this problem.

1. Open command prompt and run "dotnet neo-cli.dll
2. Open neo-gui.exe and the UI does not open.
3. Stop the neo-cli process
4. Open neo-gui and the UI opens as expected.

I'm not sure how to run the cli and gui processes on the same node. It was possible to do this with the antshares gui and this is what the documentation for setting up a private chain describes.

**Comment by arthurgreef** [comment]
It is also the case that the neo-cli process hangs if it is started after the neo-gui app has been opened.

**Comment by erikzhang** [comment]
They can't access the database at the same time.

**Comment by arthurgreef** [comment]
Which database? The wallet database or the ledger database, and is this a problem that will be fixed? Thanks.

**Comment by erikzhang** [comment]
The ledger database. It won't be fixed. You can modify config.json to specify a different directory for database.

**Comment by arthurgreef** [comment]
OK, great. Thanks.

**Comment by arthurgreef** [comment]
Hi Erik – I changed the folder name of the gui config file. When I run the cli and the gui now I no longer see utxo’s and account balances in the cli or the gui. When I rebuild the index, the gui displays the correct address balance for about ½ a second and then it shows 0 again. Have you encountered this problem before? I’m not sure how to fix it. Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by arthurgreef** [comment]
I changed the Chain folder name to Chain0 in the gui config file. When I execute "show utxo" I get "total: 0 utxos" as a result and when I run "list asset" I get no data returned. When I rebuild the index, the gui displays the correct address balance for about ½ a second and then it shows 0 again. The problem is not fixed even if I revert my folder name change. Any ideas? Thanks.
