### ISSUE TITLE
Do systemfee setting work?

### ISSUE THREAD

**Issue by arthurgreef** [neo-project/neo-gui#68]
Hi - I have set up a private blockchain and I'd like to deploy and use contracts at no fee. Is this possible by setting the system fees to 0? Can we make this possible? Thanks.

    "SystemFee": {

      "EnrollmentTransaction": 0,

      "IssueTransaction": 0,

      "PublishTransaction": 0,

      "RegisterTransaction": 0

    }

**Comment by erikzhang** [comment]
You need to change the source code:
https://github.com/neo-project/neo/blob/master/neo/SmartContract/ApplicationEngine.cs
