### ISSUE TITLE
Is there any instructions or guides on how to build this on linux?

### ISSUE THREAD

**Issue by pitersky** [neo-project/neo-gui#7]
Hi

We have researched documentation and did not find any instructions on how to build this on linux platform. Is there any? Is there any working linux builds?

**Comment by erikzhang** [comment]
You can build CLI client on Linux, but GUI will not be.
To build it on Linux, you need to install [.Net Core](https://www.microsoft.com/net/download/core) first.
And then type "dotnet build" to build it.
