### ISSUE TITLE
Unable to claim GAS

### ISSUE THREAD

**Issue by panther142** [neo-project/neo-gui#70]
Unable to claim GAS as button on ClaimForm is always greyed out (unavailable).  If this is due to a minimum number of GAS being required before claiming is available, this should be shown on the form.

**Comment by Renster123** [comment]
I have the same problem. It shows there are gas, just unavailable. Did you figure it out?

**Comment by lesterdsa** [comment]
Iam having the same issue the wallet shows i have a xx amount of GAS but ,iam unable to transfer it or use it .

**Comment by jonatanblockchain** [comment]
On the desktop wallet NEO-gui you need to send your NEOs to yourself, then the gas becomes available.

Note: you can just send 1 NEO your first time, if you just wanna test it out. Once the transaction is confirmed (see "Transaction History" tab) go to "Advanced" click "NeoGas Claim". You will now be able to claim your available Gas and they will show up in your wallet.

**Comment by surenjay89** [comment]
Did this work for anyone?

**Comment by panther142** [comment]
Yes this does work but it is not documented in the GUI like a lot of things.

**Comment by Yippyiyo** [comment]
Thank you  Jonatanblockchain. Worked for me!

**Comment by Yippyiyo** [comment]
So every time you want to claim your GAS, you have to re-send all your NEOs?

Is that correct?

**Comment by Yippyiyo** [comment]
Answering my own question - Yes and NO. Each time you want to claim you must follow the transfer to self procedure.
 
Also note that the Gas could be transferred after I sent only ONE Neo to myself. As soon as you have one confirmation in TRANSACTION HISTORY open the ADVANCED / NeoGas claim and away you go. Will leave a small Gas balance (0.000xxxxx) in the NeoGas Claim dialogue box.
https://www.youtube.com/watch?v=EWtDTH8G25A

**Comment by panther142** [comment]
Yes.  If you use the NEON wallet when you click claim GAS it does it for you.
