### ISSUE TITLE
Unable to use the claimed GAS

### ISSUE THREAD

**Issue by lesterdsa** [neo-project/neo-gui#71]
The wallet shows i have a xx amount of claimed GAS but ,iam unable to transfer it or use it .

Iam using the latest NEO wallet 2.3.6458.21374

**Comment by jonatanblockchain** [comment]
See #70

**Comment by lesterdsa** [comment]
Im unable to use the claimed GAS .

I do know how to claim the GAS but once claimed ,cannot use it ,its not every time but 5+ GAS is stuck there

**Comment by erikzhang** [comment]
Try to rebuild index?

**Comment by Yippyiyo** [comment]
There are links re this.

You need to send the NEO you have to yourself and the GAS will then become claimable.

Search here and on youtube and you will find the simple answer.

**Comment by donnyque** [comment]
I have the same issue as you, I think. #100 

Have you found a solution?
