### ISSUE TITLE
ZERO balans on my wallets

### ISSUE THREAD

**Issue by topkurs** [neo-project/neo-gui#72]
Hello!
Today I have loaded my Neo Gui wallet, latest version - 2.3
And find zero! (0) balans and no transactions.
In public tracker https://neotracker.io I see all my NEOs, see it correctly
So coins are registered in the blockchain and still my (no theft)_

I tried to Rebuid index, but it doesn't helps.
Wallet is fully synchronizes.
Also I have tried to reload / reimport wallet. It doesn't help :(

Similar problems: 
https://steemit.com/cryptocurrency/@guppyken/neo-antshares-wallet-does-not-show-your-balance-this-may-help
https://bitcointalk.org/index.php?topic=2029639

Why my Neo Wallet show me zero balance? How to fix it?
How to fix?

**Comment by topkurs** [comment]
Tried to reinstall. This one - https://github.com/neo-project/neo-gui/releases/download/v2.3.2/neo-gui-windows.zip
No results, I still have ZERO on my neo-gui wallet.

**Comment by topkurs** [comment]
Tried to deposit my wallet for 1 NEO, it's successfully added to my main balance, to my wallet.
I can see it on https://neotracker.io
I see transactions and the whole balance, loaded to my wallet.
But in my neo-gui wallet is 0 NEOs, it's empty!

What is going on? How to fix this? I have tried everything :(

**Comment by Decipherist** [comment]
I had the same issue, I could see my NEO on neotracker.io but not in my gui wallet. Took 4 days to show in my wallet now.

**Comment by topkurs** [comment]
jimmycrypto, have you done something? Or it had corrected by itself?

**Comment by Decipherist** [comment]
It corrected by itself.

I suspect it has something to do with needing to accumulate gas so it can be processed but I cannot be sure that is the reason.

**Comment by topkurs** [comment]
I'm shocked and don't know, what to do. How can I find my coins? Whats going on with this wallet neo-gui?

**Comment by Decipherist** [comment]
Your coins are not lost. Do not worry. Take some time to relax.
If you have your db3 file your coins are safe.
If you open your wallet database, double click your address in your wallet you can see your coins are there at- www.antchain.xyz/address/xxxxxxxxxxxxxx

They will appear in the wallet and start accumulating neogas 
Just take some time like mine did

**Comment by Pirozek** [comment]
I think this "detail" should be at least mentioned in the software. When using NEON wallet I see my NEO almost instantly

**Comment by Decipherist** [comment]
This occurred on the very first NEO transaction I had performed. 
I have not yet transacted again to see if it takes just as long or if it is visible immediately in the GUI.
As mentioned, I could see the coin was there at antchain at the correct address and I have the db3 file so no panic.

**Comment by vanpotheos** [comment]
Using this wallet distro you HAVE to synchronize the entire blockchain to the NEO wallet before your tokens become visible. They are stored on the blockchain, of course. You just can't 'see' them because you haven't downloaded this transaction yet.

It's important that you leave the NEO wallet running until it is fully synchronized. The longer the wallet is available the longer it will take to download the entire thing. When I first downloaded the ANS wallet it took about 18 hours the first time I opened the file. I imagine that it will only take longer now.

Hope this helps you understand how this wallet works.

**Comment by vanpotheos** [comment]
Going through and reading this I'm seeing that you're in a slight state of panic. I'm kind of surprised you didn't know about this already, as this is how the wallet has worked from day one. If you want to see your funds INSIDE of your wallet 'instantaneously' you must wait until the little numbers in the bottom left corner of the wallet / GUI match up exactly. 

Only then can any of us see our funds. This is the most secure way for the wallet to function. As you aren't relying on a third party (who can obfuscate transactions) to download the blockchain for you. This is the official NEO GUI and wallet. 

If you don't want to download the blockchain every time there is a wallet update then some people suggest that you should use the NEON wallet. If you're less paranoid, this may be a fine option for you.
If you're taking every possible step and precaution against losing your funds / being hacked, then you'll feel most comfortable using the official NEO wallet.

**In order of operation, then!**

Verify the Checksum of the zip you downloaded to confirm the wallet you downloaded is legit. I use Kleopatra for Windows. Just right click > moreGpEX options > Create Checksum. Make sure the string is identical and you're good.

Open NEO-GUI.EXE

Wait for SEVERAL HOURS until the numbers on the bottom left sync up. 

Will look something like: 

**Height: 44435/412356 Connected: 7**
^ These are the numbers that must match to see your tokens
This is what it will look like at the **beginning** of the sync process. There are currently (at time of writing) 1,413,913 blocks on the NEO chain.

Therefore, to be synced (right now) the numbers here should say; 

**Height: 1,413,913/1,413,913**

Only when you see something like what you see above, will you be able to "see" your wallet balance.
Of course, if you haven't left the GUI running you'll basically just pick up where you left off the last time you closed it.

"Connected" means how many peers you are downloading from. More = Faster.

All of this seems irritating at first, and it is. But it is the official and most secure method of storing coins on your desktop. Once the chain is fully synced your transactions, deposits, and withdrawals will appear almost instantly.

Hope this helps to anyone suffering the same misunderstanding of how the wallet works.

**Comment by vanpotheos** [comment]
And now I will officially SPAM this post. Just looking around the files we have downloaded I noticed a file in the GUI called "Chain".

I'm assuming this is the Chain which has already been downloaded / synced. If you still have the old version of the wallet downloaded onto your computer I assume that you should be able to copy / paste this file into the latest version of the wallet you are attempting to use. If this wallet was synced fully then using this technique should allow you to see your funds in the wallet much more quickly than re-starting and downloading the entire chain again from scratch.

If the Dev's would like to chime in to confirm this I would very much appreciate it. Will test now.

Edit: Got it to work, but you have to delete the new GUI files (not the ZIP!) if you want it to work. Can't just drag / drop the Chain file over from your old GUI into the new one if you've already attempted to open it. 
It does appear to work if the GUI is in it's 'brand new' state. Anyway, it's "height" is an entire 1 GB farther along than the one I was attempting to sync from scratch.

**Comment by topkurs** [comment]
I have fully synchronized wallet. And this wasn't my first transaction, I have 6 tranactions before
I don't know, what to do.
Maybe to try NEON wallet? I haven't tried it yet.

On Neo Gui I still have 0 neos on wallet. And on antichain/neotracker.io everything is OK, funds are displayed.

**Comment by topkurs** [comment]
What to do? Can you help me? Whats going on with this wallet???

**Comment by surenjay89** [comment]
I'm having the same exact problem. Except, it's my first time using the wallet. Downloaded the offline sync file and my wallet is synched at 1.4 mil /1.4mil. Coins are still not in. When I double click on the address it takes me to the page where I clearly see my NEO balance but for some reason, it won't show in the wallet. How do I fix this? Will I be able to transfer my NEO without them appearing? Any help would be appreciated.

**Comment by surenjay89** [comment]
I had the same problem initially. But when the height was fully in sync 1.4mil/1.4mil my NEO balance updated.

**Comment by Decipherist** [comment]
Just leave neo-gui open and do nothing. Let it synchronize and your coin balance will show.

**Comment by topkurs** [comment]
I have done it. Leave for ~24h
No result. Wallet is empty! And coins on wallet exists.
How much time do I need? For how long should I leave it opened?

**Comment by Thenagain32** [comment]
I've been having exactly the same problem. Neo GUI was synchronizing for almost a day and then it was still 0 balance. Really disturbing.

Now, I don't know how to fix Neo GUI but if you just want to access your balance try this:

1. Download NEON wallet from the official Neo site.
2. Run Neo GUI and login.
3. Right-click on your address and copy the WIF private key.
4. Run NEON and use the key to login.
5. You'll see your balance and will be able to send it.

**Comment by Donksy28** [comment]
My Height and Connections just say 0 theres nothing even there any one know what i have to do ?
i checked my network activity and theres 0 activity no data being sent my firewall is set to allow it thru i turned firewall off still 0

**Comment by Donksy28** [comment]
Thenagain32 your comment help me alot thanks my neo gui wont work either but now i can access my stuff using private key in neon thanks heaps :)

**Comment by Thenagain32** [comment]
Glad I could help!

**Comment by bcduddupudi** [comment]
can anyone help me i had 2 NEO wallets and i'm the investor in redpulse ,in one account the redpluse assets shows up including neo and gas, but in another wallet ,my neo and gas doesn't shows up but it shows redpulse assets ,I want to move this redpulse assets to the main working wallet can anyone help me,i'm Still not sure  why the NEO and Gas is showing up as 0 in the main wallet even though it contains 34 neos and 1 gas  ,i can see the neos when i used the key on NEON wallet but not on the NEO wallet

**Comment by meropaisa** [comment]
hey @topkurs, did you find a solution? I am facing a similar issue with my wallet.
