### ISSUE TITLE
Zero Neo & Gas Balance after block sync. 

### ISSUE THREAD

**Issue by BJamesK** [neo-project/neo-gui#75]
Hi,

I recently installed the latest NEO-GUI wallet on my desktop, downloaded the chain.acc file and synced my block. However, I currently am stuck at 1314993/1314993, with no connected nodes even after restarting the application several times. I also do not have any neo/gas in the wallet imported ( i verified it is on the block chain though).

Please help.

![image](https://user-images.githubusercontent.com/32416412/31046785-119d5a98-a5f7-11e7-9456-091a3321dfff.png)

**Comment by jonatanblockchain** [comment]
Try:
1. Move peers.dat file outside root Neo-gui folder, for example c:\TEMP
2. Start Neo-gui

**Comment by BJamesK** [comment]
@jonatanblockchain 

Tried that. Still stuck with no nodes connected. Any other suggestions?

**Comment by jonatanblockchain** [comment]
Neo-gui version? Do you have any firewall/antivirus blocking neo-gui.exe?
Did you move (or delete) `peers.dat` with the neo-gui stopped?

**Comment by BJamesK** [comment]
@jonatanblockchain 
No firewall blocking this particular program. 
And Yes, moved the peers.dat file while neo-gui was stopped. Thanks.

**Comment by gwindy** [comment]
@BJamesK @jonatanblockchain This appears to be a common problem.  I have had the same issue and there are similar queries on the Reddit site.  I have Windows 8 and discovered that all the .dll files contained in the folder had been blocked (not by my  firewall).  Right click on each dll file individually to display the properties box.  Under the 'General' tab at the very bottom, my .dll files showed up as blocked.  Click the 'unblock' button.  Repeat for all the dll files.  This enabled me to finally open the wallet and displayed my tokens/gas.  My number of connections remains at O, but at least the walllet seems to work for me now.  Let me know how you go, and I hope this helps :)

**Comment by BJamesK** [comment]
@gwindy  @jonatanblockchain 
Thanks for the assistant. However, having unblocked all the dll files in the neo folder, I still cannot see my NEO/GAS balance. Will keep searching for a work around.

**Comment by gwindy** [comment]
@BJamesK Now try opening the wallet, then select 'Rebuild Index' under the Wallet tab.

**Comment by gwindy** [comment]
@BJamesK Please bear with me, I just got mine working fully.  These steps might sound weird but was a lot easier than unblocking each dll file. .If you are going to download the RXP version, then this also applies....

1. Download and Extract the Neo zip folder;
2. Rezip/Compress the extracted folder (right click, send to, compressed (zipped) folder;
3. Extract the same zipped folder again;
4. Check the dll files (the unblock security tab should no longer be showing under Properties tab);
5. Run the neo.exe

Good luck i hope :)

**Comment by BJamesK** [comment]
@gwindy 
Great. However I had to individually unblock all of the .dll files after unzipping the NEO-GUI RXP version. I also downloaded the chain.acc file. I can now see my Neo/Gas. 

However, i am still unable to connect to any node. I tried sending some neo to another address, but it is showing as unconfirmed. This transaction is also not on the block chain, but the number of neo has reduced on my Neo Gui wallet.

see screen shot below of what i noticed:
![image](https://user-images.githubusercontent.com/32416412/31135952-96cc7474-a85e-11e7-8c46-029d9b89fbc9.png)

![image](https://user-images.githubusercontent.com/32416412/31136000-bb65e09a-a85e-11e7-8d81-33e4f52a1a42.png)
Thanks.

**Comment by gwindy** [comment]
@BJamesK Getting close man.  You need to keep unzipping/extracting the downloaded folder until the dll files are no longer showing up as blocked under properties tab.  Extract the folder to the desktop, then compress it, then re-extracted the compressed folder.  It should work hopefully.

No need to keep re-downloading the chain folder either.  Just copy and paste the chain subfolder from your old neo folder into the new extracted neo folder.

**Comment by petlap** [comment]
I still can't connect either, any help? I've tried literally everything
