### ISSUE TITLE
Cannot find Redpulse Tokens

### ISSUE THREAD

**Issue by jgiral35** [neo-project/neo-gui#87]
Last sunday I participated in the RPX ICO... a friend sent me some tokens to my NEO GUI adress, but i can't see them in my account! The transaction has been verified by the platform. PLEASE HELP!!

**Comment by C3KTAHT** [comment]
Go to your Neo GUI, fully sync, go to contracts, watch, enter script hash for the ICO, press OK, and you should see them under your Asset tab
