### ISSUE TITLE
No null checking /AntSharesCore/AntSharesUI/UI/AssetRegisterDialog.cs

### ISSUE THREAD

**Issue by geri43** [neo-project/neo-gui#9]
When using "Asset Registration", the Confirm button is always enabled. 
But there is no null checking for the Owner, Admin, and the Issuer fields, so if the users leaves it empty, the program throws an exception.

Also, not giving a Name for the asset doesn't throw any errors.

**Comment by erikzhang** [comment]
fixed in 7b63764
