### ISSUE TITLE
Neo not appear in my wallet please help

### ISSUE THREAD

**Issue by Donksy28** [neo-project/neo-gui#90]
hey guys i sent neo to my wallet but its not there i checked neo tracker and its in my wallet 

but thru Neo Gui my height says 0/0 and connections 0

i notice in all videos everyone else has numbers 

i tried the rebuild index but nothing happened 

any ideas ??? im sweating wheres my neo lol......

**Comment by Donksy28** [comment]
ok so now its synced but it shows 0 connections and no network activity aswell im on windows 10 ive checked and done everything i know of but nothing

**Comment by AxelTwin** [comment]
I have the same problem. I downloaded the wallet on windows 10, created a "wallet.db3" file and opened it withe the neo wallet. then I transfered neo to the address, checked on neo tracker and it looks like this address has been credited. But nothing appears in the neo wallet....

**Comment by Phetatron** [comment]
got the same problem, just finished the sync and the amount is not in the wallet, checked the wallet address online and it is credited to the address....

**Comment by Yippyiyo** [comment]
This worked for me in win7.
Try it, as you have nothing to lose.

Make sure you have the very latest NEO-GUI wallet.
https://github.com/neo-project/neo-gui/releases/tag/v2.3.5
(released 5 minutes ago)

Install it under a different folder e.g. NEO2

Create a NEW wallet and use the sent to address  db3 address file (in your original wallet) as the new db3 wallet. This addres should be the same address you originally sent the NEO to, but it is now in the new / latest wallet.

May take a bit of time to get there but this may work.

This worked for me.

**Comment by WDRpl** [comment]
neo-gui v2.3.6. I send NEO from bitfinex to my wallet address. Nothing appear - balance 0. I have confirmation on tracker. Who i need to contact to get my Neo's back?
