### ISSUE TITLE
CERTENROLLLib missing AlgorithmName in interface (causes crash in CertificateRequestWizard)

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-gui#97]
`CertificateRequestWizard` on [Line41](https://github.com/neo-project/neo-gui/blob/243885d713c5f933703ca944853be8c513d31a68/neo-gui/UI/CertificateRequestWizard.cs#L41) tries to access `AlgorithmName`. The `CX509PrivateKey` interface does not have this key on my system. 

I verified with another user on slack that we both have version 1.0.0.0 of CERTENROLLLib. My interface misses the key as it appears to be equal to this version: [msdn IX509PrivateKey interface](https://msdn.microsoft.com/en-us/library/windows/desktop/aa378921(v=vs.85).aspx)

Commenting out the line allows me to build, but not to generate a certificate. Similarly, when downloading release [2.3.5](https://github.com/neo-project/neo-gui/releases/download/v2.3.5/neo-gui-windows.zip) from github and running that also results in an exception when trying to generate a certificate. Specifically:
> “No such interface supported” in CERTENROLLib.CX509PrivateKey

Platform: win7 x64 SP1

**Comment by erikzhang** [comment]
It seems that `AlgorithmName` is available on Windows 10 only.
