### ISSUE TITLE
zero balance neo after synchronization neogaz after synchronization appeared

### ISSUE THREAD

**Issue by sergeymezin** [neo-project/neo-gui#98]
That's my problem.
Theoretically NEO is on the purse. If you write the purse address in Neotraker, it shows them, but the purse does not display them. The transaction that was made from the wallet to the stock exchange is not in the block, but the transaction in the wallet is not confirmed, and this is not confirmed. Is there a way to cancel the transaction and return the coins to the wallet?
The instruction on this address did not bring the result https://steemit.com/cryptocurrency/@guppyken/neo-antshares-wallet-does-not-show-your-balance-this-may-help

address wallet Neotraker https://neotracker.io/address/ATQWSYvaRgb4gM8nNxZyFfimJb4spZhLCq
please, help! if you know how to help send detailed instructions with pictures

![1](https://user-images.githubusercontent.com/33490840/32558395-b38c80cc-c4b5-11e7-9edb-b1919d628158.JPG)
![2](https://user-images.githubusercontent.com/33490840/32558396-b3aeb1d8-c4b5-11e7-8523-3a7df6b547e5.JPG)
![3](https://user-images.githubusercontent.com/33490840/32558397-b3d1b67e-c4b5-11e7-90ef-94e0f196d9c6.JPG)
![4](https://user-images.githubusercontent.com/33490840/32558399-b45ef782-c4b5-11e7-8fea-ae3c11a52718.jpg)
![5](https://user-images.githubusercontent.com/33490840/32558401-b482ff9c-c4b5-11e7-850b-c778c242f3f7.JPG)

**Comment by jonatanblockchain** [comment]
Its full sync? Then try rebuild the index on neo-gui. Wallet-> Rebuild index,
If not, open you wallet on neotracker and claim gas and sync your neo-gui
